-- Veyn: expands the Academy spelling search tool's term list
-- (account/spelling-search.html) with 660 new terms across
-- migration_51_spelling_terms_filters.sql's body_area/specialty columns —
-- 30 medication/anatomy terms for every one of the 21 specialties in
-- SPECIALTIES (specialties-data.js), plus a further 30 general medications
-- on top. Brings the table from 305 to 965 rows.
-- Run this in the Supabase SQL editor, after migration_51.
insert into spelling_terms (term, category, phonetic, aliases, body_area, specialty) values
('Glabella', 'anatomy', 'gla-BEL-a', ARRAY['glabela', 'glabelia']::text[], 'Head & neck', 'Aesthetic medicine'),
('Nasolabial fold', 'anatomy', 'nay-zo-LAY-bee-al', ARRAY['naso labial fold', 'nasolabal fold']::text[], 'Head & neck', 'Aesthetic medicine'),
('Malar fat pad', 'anatomy', 'MAY-lar', ARRAY['maler fat pad', 'malar fatpad']::text[], 'Head & neck', 'Aesthetic medicine'),
('Orbicularis oculi', 'anatomy', 'or-bik-yoo-LAIR-is OK-yoo-ly', ARRAY['orbicularus oculi', 'orbicularis occuli']::text[], 'Head & neck', 'Aesthetic medicine'),
('Platysma', 'anatomy', 'pla-TIZ-ma', ARRAY['platisma', 'platysmal']::text[], 'Head & neck', 'Aesthetic medicine'),
('Philtrum', 'anatomy', 'FIL-trum', ARRAY['filtrum', 'philtrium']::text[], 'Head & neck', 'Aesthetic medicine'),
('Zygomatic arch', 'anatomy', 'zy-go-MAT-ik', ARRAY['zigomatic arch', 'zygomattic arch']::text[], 'Head & neck', 'Aesthetic medicine'),
('Mentalis muscle', 'anatomy', 'men-TAL-is', ARRAY['mentalus muscle', 'mentails muscle']::text[], 'Head & neck', 'Aesthetic medicine'),
('Frontalis muscle', 'anatomy', 'fron-TAL-is', ARRAY['frontails muscle', 'frontalus muscle']::text[], 'Head & neck', 'Aesthetic medicine'),
('Corrugator supercilii', 'anatomy', 'KOR-oo-gay-tor soo-per-SIL-ee-eye', ARRAY['corrugater supercilii', 'corrugator superciliy']::text[], 'Head & neck', 'Aesthetic medicine'),
('Levator labii superioris', 'anatomy', 'le-VAY-tor LAY-bee-eye', ARRAY['levator labi superioris', 'elevator labii superioris']::text[], 'Head & neck', 'Aesthetic medicine'),
('Buccal fat pad', 'anatomy', 'BUK-al fat pad', ARRAY['buckal fat pad', 'buccal fatpad']::text[], 'Head & neck', 'Aesthetic medicine'),
('Submental area', 'anatomy', 'sub-MEN-tal', ARRAY['sub mental area', 'submentel area']::text[], 'Head & neck', 'Aesthetic medicine'),
('Marionette lines', 'anatomy', 'ma-ree-o-NET', ARRAY['marrionette lines', 'marionete lines']::text[], 'Head & neck', 'Aesthetic medicine'),
('Vermillion border', 'anatomy', 'ver-MIL-yun', ARRAY['vermilion border', 'vermillian border']::text[], 'Head & neck', 'Aesthetic medicine'),
('Tear trough', 'anatomy', 'teer trof', ARRAY['tear trof', 'teartrough']::text[], 'Head & neck', 'Aesthetic medicine'),
('Temporal fossa', 'anatomy', 'TEM-po-ral FOS-a', ARRAY['temporel fossa', 'temporal fosa']::text[], 'Head & neck', 'Aesthetic medicine'),
('Preauricular region', 'anatomy', 'pree-aw-RIK-yoo-lar', ARRAY['pre auricular region', 'preauricula region']::text[], 'Head & neck', 'Aesthetic medicine'),
('Mandibular angle', 'anatomy', 'man-DIB-yoo-lar', ARRAY['mandibula angle', 'mandibuar angle']::text[], 'Head & neck', 'Aesthetic medicine'),
('Nasojugal groove', 'anatomy', 'nay-zo-JOO-gal', ARRAY['naso jugal groove', 'nasojugual groove']::text[], 'Head & neck', 'Aesthetic medicine'),
('Depressor anguli oris', 'anatomy', 'de-PRES-or ANG-yoo-ly OR-is', ARRAY['depressor angulii oris', 'depressor anguli oriss']::text[], 'Head & neck', 'Aesthetic medicine'),
('Risorius muscle', 'anatomy', 'ri-ZOR-ee-us', ARRAY['risorious muscle', 'risorius mussle']::text[], 'Head & neck', 'Aesthetic medicine'),
('Columella', 'anatomy', 'kol-yoo-MEL-a', ARRAY['columela', 'columellar']::text[], 'Head & neck', 'Aesthetic medicine'),
('Zygomaticus major muscle', 'anatomy', 'zy-go-MAT-i-kus', ARRAY['zygomatikus major', 'zygomaticus mayor muscle']::text[], 'Head & neck', 'Aesthetic medicine'),
('Botulinum toxin', 'medication', 'BOT-yoo-ly-num', ARRAY['botulinim toxin', 'botullinum toxin']::text[], 'Skin', 'Aesthetic medicine'),
('Hyaluronic acid', 'medication', 'hy-a-loo-RON-ik', ARRAY['hyaluronic assid', 'hyalauronic acid']::text[], 'Skin', 'Aesthetic medicine'),
('Calcium hydroxylapatite', 'medication', 'hy-drox-il-AP-a-tite', ARRAY['calcium hydroxyapatite', 'calcium hydroxlapatite']::text[], 'Skin', 'Aesthetic medicine'),
('Poly-L-lactic acid', 'medication', 'POL-ee el LAK-tik', ARRAY['poly l lactic acid', 'polylactic acid']::text[], 'Skin', 'Aesthetic medicine'),
('Deoxycholic acid', 'medication', 'dee-ox-ee-KOL-ik', ARRAY['deoxycolic acid', 'de-oxycholic acid']::text[], 'Skin', 'Aesthetic medicine'),
('Polydioxanone', 'medication', 'pol-ee-dy-OX-a-known', ARRAY['polydioxanone thread', 'poly dioxanone']::text[], 'Skin', 'Aesthetic medicine'),
('Digoxin', 'medication', 'di-JOX-in', ARRAY['digoxen', 'digoxine']::text[], 'Cardiovascular', 'Cardiology'),
('Amiodarone', 'medication', 'a-my-OH-da-rone', ARRAY['amioderone', 'amiodarone tablets']::text[], 'Cardiovascular', 'Cardiology'),
('Verapamil', 'medication', 've-RAP-a-mil', ARRAY['verapamyl', 'veropamil']::text[], 'Cardiovascular', 'Cardiology'),
('Diltiazem', 'medication', 'dil-TY-a-zem', ARRAY['diltiazam', 'diltiezem']::text[], 'Cardiovascular', 'Cardiology'),
('Nicorandil', 'medication', 'ny-KOR-an-dil', ARRAY['nicorandel', 'nichorandil']::text[], 'Cardiovascular', 'Cardiology'),
('Ivabradine', 'medication', 'eye-VAB-ra-deen', ARRAY['ivabradin', 'ivobradine']::text[], 'Cardiovascular', 'Cardiology'),
('Sacubitril-valsartan', 'medication', 'sa-KYOO-bi-tril val-SAR-tan', ARRAY['sacubitril valsartan', 'sacubatril valsartan']::text[], 'Cardiovascular', 'Cardiology'),
('Eplerenone', 'medication', 'ep-LER-e-known', ARRAY['eplerenon', 'eplereknone']::text[], 'Cardiovascular', 'Cardiology'),
('Isosorbide mononitrate', 'medication', 'eye-so-SOR-bide mon-o-NY-trate', ARRAY['isosorbide mononitrat', 'iso sorbide mononitrate']::text[], 'Cardiovascular', 'Cardiology'),
('Glyceryl trinitrate', 'medication', 'GLIS-er-il try-NY-trate', ARRAY['glyceril trinitrate', 'glyceral trinitrate']::text[], 'Cardiovascular', 'Cardiology'),
('Adenosine', 'medication', 'a-DEN-o-seen', ARRAY['adenosin', 'adenozine']::text[], 'Cardiovascular', 'Cardiology'),
('Flecainide', 'medication', 'FLEK-a-nide', ARRAY['flecanide', 'flecainide tablets']::text[], 'Cardiovascular', 'Cardiology'),
('Sotalol', 'medication', 'SO-ta-lol', ARRAY['sottalol', 'sotolol']::text[], 'Cardiovascular', 'Cardiology'),
('Dronedarone', 'medication', 'dro-NED-a-rone', ARRAY['dronedaron', 'dronederone']::text[], 'Cardiovascular', 'Cardiology'),
('Ranolazine', 'medication', 'ra-NOL-a-zeen', ARRAY['ranolazin', 'renolazine']::text[], 'Cardiovascular', 'Cardiology'),
('Endocardium', 'anatomy', 'en-do-KAR-dee-um', ARRAY['endocardum', 'endocardeum']::text[], 'Cardiovascular', 'Cardiology'),
('Epicardium', 'anatomy', 'ep-i-KAR-dee-um', ARRAY['epicardum', 'epicardeum']::text[], 'Cardiovascular', 'Cardiology'),
('Chordae tendineae', 'anatomy', 'KOR-day ten-DIN-ee-ay', ARRAY['cordae tendineae', 'chordae tendinae']::text[], 'Cardiovascular', 'Cardiology'),
('Papillary muscles', 'anatomy', 'PAP-i-lar-ee', ARRAY['papilary muscles', 'papillory muscles']::text[], 'Cardiovascular', 'Cardiology'),
('Bundle of His', 'anatomy', 'bundle of hiss', ARRAY['bundle of hiss', 'bundle of hys']::text[], 'Cardiovascular', 'Cardiology'),
('Purkinje fibres', 'anatomy', 'per-KIN-jee', ARRAY['purkinje fibers', 'perkinje fibres']::text[], 'Cardiovascular', 'Cardiology'),
('Interventricular septum', 'anatomy', 'in-ter-ven-TRIK-yoo-lar', ARRAY['inter ventricular septum', 'interventricula septum']::text[], 'Cardiovascular', 'Cardiology'),
('Interatrial septum', 'anatomy', 'in-ter-AY-tree-al', ARRAY['inter atrial septum', 'interatrial septem']::text[], 'Cardiovascular', 'Cardiology'),
('Left atrium', 'anatomy', 'AY-tree-um', ARRAY['left atrum', 'left aitrium']::text[], 'Cardiovascular', 'Cardiology'),
('Right atrium', 'anatomy', 'AY-tree-um', ARRAY['right atrum', 'right aitrium']::text[], 'Cardiovascular', 'Cardiology'),
('Left ventricle', 'anatomy', 'VEN-tri-kul', ARRAY['left ventrical', 'left ventrikle']::text[], 'Cardiovascular', 'Cardiology'),
('Right ventricle', 'anatomy', 'VEN-tri-kul', ARRAY['right ventrical', 'right ventrikle']::text[], 'Cardiovascular', 'Cardiology'),
('Coronary arteries', 'anatomy', 'KOR-o-na-ree', ARRAY['coronery arteries', 'coronary artiries']::text[], 'Cardiovascular', 'Cardiology'),
('Pulmonary artery', 'anatomy', 'PUL-mo-na-ree', ARRAY['pulminary artery', 'pulmonery artery']::text[], 'Cardiovascular', 'Cardiology'),
('Inferior vena cava', 'anatomy', 'VEE-na KAH-va', ARRAY['inferior vena cavae', 'inferior venacava']::text[], 'Cardiovascular', 'Cardiology'),
('Betamethasone', 'medication', 'bay-ta-METH-a-zone', ARRAY['betamethasome', 'betametasone']::text[], 'Skin', 'Dermatology'),
('Clobetasol propionate', 'medication', 'klo-BET-a-sol', ARRAY['clobetasal propionate', 'clobetesol propionate']::text[], 'Skin', 'Dermatology'),
('Tacrolimus', 'medication', 'ta-KROL-i-mus', ARRAY['tacrolimis', 'tachrolimus']::text[], 'Skin', 'Dermatology'),
('Pimecrolimus', 'medication', 'py-me-KROL-i-mus', ARRAY['pimecrolimis', 'pymecrolimus']::text[], 'Skin', 'Dermatology'),
('Calcipotriol', 'medication', 'kal-si-PO-tree-ol', ARRAY['calcipotriole', 'calcipotrial']::text[], 'Skin', 'Dermatology'),
('Coal tar', 'medication', 'kole tar', ARRAY['coaltar', 'cole tar']::text[], 'Skin', 'Dermatology'),
('Salicylic acid', 'medication', 'sal-i-SIL-ik', ARRAY['salycilic acid', 'salicilic acid']::text[], 'Skin', 'Dermatology'),
('Benzoyl peroxide', 'medication', 'BEN-zoyl pe-ROX-ide', ARRAY['benzyl peroxide', 'benzoil peroxide']::text[], 'Skin', 'Dermatology'),
('Dapsone', 'medication', 'DAP-sone', ARRAY['dapzone', 'dapson']::text[], 'Skin', 'Dermatology'),
('Minocycline', 'medication', 'min-o-SY-kleen', ARRAY['minocyclin', 'minocycline capsules']::text[], 'Skin', 'Dermatology'),
('Ustekinumab', 'medication', 'us-te-KIN-yoo-mab', ARRAY['ustekinumumab', 'ustekinemab']::text[], 'Skin', 'Dermatology'),
('Secukinumab', 'medication', 'se-KYOO-kin-yoo-mab', ARRAY['secukinumumab', 'sekukinumab']::text[], 'Skin', 'Dermatology'),
('Dupilumab', 'medication', 'doo-PIL-yoo-mab', ARRAY['dupilumumab', 'dupelumab']::text[], 'Skin', 'Dermatology'),
('Ixekizumab', 'medication', 'ix-e-KIZ-oo-mab', ARRAY['ixekizumumab', 'ixekisumab']::text[], 'Skin', 'Dermatology'),
('Guselkumab', 'medication', 'goo-sel-KOO-mab', ARRAY['guselkumumab', 'guzelkumab']::text[], 'Skin', 'Dermatology'),
('Stratum corneum', 'anatomy', 'STRAT-um KOR-nee-um', ARRAY['stratum corneam', 'straturm corneum']::text[], 'Skin', 'Dermatology'),
('Stratum basale', 'anatomy', 'STRAT-um ba-SAY-lee', ARRAY['stratum basile', 'stratum bassale']::text[], 'Skin', 'Dermatology'),
('Melanocytes', 'anatomy', 'MEL-a-no-sites', ARRAY['melanacytes', 'melinocytes']::text[], 'Skin', 'Dermatology'),
('Keratinocytes', 'anatomy', 'ke-RAT-in-o-sites', ARRAY['keratanocytes', 'keritinocytes']::text[], 'Skin', 'Dermatology'),
('Hair follicle', 'anatomy', 'FOL-i-kul', ARRAY['hair follical', 'hair follicel']::text[], 'Skin', 'Dermatology'),
('Eccrine glands', 'anatomy', 'EK-rin', ARRAY['eccrin glands', 'ekrine glands']::text[], 'Skin', 'Dermatology'),
('Apocrine glands', 'anatomy', 'AP-o-krin', ARRAY['apocrin glands', 'appocrine glands']::text[], 'Skin', 'Dermatology'),
('Nail matrix', 'anatomy', 'nail MAY-trix', ARRAY['nail matrics', 'nail matrics']::text[], 'Skin', 'Dermatology'),
('Nail bed', 'anatomy', 'nail bed', ARRAY['nailbed', 'nail beed']::text[], 'Skin', 'Dermatology'),
('Dermal papillae', 'anatomy', 'DER-mal pa-PIL-ay', ARRAY['dermal papilae', 'dermal papillay']::text[], 'Skin', 'Dermatology'),
('Langerhans cells', 'anatomy', 'LANG-er-hanz', ARRAY['langerhan cells', 'langerhands cells']::text[], 'Skin', 'Dermatology'),
('Rete ridges', 'anatomy', 'REE-tee ridges', ARRAY['reet ridges', 'rete ridgies']::text[], 'Skin', 'Dermatology'),
('Basement membrane', 'anatomy', 'BAYS-ment membrain', ARRAY['basemant membrane', 'basement membrain']::text[], 'Skin', 'Dermatology'),
('Pilosebaceous unit', 'anatomy', 'py-lo-se-BAY-shus', ARRAY['pilosebacious unit', 'pillosebaceous unit']::text[], 'Skin', 'Dermatology'),
('Cuticle', 'anatomy', 'KYOO-ti-kul', ARRAY['cutical', 'cuticel']::text[], 'Skin', 'Dermatology'),
('Liraglutide', 'medication', 'lir-a-GLOO-tide', ARRAY['liraglutid', 'liraglutyde']::text[], 'Endocrine', 'Endocrinology'),
('Semaglutide', 'medication', 'sem-a-GLOO-tide', ARRAY['semaglutid', 'semaglutyde']::text[], 'Endocrine', 'Endocrinology'),
('Exenatide', 'medication', 'ex-EN-a-tide', ARRAY['exenatid', 'exenetide']::text[], 'Endocrine', 'Endocrinology'),
('Insulin glargine', 'medication', 'IN-syoo-lin GLAR-jeen', ARRAY['insulin glargin', 'insulin glargene']::text[], 'Endocrine', 'Endocrinology'),
('Insulin aspart', 'medication', 'IN-syoo-lin AS-part', ARRAY['insulin aspert', 'insuline aspart']::text[], 'Endocrine', 'Endocrinology'),
('Insulin degludec', 'medication', 'IN-syoo-lin de-GLOO-dek', ARRAY['insulin deglodec', 'insuline degludec']::text[], 'Endocrine', 'Endocrinology'),
('Vildagliptin', 'medication', 'vil-da-GLIP-tin', ARRAY['vildagliptan', 'vildaglyptin']::text[], 'Endocrine', 'Endocrinology'),
('Testosterone', 'medication', 'tes-TOS-te-rone', ARRAY['testosterome', 'testosterine']::text[], 'Endocrine', 'Endocrinology'),
('Somatropin', 'medication', 'so-ma-TRO-pin', ARRAY['somatrophin', 'somatropen']::text[], 'Endocrine', 'Endocrinology'),
('Octreotide', 'medication', 'ok-TREE-o-tide', ARRAY['octreotid', 'octriotide']::text[], 'Endocrine', 'Endocrinology'),
('Cabergoline', 'medication', 'ka-BER-go-leen', ARRAY['cabergolin', 'carbegoline']::text[], 'Endocrine', 'Endocrinology'),
('Bromocriptine', 'medication', 'bro-mo-KRIP-teen', ARRAY['bromocriptin', 'bromocryptine']::text[], 'Endocrine', 'Endocrinology'),
('Propylthiouracil', 'medication', 'pro-pil-thy-o-YOOR-a-sil', ARRAY['propylthiouracyl', 'propylthiuracil']::text[], 'Endocrine', 'Endocrinology'),
('Teriparatide', 'medication', 'ter-i-PAR-a-tide', ARRAY['teriparatid', 'teriperatide']::text[], 'Endocrine', 'Endocrinology'),
('Ergocalciferol', 'medication', 'er-go-kal-SIF-e-rol', ARRAY['ergocalciferal', 'ergocalcifirol']::text[], 'Endocrine', 'Endocrinology'),
('Thyroid gland', 'anatomy', 'THY-royd', ARRAY['thyriod gland', 'thyroyd gland']::text[], 'Endocrine', 'Endocrinology'),
('Parathyroid glands', 'anatomy', 'pa-ra-THY-royd', ARRAY['parathyriod glands', 'parathyroyd glands']::text[], 'Endocrine', 'Endocrinology'),
('Adrenal glands', 'anatomy', 'a-DREE-nal', ARRAY['adrenel glands', 'adreanal glands']::text[], 'Endocrine', 'Endocrinology'),
('Adrenal cortex', 'anatomy', 'a-DREE-nal KOR-tex', ARRAY['adrenel cortex', 'adreanal cortex']::text[], 'Endocrine', 'Endocrinology'),
('Adrenal medulla', 'anatomy', 'a-DREE-nal me-DUL-a', ARRAY['adrenel medulla', 'adrenal medula']::text[], 'Endocrine', 'Endocrinology'),
('Islets of Langerhans', 'anatomy', 'EYE-lets of LANG-er-hanz', ARRAY['islets of langerhan', 'islets of langerhands']::text[], 'Endocrine', 'Endocrinology'),
('Pineal gland', 'anatomy', 'PIN-ee-al', ARRAY['pinneal gland', 'pineel gland']::text[], 'Endocrine', 'Endocrinology'),
('Thymus gland', 'anatomy', 'THY-mus', ARRAY['thymis gland', 'thimus gland']::text[], 'Endocrine', 'Endocrinology'),
('Pancreatic beta cells', 'anatomy', 'pan-kree-AT-ik BAY-ta', ARRAY['pancreatic beeta cells', 'pancreatic beta sells']::text[], 'Endocrine', 'Endocrinology'),
('Thyroid isthmus', 'anatomy', 'THY-royd IS-mus', ARRAY['thyriod isthmus', 'thyroid isthmuss']::text[], 'Endocrine', 'Endocrinology'),
('Thyroid follicles', 'anatomy', 'THY-royd FOL-i-kuls', ARRAY['thyriod follicles', 'thyroid follicals']::text[], 'Endocrine', 'Endocrinology'),
('Zona glomerulosa', 'anatomy', 'ZO-na glo-mer-yoo-LO-sa', ARRAY['zona glomerulossa', 'zona glomeruloza']::text[], 'Endocrine', 'Endocrinology'),
('Zona fasciculata', 'anatomy', 'ZO-na fa-sik-yoo-LAH-ta', ARRAY['zona fasciculatta', 'zona fascikulata']::text[], 'Endocrine', 'Endocrinology'),
('Zona reticularis', 'anatomy', 'ZO-na re-tik-yoo-LAIR-is', ARRAY['zona reticularus', 'zona reticulariss']::text[], 'Endocrine', 'Endocrinology'),
('Neurohypophysis', 'anatomy', 'nyoo-ro-hy-POF-i-sis', ARRAY['neurohypofysis', 'neuro hypophysis']::text[], 'Endocrine', 'Endocrinology'),
('Betahistine', 'medication', 'bay-ta-HIS-teen', ARRAY['betahistin', 'betahystine']::text[], 'Ears, nose & throat', 'ENT'),
('Xylometazoline', 'medication', 'zy-lo-met-AZ-o-leen', ARRAY['xylometazolin', 'xylometazaline']::text[], 'Ears, nose & throat', 'ENT'),
('Oxymetazoline', 'medication', 'ox-ee-met-AZ-o-leen', ARRAY['oxymetazolin', 'oxymetazaline']::text[], 'Ears, nose & throat', 'ENT'),
('Azelastine', 'medication', 'a-ZEL-a-steen', ARRAY['azelastin', 'azalestine']::text[], 'Ears, nose & throat', 'ENT'),
('Olopatadine', 'medication', 'o-lo-PAT-a-deen', ARRAY['olopatadin', 'olopetadine']::text[], 'Ears, nose & throat', 'ENT'),
('Sodium cromoglicate', 'medication', 'KRO-mo-gly-kate', ARRAY['sodium cromoglycate', 'sodium chromoglicate']::text[], 'Ears, nose & throat', 'ENT'),
('Prochlorperazine', 'medication', 'pro-klor-PER-a-zeen', ARRAY['prochlorperazin', 'prochloperazine']::text[], 'Ears, nose & throat', 'ENT'),
('Cinnarizine', 'medication', 'si-NAR-i-zeen', ARRAY['cinnarizin', 'cinarizine']::text[], 'Ears, nose & throat', 'ENT'),
('Chloramphenicol', 'medication', 'klor-am-FEN-i-kol', ARRAY['chloramphenical', 'chlorampenicol']::text[], 'Ears, nose & throat', 'ENT'),
('Framycetin', 'medication', 'fra-my-SEE-tin', ARRAY['framycetine', 'framicetin']::text[], 'Ears, nose & throat', 'ENT'),
('Tragus', 'anatomy', 'TRAY-gus', ARRAY['traygus', 'tragis']::text[], 'Ears, nose & throat', 'ENT'),
('Auricle', 'anatomy', 'AW-ri-kul', ARRAY['auracle', 'oricle']::text[], 'Ears, nose & throat', 'ENT'),
('Concha', 'anatomy', 'KONG-ka', ARRAY['conka', 'concka']::text[], 'Ears, nose & throat', 'ENT'),
('Antihelix', 'anatomy', 'an-ti-HEE-lix', ARRAY['anti helix', 'antihelics']::text[], 'Ears, nose & throat', 'ENT'),
('Antitragus', 'anatomy', 'an-ti-TRAY-gus', ARRAY['anti tragus', 'antitraygus']::text[], 'Ears, nose & throat', 'ENT'),
('Tympanic cavity', 'anatomy', 'tim-PAN-ik', ARRAY['timpanic cavity', 'tympanik cavity']::text[], 'Ears, nose & throat', 'ENT'),
('Malleus', 'anatomy', 'MAL-ee-us', ARRAY['malius', 'maleus']::text[], 'Ears, nose & throat', 'ENT'),
('Incus', 'anatomy', 'ING-kus', ARRAY['inkus', 'incuss']::text[], 'Ears, nose & throat', 'ENT'),
('Stapes', 'anatomy', 'STAY-peez', ARRAY['stapees', 'staypes']::text[], 'Ears, nose & throat', 'ENT'),
('Round window', 'anatomy', 'round window', ARRAY['round windo', 'round windwo']::text[], 'Ears, nose & throat', 'ENT'),
('Oval window', 'anatomy', 'oh-val window', ARRAY['ovel window', 'oval windwo']::text[], 'Ears, nose & throat', 'ENT'),
('Soft palate', 'anatomy', 'soft PAL-it', ARRAY['soft pallate', 'soft pallet']::text[], 'Ears, nose & throat', 'ENT'),
('Hard palate', 'anatomy', 'hard PAL-it', ARRAY['hard pallate', 'hard pallet']::text[], 'Ears, nose & throat', 'ENT'),
('Uvula', 'anatomy', 'YOO-vyoo-la', ARRAY['uvular', 'uvela']::text[], 'Ears, nose & throat', 'ENT'),
('Epiglottis', 'anatomy', 'ep-i-GLOT-is', ARRAY['epiglotis', 'epiglottiss']::text[], 'Ears, nose & throat', 'ENT'),
('Vocal cords', 'anatomy', 'VO-kal kords', ARRAY['vocal chords', 'vokal cords']::text[], 'Ears, nose & throat', 'ENT'),
('Parotid gland', 'anatomy', 'pa-ROT-id', ARRAY['parotyd gland', 'parottid gland']::text[], 'Ears, nose & throat', 'ENT'),
('Submandibular gland', 'anatomy', 'sub-man-DIB-yoo-lar', ARRAY['sub mandibular gland', 'submandibula gland']::text[], 'Ears, nose & throat', 'ENT'),
('Sublingual gland', 'anatomy', 'sub-LING-gwal', ARRAY['sub lingual gland', 'sublingal gland']::text[], 'Ears, nose & throat', 'ENT'),
('Thyroid cartilage', 'anatomy', 'THY-royd KAR-ti-lij', ARRAY['thyriod cartilage', 'thyroid cartalage']::text[], 'Ears, nose & throat', 'ENT'),
('Follicle-stimulating hormone', 'medication', 'FOL-i-kul STIM-yoo-lay-ting', ARRAY['follicle stimulating hormone', 'follical stimulating hormone']::text[], 'Reproductive', 'Fertility'),
('Human chorionic gonadotropin', 'medication', 'ko-ree-ON-ik go-nad-o-TRO-pin', ARRAY['human chorionic gonadotrophin', 'human chorionic gonadatropin']::text[], 'Reproductive', 'Fertility'),
('Menotropin', 'medication', 'men-o-TRO-pin', ARRAY['menotrophin', 'menotropen']::text[], 'Reproductive', 'Fertility'),
('Progesterone', 'medication', 'pro-JES-te-rone', ARRAY['progestrone', 'progesterone tablets']::text[], 'Reproductive', 'Fertility'),
('Estradiol valerate', 'medication', 'es-tra-DY-ol VAL-e-rate', ARRAY['oestradiol valerate', 'estradiol valerat']::text[], 'Reproductive', 'Fertility'),
('Dydrogesterone', 'medication', 'dy-dro-JES-te-rone', ARRAY['dydrogestrone', 'dydrogesterome']::text[], 'Reproductive', 'Fertility'),
('Buserelin', 'medication', 'BYOO-se-re-lin', ARRAY['buzerelin', 'buserelen']::text[], 'Reproductive', 'Fertility'),
('Ganirelix', 'medication', 'ga-NIR-e-lix', ARRAY['ganirelex', 'gannirelix']::text[], 'Reproductive', 'Fertility'),
('Cetrorelix', 'medication', 'set-ro-REL-ix', ARRAY['cetrorelex', 'cetroralix']::text[], 'Reproductive', 'Fertility'),
('Danazol', 'medication', 'DAN-a-zol', ARRAY['danazole', 'danozol']::text[], 'Reproductive', 'Fertility'),
('Ulipristal acetate', 'medication', 'yoo-li-PRIS-tal', ARRAY['ulipristal acitate', 'ulipristol acetate']::text[], 'Reproductive', 'Fertility'),
('Dienogest', 'medication', 'dy-EN-o-jest', ARRAY['dienogist', 'dyenogest']::text[], 'Reproductive', 'Fertility'),
('Medroxyprogesterone', 'medication', 'me-drox-ee-pro-JES-te-rone', ARRAY['medroxyprogestrone', 'medroxprogesterone']::text[], 'Reproductive', 'Fertility'),
('Luteinizing hormone', 'medication', 'LOO-tee-in-eye-zing', ARRAY['luteinising hormone', 'luteinizing hormon']::text[], 'Reproductive', 'Fertility'),
('Triptorelin', 'medication', 'trip-to-REL-in', ARRAY['triptorelen', 'tryptorelin']::text[], 'Reproductive', 'Fertility'),
('Zona pellucida', 'anatomy', 'ZO-na pe-LOO-si-da', ARRAY['zona pellucidah', 'zona pelucida']::text[], 'Reproductive', 'Fertility'),
('Corpus luteum', 'anatomy', 'KOR-pus LOO-tee-um', ARRAY['corpus luteam', 'corpus luteium']::text[], 'Reproductive', 'Fertility'),
('Graafian follicle', 'anatomy', 'GRAF-ee-an FOL-i-kul', ARRAY['graafian follical', 'grafian follicle']::text[], 'Reproductive', 'Fertility'),
('Blastocyst', 'anatomy', 'BLAS-to-sist', ARRAY['blastocist', 'blastasyst']::text[], 'Reproductive', 'Fertility'),
('Ovarian follicles', 'anatomy', 'o-VAIR-ee-an FOL-i-kuls', ARRAY['ovarien follicles', 'ovarian follicals']::text[], 'Reproductive', 'Fertility'),
('Fimbriae', 'anatomy', 'FIM-bree-ay', ARRAY['fimbrae', 'fimbriay']::text[], 'Reproductive', 'Fertility'),
('Infundibulum', 'anatomy', 'in-fun-DIB-yoo-lum', ARRAY['infundibullum', 'infundibulam']::text[], 'Reproductive', 'Fertility'),
('Cervical mucus', 'anatomy', 'SER-vi-kal MYOO-kus', ARRAY['cervical mucous', 'servical mucus']::text[], 'Reproductive', 'Fertility'),
('Seminiferous tubules', 'anatomy', 'sem-i-NIF-e-rus TOOB-yools', ARRAY['seminifurous tubules', 'seminiferous tubuls']::text[], 'Reproductive', 'Fertility'),
('Sertoli cells', 'anatomy', 'ser-TOH-lee', ARRAY['sertolli cells', 'sertoly cells']::text[], 'Reproductive', 'Fertility'),
('Leydig cells', 'anatomy', 'LY-dig', ARRAY['leidig cells', 'laydig cells']::text[], 'Reproductive', 'Fertility'),
('Acrosome', 'anatomy', 'AK-ro-some', ARRAY['acrasome', 'akrosome']::text[], 'Reproductive', 'Fertility'),
('Zygote', 'anatomy', 'ZY-gote', ARRAY['zigote', 'zygoat']::text[], 'Reproductive', 'Fertility'),
('Trophoblast', 'anatomy', 'TRO-fo-blast', ARRAY['trophablast', 'trofoblast']::text[], 'Reproductive', 'Fertility'),
('Chorionic villi', 'anatomy', 'ko-ree-ON-ik VIL-eye', ARRAY['chorionic villy', 'chorionic villae']::text[], 'Reproductive', 'Fertility'),
('Vedolizumab', 'medication', 've-do-LIZ-oo-mab', ARRAY['vedolizumumab', 'vedolizamab']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Golimumab', 'medication', 'go-LIM-yoo-mab', ARRAY['golimumumab', 'golimumumb']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Rifaximin', 'medication', 'ri-FAX-i-min', ARRAY['rifaximen', 'riffaximin']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Prucalopride', 'medication', 'proo-KAL-o-pride', ARRAY['prucaloprid', 'prucalapride']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Linaclotide', 'medication', 'lin-AK-lo-tide', ARRAY['linaclotid', 'linnaclotide']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Mebeverine', 'medication', 'me-BEV-e-reen', ARRAY['mebeverin', 'mebeverene']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Hyoscine butylbromide', 'medication', 'HY-o-seen byoo-til-BRO-mide', ARRAY['hyoscine butylbromid', 'hyocine butylbromide']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Simeticone', 'medication', 'sy-MET-i-kone', ARRAY['simethicone', 'simeticon']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Sucralfate', 'medication', 'soo-KRAL-fate', ARRAY['sucralfat', 'sucrolfate']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Ursodeoxycholic acid', 'medication', 'er-so-dee-ox-ee-KOL-ik', ARRAY['ursodeoxycolic acid', 'ursodeoxycholic assid']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Pancreatin', 'medication', 'PAN-kree-a-tin', ARRAY['pancreatine', 'pancriatin']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Colestyramine', 'medication', 'ko-les-TY-ra-meen', ARRAY['cholestyramine', 'colestyramin']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Tofacitinib', 'medication', 'to-fa-SY-ti-nib', ARRAY['tofacitinid', 'tofacitinyb']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Filgotinib', 'medication', 'fil-GO-ti-nib', ARRAY['filgotinid', 'filgotinyb']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Alverine citrate', 'medication', 'AL-ver-een SIT-rate', ARRAY['alverine citrat', 'alvarine citrate']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Ampulla of Vater', 'anatomy', 'am-PUL-a of FAH-ter', ARRAY['ampula of vater', 'ampulla of vata']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Sphincter of Oddi', 'anatomy', 'SFINK-ter of OD-ee', ARRAY['sphincter of odi', 'sfincter of oddi']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Common bile duct', 'anatomy', 'common bile dukt', ARRAY['common bile duckt', 'comon bile duct']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Cystic duct', 'anatomy', 'SIS-tik dukt', ARRAY['sistic duct', 'cystic duckt']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Hepatic duct', 'anatomy', 'he-PAT-ik dukt', ARRAY['hepattic duct', 'hepatic duckt']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Portal vein', 'anatomy', 'POR-tal vayn', ARRAY['portel vein', 'portal vane']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Pylorus', 'anatomy', 'py-LOR-us', ARRAY['pilorus', 'pyloris']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Fundus of stomach', 'anatomy', 'FUN-dus', ARRAY['fundis of stomach', 'fundus of stomache']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Cardia of stomach', 'anatomy', 'KAR-dee-a', ARRAY['cardiah of stomach', 'cardia of stomache']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Rectosigmoid junction', 'anatomy', 'rek-to-SIG-moyd', ARRAY['recto sigmoid junction', 'rectosigmiod junction']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Anal sphincter', 'anatomy', 'AY-nal SFINK-ter', ARRAY['anal sphinkter', 'anel sphincter']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Haustra', 'anatomy', 'HAW-stra', ARRAY['hawstra', 'haustrah']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Taenia coli', 'anatomy', 'TEE-nee-a KO-ly', ARRAY['tenia coli', 'taenia colli']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Intestinal villi', 'anatomy', 'in-TES-tin-al VIL-eye', ARRAY['intestinal villy', 'intestinal villae']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Microvilli', 'anatomy', 'my-kro-VIL-eye', ARRAY['micro villi', 'microvilly']::text[], 'Gastrointestinal', 'Gastroenterology'),
('Paracetamol', 'medication', 'par-a-SEE-ta-mol', ARRAY['paracetemol', 'parcetamol']::text[], 'General / systemic', 'General medicine'),
('Ibuprofen', 'medication', 'eye-byoo-PRO-fen', ARRAY['ibuprofin', 'ibrupofen']::text[], 'General / systemic', 'General medicine'),
('Aspirin', 'medication', 'AS-prin', ARRAY['asprin', 'aspirine']::text[], 'General / systemic', 'General medicine'),
('Clindamycin', 'medication', 'klin-da-MY-sin', ARRAY['clindamicin', 'clyndamycin']::text[], 'General / systemic', 'General medicine'),
('Cefalexin', 'medication', 'sef-a-LEX-in', ARRAY['cephalexin', 'cefalexen']::text[], 'General / systemic', 'General medicine'),
('Cefuroxime', 'medication', 'sef-yoor-OX-eem', ARRAY['cefuroxim', 'cephuroxime']::text[], 'General / systemic', 'General medicine'),
('Ceftriaxone', 'medication', 'sef-try-AX-own', ARRAY['ceftriaxon', 'ceftriaxen']::text[], 'General / systemic', 'General medicine'),
('Chlorhexidine', 'medication', 'klor-HEX-i-deen', ARRAY['chlorhexadine', 'chlorohexidine']::text[], 'General / systemic', 'General medicine'),
('Povidone-iodine', 'medication', 'PO-vi-done EYE-o-dine', ARRAY['povidone iodine', 'providone iodine']::text[], 'General / systemic', 'General medicine'),
('Naloxone', 'medication', 'na-LOX-own', ARRAY['naloxon', 'naloxome']::text[], 'General / systemic', 'General medicine'),
('Adrenaline', 'medication', 'a-DREN-a-lin', ARRAY['adrenalin', 'epinephrine']::text[], 'General / systemic', 'General medicine'),
('Atropine', 'medication', 'AT-ro-peen', ARRAY['atropin', 'atrapine']::text[], 'General / systemic', 'General medicine'),
('Flumazenil', 'medication', 'floo-MAZ-e-nil', ARRAY['flumazenal', 'flumazanil']::text[], 'General / systemic', 'General medicine'),
('Activated charcoal', 'medication', 'AK-ti-vay-ted CHAR-kole', ARRAY['activated charcol', 'activated carcoal']::text[], 'General / systemic', 'General medicine'),
('Glucagon', 'medication', 'GLOO-ka-gon', ARRAY['glucagen', 'glukagon']::text[], 'General / systemic', 'General medicine'),
('Lymph nodes', 'anatomy', 'limf nodes', ARRAY['lymf nodes', 'lymph knodes']::text[], 'Blood & immune', 'General medicine'),
('Lymphatic system', 'anatomy', 'lim-FAT-ik', ARRAY['lymfatic system', 'lymphatik system']::text[], 'Blood & immune', 'General medicine'),
('Reticuloendothelial system', 'anatomy', 're-tik-yoo-lo-en-do-THEE-lee-al', ARRAY['reticulo endothelial system', 'reticuloendothelal system']::text[], 'Blood & immune', 'General medicine'),
('Bone marrow', 'anatomy', 'bone MA-ro', ARRAY['bone marow', 'bone marrow cavity']::text[], 'Blood & immune', 'General medicine'),
('Fascia', 'anatomy', 'FASH-a', ARRAY['facia', 'fasha']::text[], 'Musculoskeletal', 'General medicine'),
('Mucous membrane', 'anatomy', 'MYOO-kus membrain', ARRAY['mucus membrane', 'mucous membrain']::text[], 'General / systemic', 'General medicine'),
('Serous membrane', 'anatomy', 'SEER-us membrain', ARRAY['serious membrane', 'serous membrain']::text[], 'General / systemic', 'General medicine'),
('Epithelium', 'anatomy', 'ep-i-THEE-lee-um', ARRAY['epithelum', 'epitheleum']::text[], 'General / systemic', 'General medicine'),
('Connective tissue', 'anatomy', 'ko-NEK-tiv TISH-yoo', ARRAY['connective tisue', 'conective tissue']::text[], 'General / systemic', 'General medicine'),
('Cartilage', 'anatomy', 'KAR-ti-lij', ARRAY['cartilege', 'cartalage']::text[], 'Musculoskeletal', 'General medicine'),
('Ligaments', 'anatomy', 'LIG-a-ments', ARRAY['liggaments', 'ligements']::text[], 'Musculoskeletal', 'General medicine'),
('Tendons', 'anatomy', 'TEN-donz', ARRAY['tendens', 'tendans']::text[], 'Musculoskeletal', 'General medicine'),
('Ganglia', 'anatomy', 'GANG-lee-a', ARRAY['ganglea', 'ganglya']::text[], 'Nervous system', 'General medicine'),
('Plexus', 'anatomy', 'PLEX-us', ARRAY['plexis', 'plexuss']::text[], 'Nervous system', 'General medicine'),
('Interstitium', 'anatomy', 'in-ter-STISH-ee-um', ARRAY['interstitum', 'interstiteum']::text[], 'General / systemic', 'General medicine'),
('Suxamethonium', 'medication', 'sux-a-me-THO-nee-um', ARRAY['suxamethonum', 'suxamethoneum']::text[], 'General / systemic', 'General surgery'),
('Rocuronium', 'medication', 'ro-kyoo-RO-nee-um', ARRAY['rocuronum', 'rocuroneum']::text[], 'General / systemic', 'General surgery'),
('Atracurium', 'medication', 'a-tra-KYOOR-ee-um', ARRAY['atracurum', 'atracureum']::text[], 'General / systemic', 'General surgery'),
('Sevoflurane', 'medication', 'see-vo-FLOOR-ain', ARRAY['sevofluran', 'sevofluraine']::text[], 'General / systemic', 'General surgery'),
('Isoflurane', 'medication', 'eye-so-FLOOR-ain', ARRAY['isofluran', 'isofluraine']::text[], 'General / systemic', 'General surgery'),
('Desflurane', 'medication', 'des-FLOOR-ain', ARRAY['desfluran', 'desfluraine']::text[], 'General / systemic', 'General surgery'),
('Bupivacaine', 'medication', 'byoo-PIV-a-kane', ARRAY['bupivicaine', 'bupivacane']::text[], 'General / systemic', 'General surgery'),
('Ropivacaine', 'medication', 'ro-PIV-a-kane', ARRAY['ropivicaine', 'ropivacane']::text[], 'General / systemic', 'General surgery'),
('Tranexamic acid', 'medication', 'tran-EX-am-ik', ARRAY['tranexamik acid', 'tranexemic acid']::text[], 'Blood & immune', 'General surgery'),
('Enoxaparin', 'medication', 'e-nox-a-PA-rin', ARRAY['enoxaparen', 'enoxapirin']::text[], 'Blood & immune', 'General surgery'),
('Dalteparin', 'medication', 'dal-TEP-a-rin', ARRAY['dalteparen', 'daltapirin']::text[], 'Blood & immune', 'General surgery'),
('Fondaparinux', 'medication', 'fon-da-PA-ri-nux', ARRAY['fondaparinix', 'fondaperinux']::text[], 'Blood & immune', 'General surgery'),
('Protamine sulfate', 'medication', 'PRO-ta-meen SUL-fate', ARRAY['protamine sulphate', 'protamin sulfate']::text[], 'Blood & immune', 'General surgery'),
('Neostigmine', 'medication', 'nee-o-STIG-meen', ARRAY['neostygmine', 'neostigmin']::text[], 'General / systemic', 'General surgery'),
('Sugammadex', 'medication', 'soo-GAM-a-dex', ARRAY['sugammadecs', 'sugamadex']::text[], 'General / systemic', 'General surgery'),
('Linea alba', 'anatomy', 'LIN-ee-a AL-ba', ARRAY['linea albah', 'linia alba']::text[], 'Musculoskeletal', 'General surgery'),
('Rectus abdominis', 'anatomy', 'REK-tus ab-DOM-i-nis', ARRAY['rectus abdominus', 'rectus abdomanis']::text[], 'Musculoskeletal', 'General surgery'),
('External oblique muscle', 'anatomy', 'ob-LEEK', ARRAY['external obleeq muscle', 'external oblique mussle']::text[], 'Musculoskeletal', 'General surgery'),
('Internal oblique muscle', 'anatomy', 'ob-LEEK', ARRAY['internal obleeq muscle', 'internal oblique mussle']::text[], 'Musculoskeletal', 'General surgery'),
('Transversus abdominis', 'anatomy', 'trans-VER-sus ab-DOM-i-nis', ARRAY['transversus abdominus', 'transverses abdominis']::text[], 'Musculoskeletal', 'General surgery'),
('Inguinal canal', 'anatomy', 'ING-gwin-al', ARRAY['inguinel canal', 'inguenal canal']::text[], 'Musculoskeletal', 'General surgery'),
('Inguinal ligament', 'anatomy', 'ING-gwin-al', ARRAY['inguinel ligament', 'inguenal ligament']::text[], 'Musculoskeletal', 'General surgery'),
('Femoral canal', 'anatomy', 'FEM-or-al', ARRAY['femorel canal', 'femural canal']::text[], 'Musculoskeletal', 'General surgery'),
('Umbilicus', 'anatomy', 'um-BIL-i-kus', ARRAY['umbillicus', 'umbilicuss']::text[], 'General / systemic', 'General surgery'),
('Retroperitoneum', 'anatomy', 're-tro-pe-ri-to-NEE-um', ARRAY['retro peritoneum', 'retroperitonium']::text[], 'Gastrointestinal', 'General surgery'),
('Falciform ligament', 'anatomy', 'FAL-si-form', ARRAY['falciform ligement', 'falsiform ligament']::text[], 'Gastrointestinal', 'General surgery'),
('Omentum', 'anatomy', 'o-MEN-tum', ARRAY['omentem', 'omentam']::text[], 'Gastrointestinal', 'General surgery'),
('Hernial sac', 'anatomy', 'HER-nee-al sak', ARRAY['hernial saq', 'hernal sac']::text[], 'Musculoskeletal', 'General surgery'),
('Abdominal wall', 'anatomy', 'ab-DOM-in-al wall', ARRAY['abdomanal wall', 'abdominel wall']::text[], 'General / systemic', 'General surgery'),
('Peritoneal cavity', 'anatomy', 'pe-ri-to-NEE-al', ARRAY['peritonial cavity', 'peritoneal caverty']::text[], 'Gastrointestinal', 'General surgery'),
('Norethisterone', 'medication', 'nor-e-THIS-te-rone', ARRAY['norethisterrone', 'northisterone']::text[], 'Reproductive', 'Gynaecology'),
('Levonorgestrel', 'medication', 'lee-vo-nor-JES-trel', ARRAY['levonorgestrol', 'levonorgestral']::text[], 'Reproductive', 'Gynaecology'),
('Mifepristone', 'medication', 'mif-e-PRIS-tone', ARRAY['mifepristione', 'mifepristone tablets']::text[], 'Reproductive', 'Gynaecology'),
('Misoprostol', 'medication', 'my-so-PROS-tol', ARRAY['misoprostal', 'mysoprostol']::text[], 'Reproductive', 'Gynaecology'),
('Mefenamic acid', 'medication', 'mef-e-NAM-ik', ARRAY['mefenamic assid', 'mephenamic acid']::text[], 'Reproductive', 'Gynaecology'),
('Raloxifene', 'medication', 'ra-LOX-i-feen', ARRAY['raloxafene', 'raloxefine']::text[], 'Reproductive', 'Gynaecology'),
('Bazedoxifene', 'medication', 'baz-e-DOX-i-feen', ARRAY['bazedoxafene', 'bazedoxefine']::text[], 'Reproductive', 'Gynaecology'),
('Desogestrel', 'medication', 'des-o-JES-trel', ARRAY['desogestrol', 'desogestral']::text[], 'Reproductive', 'Gynaecology'),
('Drospirenone', 'medication', 'dros-PY-re-known', ARRAY['drospirenon', 'drospyrenone']::text[], 'Reproductive', 'Gynaecology'),
('Ethinylestradiol', 'medication', 'eth-in-il-es-tra-DY-ol', ARRAY['ethinylestradiole', 'ethinyloestradiol']::text[], 'Reproductive', 'Gynaecology'),
('Conjugated estrogens', 'medication', 'KON-joo-gay-ted ES-tro-jens', ARRAY['conjugated oestrogens', 'conjugated estrogenes']::text[], 'Reproductive', 'Gynaecology'),
('Vaginal estriol', 'medication', 'VAJ-in-al ES-tree-ol', ARRAY['vaginal oestriol', 'vaginal estrial']::text[], 'Reproductive', 'Gynaecology'),
('Progesterone pessary', 'medication', 'pro-JES-te-rone PES-a-ree', ARRAY['progesterone pessery', 'progestrone pessary']::text[], 'Reproductive', 'Gynaecology'),
('Gestrinone', 'medication', 'JES-tri-known', ARRAY['gestrinon', 'gestrenone']::text[], 'Reproductive', 'Gynaecology'),
('Tibolone', 'medication', 'TIB-o-lone', ARRAY['tibalone', 'tybolone']::text[], 'Reproductive', 'Gynaecology'),
('Uterine fundus', 'anatomy', 'YOO-te-rine FUN-dus', ARRAY['uterine fundis', 'uterin fundus']::text[], 'Reproductive', 'Gynaecology'),
('Uterine cavity', 'anatomy', 'YOO-te-rine', ARRAY['uterine caverty', 'uterin cavity']::text[], 'Reproductive', 'Gynaecology'),
('Cervical os', 'anatomy', 'SER-vi-kal os', ARRAY['cervical oss', 'servical os']::text[], 'Reproductive', 'Gynaecology'),
('Endocervical canal', 'anatomy', 'en-do-SER-vi-kal', ARRAY['endo cervical canal', 'endocervicle canal']::text[], 'Reproductive', 'Gynaecology'),
('Vaginal fornix', 'anatomy', 'FOR-nix', ARRAY['vaginal fornics', 'vaginel fornix']::text[], 'Reproductive', 'Gynaecology'),
('Vaginal rugae', 'anatomy', 'ROO-gay', ARRAY['vaginal rugay', 'vaginal ruggae']::text[], 'Reproductive', 'Gynaecology'),
('Broad ligament', 'anatomy', 'brawd LIG-a-ment', ARRAY['broad ligement', 'broad ligamant']::text[], 'Reproductive', 'Gynaecology'),
('Round ligament', 'anatomy', 'round LIG-a-ment', ARRAY['round ligement', 'round ligamant']::text[], 'Reproductive', 'Gynaecology'),
('Uterosacral ligament', 'anatomy', 'yoo-ter-o-SAY-kral', ARRAY['utero sacral ligament', 'uterosacrel ligament']::text[], 'Reproductive', 'Gynaecology'),
('Ovarian ligament', 'anatomy', 'o-VAIR-ee-an', ARRAY['ovarien ligament', 'ovarian ligemant']::text[], 'Reproductive', 'Gynaecology'),
('Pouch of Douglas', 'anatomy', 'powch of DUG-las', ARRAY['pouch of douglass', 'pouch of duglas']::text[], 'Reproductive', 'Gynaecology'),
('Hymen', 'anatomy', 'HY-men', ARRAY['himen', 'hyman']::text[], 'Reproductive', 'Gynaecology'),
('Clitoral hood', 'anatomy', 'KLIT-o-ral', ARRAY['clitorel hood', 'clitoral hoode']::text[], 'Reproductive', 'Gynaecology'),
('Mons pubis', 'anatomy', 'monz PYOO-bis', ARRAY['mons pubiss', 'mons puubis']::text[], 'Reproductive', 'Gynaecology'),
('Introitus', 'anatomy', 'in-TRO-i-tus', ARRAY['introytus', 'introitis']::text[], 'Reproductive', 'Gynaecology'),
('Riluzole', 'medication', 'RIL-yoo-zole', ARRAY['riluzol', 'rilluzole']::text[], 'Nervous system', 'Neurology'),
('Natalizumab', 'medication', 'na-ta-LIZ-oo-mab', ARRAY['natalizumumab', 'nataluzimab']::text[], 'Nervous system', 'Neurology'),
('Fingolimod', 'medication', 'fin-GOL-i-mod', ARRAY['fingolimid', 'fingollimod']::text[], 'Nervous system', 'Neurology'),
('Ocrelizumab', 'medication', 'o-kre-LIZ-oo-mab', ARRAY['ocrelizumumab', 'ocreluzimab']::text[], 'Nervous system', 'Neurology'),
('Interferon beta', 'medication', 'in-ter-FEER-on BAY-ta', ARRAY['interferon beeta', 'interferan beta']::text[], 'Nervous system', 'Neurology'),
('Glatiramer acetate', 'medication', 'gla-TIR-a-mer AS-e-tate', ARRAY['glatirimer acetate', 'glatiramer acitate']::text[], 'Nervous system', 'Neurology'),
('Donepezil', 'medication', 'do-NEP-e-zil', ARRAY['donepizil', 'donepazil']::text[], 'Nervous system', 'Neurology'),
('Rivastigmine', 'medication', 'ri-va-STIG-meen', ARRAY['rivastygmine', 'rivastigmin']::text[], 'Nervous system', 'Neurology'),
('Galantamine', 'medication', 'ga-LAN-ta-meen', ARRAY['galantimine', 'galantamin']::text[], 'Nervous system', 'Neurology'),
('Memantine', 'medication', 'me-MAN-teen', ARRAY['memantin', 'mementine']::text[], 'Nervous system', 'Neurology'),
('Sumatriptan', 'medication', 'soo-ma-TRIP-tan', ARRAY['sumatriptin', 'sumitriptan']::text[], 'Nervous system', 'Neurology'),
('Rizatriptan', 'medication', 'ry-za-TRIP-tan', ARRAY['rizatriptin', 'rizzatriptan']::text[], 'Nervous system', 'Neurology'),
('Topiramate', 'medication', 'to-PY-ra-mate', ARRAY['topiramat', 'toperamate']::text[], 'Nervous system', 'Neurology'),
('Zonisamide', 'medication', 'zo-NIS-a-mide', ARRAY['zonisamid', 'zonnisamide']::text[], 'Nervous system', 'Neurology'),
('Lacosamide', 'medication', 'la-KOS-a-mide', ARRAY['lacosamid', 'lacosemide']::text[], 'Nervous system', 'Neurology'),
('Cerebral cortex', 'anatomy', 'se-REE-bral KOR-tex', ARRAY['cerebral cortix', 'serebral cortex']::text[], 'Nervous system', 'Neurology'),
('Cerebral hemispheres', 'anatomy', 'se-REE-bral HEM-i-sfeerz', ARRAY['cerebral hemispheeres', 'serebral hemispheres']::text[], 'Nervous system', 'Neurology'),
('White matter', 'anatomy', 'white MAT-er', ARRAY['white mater', 'whyte matter']::text[], 'Nervous system', 'Neurology'),
('Grey matter', 'anatomy', 'gray MAT-er', ARRAY['gray matter', 'grey mater']::text[], 'Nervous system', 'Neurology'),
('Spinal cord', 'anatomy', 'SPY-nal kord', ARRAY['spinel cord', 'spinal chord']::text[], 'Nervous system', 'Neurology'),
('Dorsal root ganglion', 'anatomy', 'DOR-sal root GANG-lee-on', ARRAY['dorsal root ganglian', 'dorsel root ganglion']::text[], 'Nervous system', 'Neurology'),
('Cauda equina', 'anatomy', 'KAW-da e-KWY-na', ARRAY['cauda equinah', 'cauda ekwina']::text[], 'Nervous system', 'Neurology'),
('Substantia nigra', 'anatomy', 'sub-STAN-shee-a NY-gra', ARRAY['substantia nygra', 'substantia nigrah']::text[], 'Nervous system', 'Neurology'),
('Reticular formation', 'anatomy', 're-TIK-yoo-lar', ARRAY['reticula formation', 'reticular formattion']::text[], 'Nervous system', 'Neurology'),
('Optic chiasm', 'anatomy', 'OP-tik KY-azm', ARRAY['optic chiasim', 'optick chiasm']::text[], 'Nervous system', 'Neurology'),
('Cranial nerves', 'anatomy', 'KRAY-nee-al nervz', ARRAY['craniel nerves', 'cranial nervs']::text[], 'Nervous system', 'Neurology'),
('Vagus nerve', 'anatomy', 'VAY-gus nerv', ARRAY['vagas nerve', 'vagus nerv']::text[], 'Nervous system', 'Neurology'),
('Trigeminal nerve', 'anatomy', 'try-JEM-in-al', ARRAY['trigeminel nerve', 'trigemenal nerve']::text[], 'Nervous system', 'Neurology'),
('Sciatic nerve', 'anatomy', 'sy-AT-ik', ARRAY['sciatick nerve', 'siatic nerve']::text[], 'Nervous system', 'Neurology'),
('Myelin sheath', 'anatomy', 'MY-e-lin sheeth', ARRAY['mylin sheath', 'myelin sheeth']::text[], 'Nervous system', 'Neurology'),
('Ipilimumab', 'medication', 'ip-i-LIM-yoo-mab', ARRAY['ipilimumumab', 'ipilimomab']::text[], 'General / systemic', 'Oncology'),
('Atezolizumab', 'medication', 'a-tez-o-LIZ-oo-mab', ARRAY['atezolizumumab', 'atezoluzimab']::text[], 'General / systemic', 'Oncology'),
('Durvalumab', 'medication', 'der-VAL-yoo-mab', ARRAY['durvalumumab', 'durvalumumb']::text[], 'General / systemic', 'Oncology'),
('Carboplatin', 'medication', 'KAR-bo-pla-tin', ARRAY['carboplatan', 'carboplattin']::text[], 'General / systemic', 'Oncology'),
('Cisplatin', 'medication', 'SIS-pla-tin', ARRAY['cisplatan', 'cissplatin']::text[], 'General / systemic', 'Oncology'),
('Oxaliplatin', 'medication', 'ox-AL-i-pla-tin', ARRAY['oxaliplatan', 'oxalyplatin']::text[], 'General / systemic', 'Oncology'),
('Gemcitabine', 'medication', 'jem-SY-ta-been', ARRAY['gemcitabin', 'gemsitabine']::text[], 'General / systemic', 'Oncology'),
('Irinotecan', 'medication', 'i-ri-no-TEE-kan', ARRAY['irinotecen', 'irrinotecan']::text[], 'General / systemic', 'Oncology'),
('Etoposide', 'medication', 'e-TOP-o-side', ARRAY['etoposid', 'etopaside']::text[], 'General / systemic', 'Oncology'),
('Vincristine', 'medication', 'vin-KRIS-teen', ARRAY['vincristin', 'vincristene']::text[], 'General / systemic', 'Oncology'),
('Vinblastine', 'medication', 'vin-BLAS-teen', ARRAY['vinblastin', 'vinblastene']::text[], 'General / systemic', 'Oncology'),
('Doxorubicin', 'medication', 'dox-o-ROO-bi-sin', ARRAY['doxorubicine', 'doxorubisin']::text[], 'General / systemic', 'Oncology'),
('Epirubicin', 'medication', 'ep-i-ROO-bi-sin', ARRAY['epirubicine', 'epirubisin']::text[], 'General / systemic', 'Oncology'),
('Imatinib', 'medication', 'i-MAT-in-ib', ARRAY['imatinid', 'imattinib']::text[], 'General / systemic', 'Oncology'),
('Dasatinib', 'medication', 'da-SAT-in-ib', ARRAY['dasatinid', 'dassatinib']::text[], 'General / systemic', 'Oncology'),
('Axillary lymph nodes', 'anatomy', 'AX-il-a-ree', ARRAY['axilary lymph nodes', 'axillery lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Sentinel lymph node', 'anatomy', 'SEN-ti-nel', ARRAY['sentinal lymph node', 'sentinel limph node']::text[], 'Blood & immune', 'Oncology'),
('Mediastinal lymph nodes', 'anatomy', 'mee-dee-a-STY-nal', ARRAY['mediastinel lymph nodes', 'mediastenal lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Inguinal lymph nodes', 'anatomy', 'ING-gwin-al', ARRAY['inguinel lymph nodes', 'inguenal lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Cervical lymph nodes', 'anatomy', 'SER-vi-kal', ARRAY['servical lymph nodes', 'cervicle lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Supraclavicular lymph nodes', 'anatomy', 'soo-pra-kla-VIK-yoo-lar', ARRAY['supraclavicula lymph nodes', 'supra clavicular lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Retroperitoneal lymph nodes', 'anatomy', 're-tro-pe-ri-to-NEE-al', ARRAY['retro peritoneal lymph nodes', 'retroperitonial lymph nodes']::text[], 'Blood & immune', 'Oncology'),
('Splenic hilum', 'anatomy', 'SPLEN-ik HY-lum', ARRAY['splenic hylum', 'splenick hilum']::text[], 'Blood & immune', 'Oncology'),
('Hepatic segments', 'anatomy', 'he-PAT-ik', ARRAY['hepattic segments', 'hepatic segmants']::text[], 'Gastrointestinal', 'Oncology'),
('Pleural cavity', 'anatomy', 'PLOOR-al', ARRAY['plural cavity', 'pleural caverty']::text[], 'Respiratory', 'Oncology'),
('Thoracic cavity', 'anatomy', 'tho-RAS-ik', ARRAY['thorasic cavity', 'thoracic caverty']::text[], 'Respiratory', 'Oncology'),
('Perivascular space', 'anatomy', 'pe-ri-VAS-kyoo-lar', ARRAY['peri vascular space', 'perivascula space']::text[], 'General / systemic', 'Oncology'),
('Perineural space', 'anatomy', 'pe-ri-NYOOR-al', ARRAY['peri neural space', 'perineurel space']::text[], 'Nervous system', 'Oncology'),
('Subcapsular region', 'anatomy', 'sub-KAP-syoo-lar', ARRAY['sub capsular region', 'subcapsula region']::text[], 'General / systemic', 'Oncology'),
('Serosal surface', 'anatomy', 'se-RO-sal', ARRAY['serosel surface', 'serosal surfice']::text[], 'General / systemic', 'Oncology'),
('Latanoprost', 'medication', 'la-TAN-o-prost', ARRAY['latanoprast', 'latanaprost']::text[], 'Eyes', 'Ophthalmology'),
('Timolol', 'medication', 'TY-mo-lol', ARRAY['timalol', 'tymolol']::text[], 'Eyes', 'Ophthalmology'),
('Brimonidine', 'medication', 'bry-MON-i-deen', ARRAY['brimonidin', 'brymonidine']::text[], 'Eyes', 'Ophthalmology'),
('Dorzolamide', 'medication', 'dor-ZOL-a-mide', ARRAY['dorzolamid', 'dorzalamide']::text[], 'Eyes', 'Ophthalmology'),
('Bimatoprost', 'medication', 'by-MAT-o-prost', ARRAY['bimatoprast', 'bimataprost']::text[], 'Eyes', 'Ophthalmology'),
('Travoprost', 'medication', 'TRAV-o-prost', ARRAY['travoprast', 'travaprost']::text[], 'Eyes', 'Ophthalmology'),
('Pilocarpine', 'medication', 'py-lo-KAR-peen', ARRAY['pilocarpin', 'pylocarpine']::text[], 'Eyes', 'Ophthalmology'),
('Cyclopentolate', 'medication', 'sy-klo-PEN-to-late', ARRAY['cyclopentolat', 'ciclopentolate']::text[], 'Eyes', 'Ophthalmology'),
('Tropicamide', 'medication', 'tro-PIK-a-mide', ARRAY['tropicamid', 'tropycamide']::text[], 'Eyes', 'Ophthalmology'),
('Ranibizumab', 'medication', 'ran-i-BIZ-oo-mab', ARRAY['ranibizumumab', 'ranibizamab']::text[], 'Eyes', 'Ophthalmology'),
('Aflibercept', 'medication', 'a-FLIB-er-sept', ARRAY['afliberceptt', 'aflybercept']::text[], 'Eyes', 'Ophthalmology'),
('Fluorescein', 'medication', 'floo-RES-ee-in', ARRAY['florescein', 'fluoroscein']::text[], 'Eyes', 'Ophthalmology'),
('Ofloxacin', 'medication', 'o-FLOX-a-sin', ARRAY['ofloxacine', 'ofloxicin']::text[], 'Eyes', 'Ophthalmology'),
('Ketorolac', 'medication', 'ke-TOR-o-lak', ARRAY['ketorolack', 'ketoralac']::text[], 'Eyes', 'Ophthalmology'),
('Loteprednol', 'medication', 'lo-te-PRED-nol', ARRAY['loteprednal', 'lotepradnol']::text[], 'Eyes', 'Ophthalmology'),
('Cornea', 'anatomy', 'KOR-nee-a', ARRAY['cornia', 'korneal']::text[], 'Eyes', 'Ophthalmology'),
('Iris', 'anatomy', 'EYE-ris', ARRAY['irris', 'iriss']::text[], 'Eyes', 'Ophthalmology'),
('Crystalline lens', 'anatomy', 'KRIS-ta-leen', ARRAY['cristalline lens', 'crystaline lens']::text[], 'Eyes', 'Ophthalmology'),
('Retina', 'anatomy', 'RET-in-a', ARRAY['retna', 'reitna']::text[], 'Eyes', 'Ophthalmology'),
('Optic disc', 'anatomy', 'OP-tik disk', ARRAY['optick disc', 'optic disk']::text[], 'Eyes', 'Ophthalmology'),
('Trabecular meshwork', 'anatomy', 'tra-BEK-yoo-lar', ARRAY['trabecula meshwork', 'trabekular meshwork']::text[], 'Eyes', 'Ophthalmology'),
('Canal of Schlemm', 'anatomy', 'kan-AL of shlem', ARRAY['canal of schlem', 'canal of shlemm']::text[], 'Eyes', 'Ophthalmology'),
('Bulbar conjunctiva', 'anatomy', 'BUL-bar kon-junk-TY-va', ARRAY['bulbar conjuctiva', 'bulber conjunctiva']::text[], 'Eyes', 'Ophthalmology'),
('Palpebral conjunctiva', 'anatomy', 'pal-PEE-bral kon-junk-TY-va', ARRAY['palpebral conjuctiva', 'palpibral conjunctiva']::text[], 'Eyes', 'Ophthalmology'),
('Meibomian glands', 'anatomy', 'my-BO-mee-an', ARRAY['meibomien glands', 'mybomian glands']::text[], 'Eyes', 'Ophthalmology'),
('Extraocular muscles', 'anatomy', 'ex-tra-OK-yoo-lar', ARRAY['extra ocular muscles', 'extraoccular muscles']::text[], 'Eyes', 'Ophthalmology'),
('Superior rectus muscle', 'anatomy', 'soo-PEER-ee-or REK-tus', ARRAY['superior rectis muscle', 'superior rectus mussle']::text[], 'Eyes', 'Ophthalmology'),
('Inferior oblique muscle', 'anatomy', 'ob-LEEK', ARRAY['inferior obleeq muscle', 'inferior oblique mussle']::text[], 'Eyes', 'Ophthalmology'),
('Levator palpebrae superioris', 'anatomy', 'le-VAY-tor pal-PEE-bry', ARRAY['levator palpebra superioris', 'levator palpebrae superiores']::text[], 'Eyes', 'Ophthalmology'),
('Choroid plexus', 'anatomy', 'KOR-oyd PLEX-us', ARRAY['choriod plexus', 'choroid plexis']::text[], 'Eyes', 'Ophthalmology'),
('Entonox', 'medication', 'EN-to-nox', ARRAY['entonox gas', 'entinox']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Ketamine', 'medication', 'KET-a-meen', ARRAY['ketamin', 'ketiman']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Romosozumab', 'medication', 'ro-mo-SO-zoo-mab', ARRAY['romosozumumab', 'romosuzimab']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Strontium ranelate', 'medication', 'STRON-tee-um RAN-e-late', ARRAY['strontium ranelat', 'stronium ranelate']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Diclofenac gel', 'medication', 'dy-KLOF-en-ak', ARRAY['diclofenic gel', 'diclofenac jel']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Piroxicam', 'medication', 'py-ROX-i-kam', ARRAY['piroxicom', 'pyroxicam']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Indometacin', 'medication', 'in-do-MET-a-sin', ARRAY['indomethacin', 'indometacine']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Sulindac', 'medication', 'SUL-in-dak', ARRAY['sulindack', 'sullindac']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Bursa', 'anatomy', 'BER-sa', ARRAY['bursah', 'birsa']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Synovium', 'anatomy', 'si-NO-vee-um', ARRAY['synovum', 'synoveum']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Synovial fluid', 'anatomy', 'si-NO-vee-al', ARRAY['synovial fluyd', 'synoveal fluid']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Articular cartilage', 'anatomy', 'ar-TIK-yoo-lar', ARRAY['articula cartilage', 'artikular cartilage']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Growth plate', 'anatomy', 'growth plate', ARRAY['grouth plate', 'growth plait']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Diaphysis', 'anatomy', 'dy-AF-i-sis', ARRAY['diaphisis', 'dyaphysis']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Epiphysis', 'anatomy', 'e-PIF-i-sis', ARRAY['epiphisis', 'epyphysis']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Metaphysis', 'anatomy', 'me-TAF-i-sis', ARRAY['metaphisis', 'metaphysiss']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Periosteum', 'anatomy', 'pe-ree-OS-tee-um', ARRAY['periostium', 'periosteam']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Endosteum', 'anatomy', 'en-DOS-tee-um', ARRAY['endostium', 'endosteam']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Medullary cavity', 'anatomy', 'MED-yoo-lar-ee', ARRAY['medulary cavity', 'medullary caverty']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Anterior cruciate ligament', 'anatomy', 'KROO-shee-ate', ARRAY['anterior cruciat ligament', 'anterior cruciate ligement']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Posterior cruciate ligament', 'anatomy', 'KROO-shee-ate', ARRAY['posterior cruciat ligament', 'posterior cruciate ligement']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Medial collateral ligament', 'anatomy', 'MEE-dee-al ko-LAT-er-al', ARRAY['medial collateral ligement', 'medial colateral ligament']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Lateral collateral ligament', 'anatomy', 'LAT-er-al ko-LAT-er-al', ARRAY['lateral collateral ligement', 'lateral colateral ligament']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Rotator cuff', 'anatomy', 'ro-TAY-tor kuf', ARRAY['rotater cuff', 'rotator cough']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Deltoid muscle', 'anatomy', 'DEL-toyd', ARRAY['deltoyd muscle', 'deltoid mussle']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Biceps brachii', 'anatomy', 'BY-seps BRAY-kee-eye', ARRAY['biceps brachi', 'bicepts brachii']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Triceps brachii', 'anatomy', 'TRY-seps BRAY-kee-eye', ARRAY['triceps brachi', 'tricepts brachii']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Flexor carpi radialis', 'anatomy', 'FLEX-or KAR-py ray-dee-AL-is', ARRAY['flexor carpi radialiss', 'flexer carpi radialis']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Extensor carpi ulnaris', 'anatomy', 'ex-TEN-sor KAR-py ul-NAIR-is', ARRAY['extensor carpi ulnariss', 'extensa carpi ulnaris']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Talus', 'anatomy', 'TAY-lus', ARRAY['talis', 'taluss']::text[], 'Musculoskeletal', 'Orthopaedics'),
('Chloral hydrate', 'medication', 'KLOR-al HY-drate', ARRAY['chlorel hydrate', 'chloral hydrat']::text[], 'General / systemic', 'Paediatrics'),
('Melatonin', 'medication', 'mel-a-TO-nin', ARRAY['melatonen', 'melataonin']::text[], 'Nervous system', 'Paediatrics'),
('Methylphenidate', 'medication', 'meth-il-FEN-i-date', ARRAY['methylphenidat', 'methelphenidate']::text[], 'Nervous system', 'Paediatrics'),
('Lisdexamfetamine', 'medication', 'lis-dex-am-FET-a-meen', ARRAY['lisdexamfetamin', 'lisdexanfetamine']::text[], 'Nervous system', 'Paediatrics'),
('Atomoxetine', 'medication', 'at-o-MOX-e-teen', ARRAY['atomoxetin', 'atomoxatine']::text[], 'Nervous system', 'Paediatrics'),
('Guanfacine', 'medication', 'GWAN-fa-seen', ARRAY['guanfacin', 'guanfasine']::text[], 'Nervous system', 'Paediatrics'),
('Vigabatrin', 'medication', 'vy-GAB-a-trin', ARRAY['vigabatren', 'vygabatrin']::text[], 'Nervous system', 'Paediatrics'),
('Clobazam', 'medication', 'KLO-ba-zam', ARRAY['clobazem', 'clobezam']::text[], 'Nervous system', 'Paediatrics'),
('Sulthiame', 'medication', 'sul-THY-am', ARRAY['sulthiam', 'sulthyame']::text[], 'Nervous system', 'Paediatrics'),
('Ethosuximide', 'medication', 'eth-o-SUX-i-mide', ARRAY['ethosuximid', 'ethasuximide']::text[], 'Nervous system', 'Paediatrics'),
('Pyridoxine', 'medication', 'py-ri-DOX-een', ARRAY['pyridoxin', 'pyridoxene']::text[], 'General / systemic', 'Paediatrics'),
('Biotin', 'medication', 'BY-o-tin', ARRAY['biotine', 'byotin']::text[], 'General / systemic', 'Paediatrics'),
('Dexamfetamine', 'medication', 'dex-am-FET-a-meen', ARRAY['dexamfetamin', 'dexanfetamine']::text[], 'Nervous system', 'Paediatrics'),
('Clonidine', 'medication', 'KLON-i-deen', ARRAY['clonidin', 'clonadine']::text[], 'Cardiovascular', 'Paediatrics'),
('Sodium feredetate', 'medication', 'SO-dee-um fe-RED-e-tate', ARRAY['sodium feradetate', 'sodium ferredetate']::text[], 'Blood & immune', 'Paediatrics'),
('Fontanelle', 'anatomy', 'fon-ta-NEL', ARRAY['fontanel', 'fontanele']::text[], 'Head & neck', 'Paediatrics'),
('Anterior fontanelle', 'anatomy', 'fon-ta-NEL', ARRAY['anterior fontanel', 'anteriar fontanelle']::text[], 'Head & neck', 'Paediatrics'),
('Posterior fontanelle', 'anatomy', 'fon-ta-NEL', ARRAY['posterior fontanel', 'posteriar fontanelle']::text[], 'Head & neck', 'Paediatrics'),
('Umbilical cord', 'anatomy', 'um-BIL-i-kal', ARRAY['umbillical cord', 'umbilicle cord']::text[], 'General / systemic', 'Paediatrics'),
('Umbilical stump', 'anatomy', 'um-BIL-i-kal', ARRAY['umbillical stump', 'umbilicle stump']::text[], 'General / systemic', 'Paediatrics'),
('Ductus arteriosus', 'anatomy', 'DUK-tus ar-teer-ee-O-sus', ARRAY['ductus arteriosis', 'ductus arteriousus']::text[], 'Cardiovascular', 'Paediatrics'),
('Foramen ovale', 'anatomy', 'fo-RAY-men o-VAH-lee', ARRAY['foramen ovalee', 'foraman ovale']::text[], 'Cardiovascular', 'Paediatrics'),
('Ductus venosus', 'anatomy', 'DUK-tus ve-NO-sus', ARRAY['ductus venosis', 'ductus venousus']::text[], 'Cardiovascular', 'Paediatrics'),
('Vernix caseosa', 'anatomy', 'VER-nix kay-see-O-sa', ARRAY['vernix caseossa', 'vernix casiosa']::text[], 'Skin', 'Paediatrics'),
('Meconium', 'anatomy', 'me-KO-nee-um', ARRAY['meconum', 'mekonium']::text[], 'Gastrointestinal', 'Paediatrics'),
('Deciduous teeth', 'anatomy', 'de-SID-yoo-us', ARRAY['decidious teeth', 'deciduas teeth']::text[], 'Head & neck', 'Paediatrics'),
('Cranial sutures', 'anatomy', 'KRAY-nee-al SOO-cherz', ARRAY['craniel sutures', 'cranial suchers']::text[], 'Head & neck', 'Paediatrics'),
('Sagittal suture', 'anatomy', 'SAJ-i-tal SOO-cher', ARRAY['sagital suture', 'saggital suture']::text[], 'Head & neck', 'Paediatrics'),
('Coronal suture', 'anatomy', 'ko-RO-nal SOO-cher', ARRAY['coronel suture', 'coronal suchure']::text[], 'Head & neck', 'Paediatrics'),
('Lambdoid suture', 'anatomy', 'LAM-doyd SOO-cher', ARRAY['lambdoyd suture', 'lambdoid suchure']::text[], 'Head & neck', 'Paediatrics'),
('Diamorphine', 'medication', 'dy-a-MOR-feen', ARRAY['diamorphin', 'dyamorphine']::text[], 'General / systemic', 'Pain management'),
('Morphine sulfate', 'medication', 'MOR-feen SUL-fate', ARRAY['morphine sulphate', 'morphene sulfate']::text[], 'General / systemic', 'Pain management'),
('Hydromorphone', 'medication', 'hy-dro-MOR-fone', ARRAY['hydromorphon', 'hydromorfone']::text[], 'General / systemic', 'Pain management'),
('Methadone', 'medication', 'METH-a-done', ARRAY['methadon', 'methedone']::text[], 'General / systemic', 'Pain management'),
('Fentanyl', 'medication', 'FEN-ta-nil', ARRAY['fentanil', 'fentynal']::text[], 'General / systemic', 'Pain management'),
('Tapentadol', 'medication', 'ta-PEN-ta-dol', ARRAY['tapentadal', 'tapentodol']::text[], 'General / systemic', 'Pain management'),
('Nortriptyline', 'medication', 'nor-TRIP-ti-leen', ARRAY['nortryptiline', 'nortriptaline']::text[], 'Nervous system', 'Pain management'),
('Capsaicin cream', 'medication', 'kap-SAY-i-sin', ARRAY['capsaicin creme', 'capsacin cream']::text[], 'Skin', 'Pain management'),
('Lidocaine patch', 'medication', 'LY-do-kane', ARRAY['lignocaine patch', 'lidocaine patche']::text[], 'Skin', 'Pain management'),
('Ziconotide', 'medication', 'zy-KON-o-tide', ARRAY['ziconotid', 'zyconotide']::text[], 'Nervous system', 'Pain management'),
('Clonazepam', 'medication', 'klo-NAZ-e-pam', ARRAY['clonazepan', 'clonezepam']::text[], 'Nervous system', 'Pain management'),
('Nefopam', 'medication', 'NEF-o-pam', ARRAY['nefopan', 'nephopam']::text[], 'Nervous system', 'Pain management'),
('Meptazinol', 'medication', 'mep-TAZ-i-nol', ARRAY['meptazinal', 'meptazynol']::text[], 'General / systemic', 'Pain management'),
('Oxycodone-naloxone', 'medication', 'ox-i-CO-done na-LOX-own', ARRAY['oxycodone naloxone', 'oxycodeine naloxone']::text[], 'General / systemic', 'Pain management'),
('Levomepromazine', 'medication', 'lee-vo-me-PRO-ma-zeen', ARRAY['levomepromazin', 'levomepromazene']::text[], 'Nervous system', 'Pain management'),
('Dorsal horn', 'anatomy', 'DOR-sal horn', ARRAY['dorsel horn', 'dorsal hourn']::text[], 'Nervous system', 'Pain management'),
('Nociceptors', 'anatomy', 'no-si-SEP-torz', ARRAY['nocisceptors', 'nocioceptors']::text[], 'Nervous system', 'Pain management'),
('Spinothalamic tract', 'anatomy', 'spy-no-tha-LAM-ik', ARRAY['spino thalamic tract', 'spinothalamick tract']::text[], 'Nervous system', 'Pain management'),
('Peripheral nerves', 'anatomy', 'pe-RIF-er-al nervz', ARRAY['peripheral nervs', 'periferal nerves']::text[], 'Nervous system', 'Pain management'),
('Sympathetic chain', 'anatomy', 'sim-pa-THET-ik', ARRAY['sympathetick chain', 'simpathetic chain']::text[], 'Nervous system', 'Pain management'),
('Stellate ganglion', 'anatomy', 'STEL-ate GANG-lee-on', ARRAY['stellate ganglian', 'stelate ganglion']::text[], 'Nervous system', 'Pain management'),
('Coeliac plexus', 'anatomy', 'SEE-lee-ak PLEX-us', ARRAY['celiac plexus', 'coeliac plexis']::text[], 'Nervous system', 'Pain management'),
('Epidural space', 'anatomy', 'ep-i-DYOOR-al', ARRAY['epidurel space', 'epidural spase']::text[], 'Nervous system', 'Pain management'),
('Subarachnoid space', 'anatomy', 'sub-a-RAK-noyd', ARRAY['sub arachnoid space', 'subarachnoyd space']::text[], 'Nervous system', 'Pain management'),
('Facet joints', 'anatomy', 'FAS-et joynts', ARRAY['facett joints', 'fascet joints']::text[], 'Musculoskeletal', 'Pain management'),
('Sacroiliac joint', 'anatomy', 'say-kro-IL-ee-ak', ARRAY['sacroiliack joint', 'sacro-iliac joint']::text[], 'Musculoskeletal', 'Pain management'),
('Trigeminal ganglion', 'anatomy', 'try-JEM-in-al GANG-lee-on', ARRAY['trigeminel ganglion', 'trigeminal ganglian']::text[], 'Nervous system', 'Pain management'),
('Periaqueductal grey', 'anatomy', 'pe-ri-a-kwe-DUK-tal', ARRAY['peri aqueductal grey', 'periaqueductal gray']::text[], 'Nervous system', 'Pain management'),
('Substantia gelatinosa', 'anatomy', 'sub-STAN-shee-a jel-a-tin-O-sa', ARRAY['substantia gelatinossa', 'substantia gelatinoza']::text[], 'Nervous system', 'Pain management'),
('Myofascial trigger points', 'anatomy', 'my-o-FASH-al', ARRAY['myofacial trigger points', 'myofascial triger points']::text[], 'Musculoskeletal', 'Pain management'),
('Silicone gel', 'medication', 'SIL-i-kone jel', ARRAY['silicon gel', 'silicone jell']::text[], 'Skin', 'Plastic surgery'),
('Collagenase', 'medication', 'ko-LAJ-e-nase', ARRAY['collagenaze', 'colagenase']::text[], 'Skin', 'Plastic surgery'),
('Hyaluronidase', 'medication', 'hy-a-loo-RON-i-dase', ARRAY['hyaluronidaze', 'hyalauronidase']::text[], 'Skin', 'Plastic surgery'),
('Prilocaine', 'medication', 'PRY-lo-kane', ARRAY['prilocain', 'prylocaine']::text[], 'Skin', 'Plastic surgery'),
('Mepivacaine', 'medication', 'me-PIV-a-kane', ARRAY['mepivicaine', 'mepivacane']::text[], 'Skin', 'Plastic surgery'),
('Fibrin sealant', 'medication', 'FY-brin SEE-lant', ARRAY['fibrin sealent', 'fybrin sealant']::text[], 'Blood & immune', 'Plastic surgery'),
('Heparin', 'medication', 'HEP-a-rin', ARRAY['heperin', 'hepparin']::text[], 'Blood & immune', 'Plastic surgery'),
('Aprotinin', 'medication', 'a-PRO-tin-in', ARRAY['aprotynin', 'aprotinen']::text[], 'Blood & immune', 'Plastic surgery'),
('Sodium tetradecyl sulfate', 'medication', 'tet-ra-DES-il SUL-fate', ARRAY['sodium tetradecyl sulphate', 'sodium tetradecil sulfate']::text[], 'Cardiovascular', 'Plastic surgery'),
('Polidocanol', 'medication', 'po-li-DO-ka-nol', ARRAY['polidocanal', 'polydocanol']::text[], 'Cardiovascular', 'Plastic surgery'),
('Split-thickness skin graft', 'anatomy', 'split THIK-nes', ARRAY['split thickness skin graft', 'split-thicknes skin graft']::text[], 'Skin', 'Plastic surgery'),
('Full-thickness skin graft', 'anatomy', 'ful THIK-nes', ARRAY['full thickness skin graft', 'full-thicknes skin graft']::text[], 'Skin', 'Plastic surgery'),
('Free flap', 'anatomy', 'free flap', ARRAY['free flapp', 'free flep']::text[], 'Skin', 'Plastic surgery'),
('Pedicled flap', 'anatomy', 'PED-i-kuld flap', ARRAY['pediculed flap', 'pedicaled flap']::text[], 'Skin', 'Plastic surgery'),
('Perforator vessels', 'anatomy', 'PER-fo-ray-tor', ARRAY['perforater vessels', 'perforator vesels']::text[], 'Skin', 'Plastic surgery'),
('Latissimus dorsi flap', 'anatomy', 'la-TIS-i-mus DOR-sy', ARRAY['latismus dorsi flap', 'latissimus dorsai flap']::text[], 'Musculoskeletal', 'Plastic surgery'),
('Deep inferior epigastric perforator', 'anatomy', 'ep-i-GAS-trik', ARRAY['deep inferior epigastric perforater', 'deep inferior epigastrick perforator']::text[], 'Musculoskeletal', 'Plastic surgery'),
('Donor site', 'anatomy', 'DO-nor site', ARRAY['doner site', 'donor sight']::text[], 'Skin', 'Plastic surgery'),
('Recipient site', 'anatomy', 're-SIP-ee-ent', ARRAY['recipiant site', 'recipient sight']::text[], 'Skin', 'Plastic surgery'),
('Keloid scar', 'anatomy', 'KEE-loyd', ARRAY['keloyd scar', 'keloid scarr']::text[], 'Skin', 'Plastic surgery'),
('Hypertrophic scar', 'anatomy', 'hy-per-TRO-fik', ARRAY['hypertrophick scar', 'hypertrofic scar']::text[], 'Skin', 'Plastic surgery'),
('Dermal substitute', 'anatomy', 'DER-mal SUB-sti-tyoot', ARRAY['dermal substitude', 'dermal substitue']::text[], 'Skin', 'Plastic surgery'),
('Tissue expander', 'anatomy', 'TISH-oo ex-PAN-der', ARRAY['tissue expandor', 'tisue expander']::text[], 'Skin', 'Plastic surgery'),
('Capsular contracture', 'anatomy', 'KAP-syoo-lar kon-TRAK-cher', ARRAY['capsula contracture', 'capsular contractur']::text[], 'Skin', 'Plastic surgery'),
('Fibrous capsule', 'anatomy', 'FY-brus KAP-syool', ARRAY['fibris capsule', 'fibrous capsul']::text[], 'Skin', 'Plastic surgery'),
('Areola', 'anatomy', 'a-REE-o-la', ARRAY['areolar', 'areola area']::text[], 'Skin', 'Plastic surgery'),
('Nipple-areola complex', 'anatomy', 'a-REE-o-la', ARRAY['nipple areola complex', 'nipple-areolar complex']::text[], 'Skin', 'Plastic surgery'),
('Inframammary fold', 'anatomy', 'in-fra-MAM-a-ree', ARRAY['infra mammary fold', 'inframammery fold']::text[], 'Skin', 'Plastic surgery'),
('Pectoralis major muscle', 'anatomy', 'pek-to-RAL-is', ARRAY['pectoralis mayor muscle', 'pectoralus major muscle']::text[], 'Musculoskeletal', 'Plastic surgery'),
('Serratus anterior muscle', 'anatomy', 'se-RAY-tus an-TEER-ee-or', ARRAY['seratus anterior muscle', 'serratus anteriar muscle']::text[], 'Musculoskeletal', 'Plastic surgery'),
('Lithium carbonate', 'medication', 'LITH-ee-um KAR-bo-nate', ARRAY['lithium carbonat', 'lithum carbonate']::text[], 'Mental health', 'Psychiatry'),
('Clozapine', 'medication', 'KLO-za-peen', ARRAY['clozapin', 'closapine']::text[], 'Mental health', 'Psychiatry'),
('Haloperidol', 'medication', 'ha-lo-PER-i-dol', ARRAY['haloperidal', 'halloperidol']::text[], 'Mental health', 'Psychiatry'),
('Chlorpromazine', 'medication', 'klor-PRO-ma-zeen', ARRAY['chlorpromazin', 'chlopromazine']::text[], 'Mental health', 'Psychiatry'),
('Flupentixol', 'medication', 'floo-PEN-tix-ol', ARRAY['flupenthixol', 'flupentixal']::text[], 'Mental health', 'Psychiatry'),
('Zuclopenthixol', 'medication', 'zoo-klo-PEN-thix-ol', ARRAY['zuclopenthixal', 'zuclopentixol']::text[], 'Mental health', 'Psychiatry'),
('Paliperidone', 'medication', 'pal-i-PER-i-done', ARRAY['paliperidon', 'palliperidone']::text[], 'Mental health', 'Psychiatry'),
('Lurasidone', 'medication', 'loo-RAS-i-done', ARRAY['lurasidon', 'lurazidone']::text[], 'Mental health', 'Psychiatry'),
('Vortioxetine', 'medication', 'vor-tee-OX-e-teen', ARRAY['vortioxetin', 'vortioxatine']::text[], 'Mental health', 'Psychiatry'),
('Agomelatine', 'medication', 'a-go-MEL-a-teen', ARRAY['agomelatin', 'agomelitine']::text[], 'Mental health', 'Psychiatry'),
('Reboxetine', 'medication', 're-BOX-e-teen', ARRAY['reboxetin', 'reboxatine']::text[], 'Mental health', 'Psychiatry'),
('Trazodone', 'medication', 'TRAZ-o-done', ARRAY['trazadone', 'trazodon']::text[], 'Mental health', 'Psychiatry'),
('Lofepramine', 'medication', 'lo-FEP-ra-meen', ARRAY['lofepramin', 'lofepramene']::text[], 'Mental health', 'Psychiatry'),
('Moclobemide', 'medication', 'mo-KLO-be-mide', ARRAY['moclobemid', 'moclobamide']::text[], 'Mental health', 'Psychiatry'),
('Phenelzine', 'medication', 'FEN-el-zeen', ARRAY['phenelzin', 'fenelzine']::text[], 'Mental health', 'Psychiatry'),
('Amygdala', 'anatomy', 'a-MIG-da-la', ARRAY['amigdala', 'amygdalla']::text[], 'Mental health', 'Psychiatry'),
('Nucleus accumbens', 'anatomy', 'NYOO-klee-us a-KUM-benz', ARRAY['nucleus acumbens', 'nucleus accumbans']::text[], 'Mental health', 'Psychiatry'),
('Prefrontal cortex', 'anatomy', 'pre-FRUN-tal KOR-tex', ARRAY['pre frontal cortex', 'prefrontal cortix']::text[], 'Mental health', 'Psychiatry'),
('Limbic system', 'anatomy', 'LIM-bik', ARRAY['limbick system', 'limbik system']::text[], 'Mental health', 'Psychiatry'),
('Locus coeruleus', 'anatomy', 'LO-kus se-ROO-lee-us', ARRAY['locus ceruleus', 'locus coerulius']::text[], 'Mental health', 'Psychiatry'),
('Raphe nuclei', 'anatomy', 'RAY-fee NYOO-klee-eye', ARRAY['raphae nuclei', 'raphe nucli']::text[], 'Mental health', 'Psychiatry'),
('Ventral tegmental area', 'anatomy', 'VEN-tral teg-MEN-tal', ARRAY['ventral tegmentel area', 'ventrel tegmental area']::text[], 'Mental health', 'Psychiatry'),
('Anterior cingulate cortex', 'anatomy', 'SIN-gyoo-late', ARRAY['anterior cingulate cortix', 'anterior singulate cortex']::text[], 'Mental health', 'Psychiatry'),
('Insula', 'anatomy', 'IN-syoo-la', ARRAY['insular', 'insulah']::text[], 'Mental health', 'Psychiatry'),
('Synaptic cleft', 'anatomy', 'si-NAP-tik kleft', ARRAY['synaptick cleft', 'sinaptic cleft']::text[], 'Mental health', 'Psychiatry'),
('Dendrites', 'anatomy', 'DEN-drites', ARRAY['dendrights', 'dendrytes']::text[], 'Mental health', 'Psychiatry'),
('Axon terminals', 'anatomy', 'AK-son TER-min-alz', ARRAY['axan terminals', 'axon terminels']::text[], 'Mental health', 'Psychiatry'),
('Neuroglia', 'anatomy', 'nyoo-RO-glee-a', ARRAY['neuroglea', 'neurogliah']::text[], 'Mental health', 'Psychiatry'),
('Astrocytes', 'anatomy', 'AS-tro-sites', ARRAY['astracytes', 'astrositess']::text[], 'Mental health', 'Psychiatry'),
('Oligodendrocytes', 'anatomy', 'ol-i-go-DEN-dro-sites', ARRAY['oligadendrocytes', 'oligodendracytes']::text[], 'Mental health', 'Psychiatry'),
('Vilanterol', 'medication', 'vy-LAN-ter-ol', ARRAY['vilanteral', 'vylanterol']::text[], 'Respiratory', 'Respiratory medicine'),
('Umeclidinium', 'medication', 'yoo-me-kli-DIN-ee-um', ARRAY['umeclidinum', 'umecliduinium']::text[], 'Respiratory', 'Respiratory medicine'),
('Glycopyrronium', 'medication', 'gly-ko-py-RO-nee-um', ARRAY['glycopyronium', 'glicopyrronium']::text[], 'Respiratory', 'Respiratory medicine'),
('Roflumilast', 'medication', 'ro-FLOO-mi-last', ARRAY['roflumilest', 'rofloomilast']::text[], 'Respiratory', 'Respiratory medicine'),
('Omalizumab', 'medication', 'o-ma-LIZ-oo-mab', ARRAY['omalizumumab', 'omaluzimab']::text[], 'Respiratory', 'Respiratory medicine'),
('Mepolizumab', 'medication', 'me-po-LIZ-oo-mab', ARRAY['mepolizumumab', 'mepoluzimab']::text[], 'Respiratory', 'Respiratory medicine'),
('Benralizumab', 'medication', 'ben-ra-LIZ-oo-mab', ARRAY['benralizumumab', 'benraluzimab']::text[], 'Respiratory', 'Respiratory medicine'),
('Reslizumab', 'medication', 'res-li-ZOO-mab', ARRAY['reslizumumab', 'reslyzumab']::text[], 'Respiratory', 'Respiratory medicine'),
('Aclidinium', 'medication', 'a-kli-DIN-ee-um', ARRAY['aclidinum', 'acliduinium']::text[], 'Respiratory', 'Respiratory medicine'),
('Indacaterol', 'medication', 'in-da-KAT-er-ol', ARRAY['indacaterall', 'indakaterol']::text[], 'Respiratory', 'Respiratory medicine'),
('Bronchioles', 'anatomy', 'BRONG-kee-oles', ARRAY['bronchioals', 'bronkioles']::text[], 'Respiratory', 'Respiratory medicine'),
('Terminal bronchioles', 'anatomy', 'TER-min-al BRONG-kee-oles', ARRAY['terminel bronchioles', 'terminal bronkioles']::text[], 'Respiratory', 'Respiratory medicine'),
('Respiratory bronchioles', 'anatomy', 'RES-pra-tor-ee BRONG-kee-oles', ARRAY['respiritory bronchioles', 'respiratory bronkioles']::text[], 'Respiratory', 'Respiratory medicine'),
('Alveolar sacs', 'anatomy', 'al-VEE-o-lar', ARRAY['alveolar sackss', 'alveolor sacs']::text[], 'Respiratory', 'Respiratory medicine'),
('Alveolar ducts', 'anatomy', 'al-VEE-o-lar dukts', ARRAY['alveolar ducktss', 'alveolor ducts']::text[], 'Respiratory', 'Respiratory medicine'),
('Visceral pleura', 'anatomy', 'VIS-er-al PLOOR-a', ARRAY['visceral plura', 'visceral pleurah']::text[], 'Respiratory', 'Respiratory medicine'),
('Parietal pleura', 'anatomy', 'pa-RY-e-tal PLOOR-a', ARRAY['parietal plura', 'parietel pleura']::text[], 'Respiratory', 'Respiratory medicine'),
('Costophrenic angle', 'anatomy', 'kos-to-FREN-ik', ARRAY['costophrenick angle', 'costofrenic angle']::text[], 'Respiratory', 'Respiratory medicine'),
('Hilum of lung', 'anatomy', 'HY-lum', ARRAY['hylum of lung', 'hilum of lunge']::text[], 'Respiratory', 'Respiratory medicine'),
('Carina', 'anatomy', 'ka-RY-na', ARRAY['carinah', 'karina']::text[], 'Respiratory', 'Respiratory medicine'),
('Apex of lung', 'anatomy', 'AY-pex', ARRAY['apecs of lung', 'apex of lunge']::text[], 'Respiratory', 'Respiratory medicine'),
('Base of lung', 'anatomy', 'base of lung', ARRAY['basse of lung', 'base of lunge']::text[], 'Respiratory', 'Respiratory medicine'),
('Upper lobe of lung', 'anatomy', 'upper lobe', ARRAY['upper lobe of lunge', 'uper lobe of lung']::text[], 'Respiratory', 'Respiratory medicine'),
('Middle lobe of lung', 'anatomy', 'middle lobe', ARRAY['middle lobe of lunge', 'midle lobe of lung']::text[], 'Respiratory', 'Respiratory medicine'),
('Lower lobe of lung', 'anatomy', 'lower lobe', ARRAY['lower lobe of lunge', 'lowor lobe of lung']::text[], 'Respiratory', 'Respiratory medicine'),
('Diaphragmatic pleura', 'anatomy', 'dy-a-frag-MAT-ik PLOOR-a', ARRAY['diaphragmatic plura', 'diaphramatic pleura']::text[], 'Respiratory', 'Respiratory medicine'),
('Intercostal muscles', 'anatomy', 'in-ter-KOS-tal', ARRAY['inter costal muscles', 'intercostel muscles']::text[], 'Respiratory', 'Respiratory medicine'),
('Phrenic nerve', 'anatomy', 'FREN-ik nerv', ARRAY['phrenick nerve', 'frenic nerve']::text[], 'Respiratory', 'Respiratory medicine'),
('Pulmonary capillaries', 'anatomy', 'PUL-mo-na-ree KAP-i-lar-eez', ARRAY['pulminary capillaries', 'pulmonary capilaries']::text[], 'Respiratory', 'Respiratory medicine'),
('Bronchopulmonary segments', 'anatomy', 'brong-ko-PUL-mo-na-ree', ARRAY['broncho pulmonary segments', 'bronchopulminary segments']::text[], 'Respiratory', 'Respiratory medicine'),
('Baricitinib', 'medication', 'ba-ri-SY-ti-nib', ARRAY['baricitinid', 'baricytinib']::text[], 'Musculoskeletal', 'Rheumatology'),
('Upadacitinib', 'medication', 'oo-pa-da-SY-ti-nib', ARRAY['upadacitinid', 'upadacytinib']::text[], 'Musculoskeletal', 'Rheumatology'),
('Abatacept', 'medication', 'a-BAT-a-sept', ARRAY['abataceptt', 'abattacept']::text[], 'Musculoskeletal', 'Rheumatology'),
('Belimumab', 'medication', 'be-LIM-yoo-mab', ARRAY['belimumumab', 'beluzimab']::text[], 'Musculoskeletal', 'Rheumatology'),
('Anakinra', 'medication', 'an-a-KIN-ra', ARRAY['anakynra', 'anakinrah']::text[], 'Musculoskeletal', 'Rheumatology'),
('Canakinumab', 'medication', 'kan-a-KIN-yoo-mab', ARRAY['canakinumumab', 'canakinamab']::text[], 'Musculoskeletal', 'Rheumatology'),
('Sarilumab', 'medication', 'sa-RIL-yoo-mab', ARRAY['sarilumumab', 'sariluzimab']::text[], 'Musculoskeletal', 'Rheumatology'),
('Certolizumab pegol', 'medication', 'ser-to-LIZ-oo-mab PEG-ol', ARRAY['certolizumab peggol', 'certolizumumab pegol']::text[], 'Musculoskeletal', 'Rheumatology'),
('Mycophenolate mofetil', 'medication', 'my-ko-FEN-o-late MO-fe-til', ARRAY['mycophenolate mofetal', 'mycofenolate mofetil']::text[], 'Musculoskeletal', 'Rheumatology'),
('Ciclosporin', 'medication', 'sy-klo-SPOR-in', ARRAY['cyclosporine', 'ciclosporen']::text[], 'Musculoskeletal', 'Rheumatology'),
('Enthesis', 'anatomy', 'en-THEE-sis', ARRAY['enthesiss', 'enthisis']::text[], 'Musculoskeletal', 'Rheumatology'),
('Tendon sheath', 'anatomy', 'TEN-don sheeth', ARRAY['tendan sheath', 'tendon sheeth']::text[], 'Musculoskeletal', 'Rheumatology'),
('Joint capsule', 'anatomy', 'joynt KAP-syool', ARRAY['joint capsul', 'joynt capsule']::text[], 'Musculoskeletal', 'Rheumatology'),
('Cartilage matrix', 'anatomy', 'KAR-ti-lij MAY-trix', ARRAY['cartilege matrix', 'cartilage matrics']::text[], 'Musculoskeletal', 'Rheumatology'),
('Chondrocytes', 'anatomy', 'KON-dro-sites', ARRAY['condrocytes', 'chondracytes']::text[], 'Musculoskeletal', 'Rheumatology'),
('Osteoclasts', 'anatomy', 'OS-tee-o-klasts', ARRAY['osteaclasts', 'osteoclastss']::text[], 'Musculoskeletal', 'Rheumatology'),
('Osteoblasts', 'anatomy', 'OS-tee-o-blasts', ARRAY['osteablasts', 'osteoblastss']::text[], 'Musculoskeletal', 'Rheumatology'),
('Osteocytes', 'anatomy', 'OS-tee-o-sites', ARRAY['osteacytes', 'osteositess']::text[], 'Musculoskeletal', 'Rheumatology'),
('Trabecular bone', 'anatomy', 'tra-BEK-yoo-lar', ARRAY['trabecula bone', 'trabekular bone']::text[], 'Musculoskeletal', 'Rheumatology'),
('Cortical bone', 'anatomy', 'KOR-ti-kal', ARRAY['cortikal bone', 'cortacal bone']::text[], 'Musculoskeletal', 'Rheumatology'),
('Pannus', 'anatomy', 'PAN-us', ARRAY['pannis', 'panus']::text[], 'Musculoskeletal', 'Rheumatology'),
('Ligamentum flavum', 'anatomy', 'lig-a-MEN-tum FLAY-vum', ARRAY['ligamentum flavim', 'ligementum flavum']::text[], 'Musculoskeletal', 'Rheumatology'),
('Interspinous ligament', 'anatomy', 'in-ter-SPY-nus', ARRAY['inter spinous ligament', 'interspinus ligament']::text[], 'Musculoskeletal', 'Rheumatology'),
('Costovertebral joint', 'anatomy', 'kos-to-VER-te-bral', ARRAY['costo vertebral joint', 'costovertebrel joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Manubriosternal joint', 'anatomy', 'ma-noo-bree-o-STER-nal', ARRAY['manubrio sternal joint', 'manubriosternel joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Symphysis pubis', 'anatomy', 'SIM-fi-sis PYOO-bis', ARRAY['symphisis pubis', 'symphysis pubiss']::text[], 'Musculoskeletal', 'Rheumatology'),
('Temporomandibular joint', 'anatomy', 'tem-po-ro-man-DIB-yoo-lar', ARRAY['temperomandibular joint', 'temporomandibula joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Sternoclavicular joint', 'anatomy', 'ster-no-kla-VIK-yoo-lar', ARRAY['sterno clavicular joint', 'sternoclavicula joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Metatarsophalangeal joint', 'anatomy', 'met-a-tar-so-fa-LAN-jee-al', ARRAY['metatarso phalangeal joint', 'metatarsophalangial joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Interphalangeal joint', 'anatomy', 'in-ter-fa-LAN-jee-al', ARRAY['inter phalangeal joint', 'interphalangial joint']::text[], 'Musculoskeletal', 'Rheumatology'),
('Sildenafil', 'medication', 'sil-DEN-a-fil', ARRAY['sildenafal', 'sildenifil']::text[], 'Reproductive', 'Urology'),
('Vardenafil', 'medication', 'var-DEN-a-fil', ARRAY['vardenafal', 'vardenifil']::text[], 'Reproductive', 'Urology'),
('Alfuzosin', 'medication', 'al-FYOO-zo-sin', ARRAY['alfuzosen', 'alfusozin']::text[], 'Genitourinary', 'Urology'),
('Terazosin', 'medication', 'te-RAZ-o-sin', ARRAY['terazosen', 'terazozin']::text[], 'Genitourinary', 'Urology'),
('Mirabegron', 'medication', 'mir-a-BEG-ron', ARRAY['mirabegran', 'mirabegrone']::text[], 'Genitourinary', 'Urology'),
('Silodosin', 'medication', 'sy-LO-do-sin', ARRAY['silodosen', 'sylodosin']::text[], 'Genitourinary', 'Urology'),
('Darifenacin', 'medication', 'da-ri-FEN-a-sin', ARRAY['darifenacen', 'darifenicin']::text[], 'Genitourinary', 'Urology'),
('Trospium', 'medication', 'TROS-pee-um', ARRAY['trospum', 'trospeum']::text[], 'Genitourinary', 'Urology'),
('Bethanechol', 'medication', 'be-THAN-e-kol', ARRAY['bethanacol', 'bethanechal']::text[], 'Genitourinary', 'Urology'),
('Phenazopyridine', 'medication', 'fen-az-o-PY-ri-deen', ARRAY['phenazopyridin', 'phenazopyridene']::text[], 'Genitourinary', 'Urology'),
('Renal cortex', 'anatomy', 'REE-nal KOR-tex', ARRAY['renel cortex', 'renal cortix']::text[], 'Genitourinary', 'Urology'),
('Renal medulla', 'anatomy', 'REE-nal me-DUL-a', ARRAY['renel medulla', 'renal medula']::text[], 'Genitourinary', 'Urology'),
('Renal pelvis', 'anatomy', 'REE-nal PEL-vis', ARRAY['renel pelvis', 'renal pelviss']::text[], 'Genitourinary', 'Urology'),
('Renal calyces', 'anatomy', 'REE-nal KAL-i-seez', ARRAY['renel calyces', 'renal calices']::text[], 'Genitourinary', 'Urology'),
('Glomerulus', 'anatomy', 'glo-MER-yoo-lus', ARRAY['glomerulis', 'glomerulos']::text[], 'Genitourinary', 'Urology'),
('Bowman''s capsule', 'anatomy', 'BOW-manz KAP-syool', ARRAY['bowmans capsule', 'Bowman''s capsul']::text[], 'Genitourinary', 'Urology'),
('Proximal convoluted tubule', 'anatomy', 'PROX-im-al kon-vo-LOO-ted', ARRAY['proximal convaluted tubule', 'proximel convoluted tubule']::text[], 'Genitourinary', 'Urology'),
('Distal convoluted tubule', 'anatomy', 'DIS-tal kon-vo-LOO-ted', ARRAY['distal convaluted tubule', 'distel convoluted tubule']::text[], 'Genitourinary', 'Urology'),
('Loop of Henle', 'anatomy', 'loop of HEN-lee', ARRAY['loop of henlee', 'loop of hensle']::text[], 'Genitourinary', 'Urology'),
('Collecting duct', 'anatomy', 'ko-LEK-ting dukt', ARRAY['collecting duckt', 'colecting duct']::text[], 'Genitourinary', 'Urology'),
('Nephron', 'anatomy', 'NEF-ron', ARRAY['nefron', 'nephran']::text[], 'Genitourinary', 'Urology'),
('Detrusor muscle', 'anatomy', 'de-TROO-zor', ARRAY['detrusar muscle', 'detruser muscle']::text[], 'Genitourinary', 'Urology'),
('Trigone of bladder', 'anatomy', 'TRY-gone', ARRAY['trygone of bladder', 'trigone of bladdar']::text[], 'Genitourinary', 'Urology'),
('External urethral sphincter', 'anatomy', 'yoo-REE-thral SFINK-ter', ARRAY['external urethral sphinkter', 'external urethrel sphincter']::text[], 'Genitourinary', 'Urology'),
('Internal urethral sphincter', 'anatomy', 'yoo-REE-thral SFINK-ter', ARRAY['internal urethral sphinkter', 'internal urethrel sphincter']::text[], 'Genitourinary', 'Urology'),
('Corpus cavernosum', 'anatomy', 'KOR-pus kav-er-NO-sum', ARRAY['corpus cavernosom', 'corpus cavernossum']::text[], 'Reproductive', 'Urology'),
('Corpus spongiosum', 'anatomy', 'KOR-pus spon-jee-O-sum', ARRAY['corpus spongiosom', 'corpus spongiossum']::text[], 'Reproductive', 'Urology'),
('Glans penis', 'anatomy', 'glanz PEE-nis', ARRAY['glans peniss', 'glanz penis']::text[], 'Reproductive', 'Urology'),
('Foreskin', 'anatomy', 'FOR-skin', ARRAY['foreskyn', 'forskin']::text[], 'Reproductive', 'Urology'),
('Tunica vaginalis', 'anatomy', 'TYOO-ni-ka vaj-in-AL-is', ARRAY['tunica vaginalus', 'tunika vaginalis']::text[], 'Reproductive', 'Urology'),
('Ferric carboxymaltose', 'medication', 'FER-ik kar-box-ee-MAL-tose', ARRAY['ferric carboxymaltos', 'ferric carboxymaltoze']::text[], 'Blood & immune', 'General medicine'),
('Epoetin alfa', 'medication', 'e-PO-e-tin AL-fa', ARRAY['epoetin alpha', 'epoietin alfa']::text[], 'Blood & immune', 'General medicine'),
('Darbepoetin alfa', 'medication', 'dar-be-PO-e-tin AL-fa', ARRAY['darbepoetin alpha', 'darbepoietin alfa']::text[], 'Blood & immune', 'General medicine'),
('Filgrastim', 'medication', 'fil-GRAS-tim', ARRAY['filgrastam', 'filgastrim']::text[], 'Blood & immune', 'Oncology'),
('Pegfilgrastim', 'medication', 'peg-fil-GRAS-tim', ARRAY['pegfilgrastam', 'pegfilgastrim']::text[], 'Blood & immune', 'Oncology'),
('Immunoglobulin', 'medication', 'im-yoo-no-GLOB-yoo-lin', ARRAY['immunoglobulen', 'immunoglobin']::text[], 'Blood & immune', 'General medicine'),
('Anti-D immunoglobulin', 'medication', 'anti dee im-yoo-no-GLOB-yoo-lin', ARRAY['anti d immunoglobulin', 'anti-d immunoglobulen']::text[], 'Blood & immune', 'Gynaecology'),
('Cyproterone acetate', 'medication', 'sy-PRO-te-rone AS-e-tate', ARRAY['cyproterone acitate', 'cyprotarone acetate']::text[], 'Reproductive', 'Endocrinology'),
('Finerenone', 'medication', 'fi-NER-e-known', ARRAY['finerenon', 'finerinone']::text[], 'Endocrine', 'Endocrinology'),
('Canagliflozin', 'medication', 'kan-a-gli-FLOW-zin', ARRAY['canagliflozen', 'canaglifozin']::text[], 'Endocrine', 'Endocrinology'),
('Linagliptin', 'medication', 'lin-a-GLIP-tin', ARRAY['linagliptan', 'linnagliptin']::text[], 'Endocrine', 'Endocrinology'),
('Saxagliptin', 'medication', 'sax-a-GLIP-tin', ARRAY['saxagliptan', 'saxaglyptin']::text[], 'Endocrine', 'Endocrinology'),
('Acarbose', 'medication', 'AK-ar-bose', ARRAY['acarboze', 'akarbose']::text[], 'Endocrine', 'Endocrinology'),
('Repaglinide', 'medication', 're-PAG-li-nide', ARRAY['repaglinid', 'repaglynide']::text[], 'Endocrine', 'Endocrinology'),
('Nateglinide', 'medication', 'na-TEG-li-nide', ARRAY['nateglinid', 'nateglynide']::text[], 'Endocrine', 'Endocrinology'),
('Orlistat', 'medication', 'OR-li-stat', ARRAY['orlistatt', 'orlystat']::text[], 'Gastrointestinal', 'General medicine'),
('Naltrexone', 'medication', 'nal-TREX-own', ARRAY['naltrexon', 'naltraxone']::text[], 'Mental health', 'Psychiatry'),
('Bupropion', 'medication', 'byoo-PRO-pee-on', ARRAY['bupropian', 'bupropiom']::text[], 'Mental health', 'Psychiatry'),
('Varenicline', 'medication', 'va-REN-i-kleen', ARRAY['vareniclin', 'varenacline']::text[], 'Mental health', 'General medicine'),
('Nicotine patch', 'medication', 'NIK-o-teen', ARRAY['nicatine patch', 'nicotene patch']::text[], 'General / systemic', 'General medicine'),
('Disulfiram', 'medication', 'dy-SUL-fi-ram', ARRAY['disulfaram', 'disulphiram']::text[], 'Mental health', 'Psychiatry'),
('Acamprosate', 'medication', 'a-KAM-pro-sate', ARRAY['acamprosat', 'accamprosate']::text[], 'Mental health', 'Psychiatry'),
('Chlordiazepoxide', 'medication', 'klor-dy-az-e-POX-ide', ARRAY['chlordiazepoxid', 'chlordiazapoxide']::text[], 'Mental health', 'Psychiatry'),
('Lorazepam', 'medication', 'lo-RAZ-e-pam', ARRAY['lorazepan', 'lorezepam']::text[], 'Mental health', 'Psychiatry'),
('Temazepam', 'medication', 'te-MAZ-e-pam', ARRAY['temazepan', 'temezepam']::text[], 'Mental health', 'Psychiatry'),
('Clomethiazole', 'medication', 'klo-me-THY-a-zole', ARRAY['clomethiazol', 'clomethyazole']::text[], 'Mental health', 'Psychiatry'),
('Modafinil', 'medication', 'mo-DAF-in-il', ARRAY['modafinal', 'modafenil']::text[], 'Nervous system', 'Neurology'),
('Armodafinil', 'medication', 'ar-mo-DAF-in-il', ARRAY['armodafinal', 'armodafenil']::text[], 'Nervous system', 'Neurology'),
('Pitolisant', 'medication', 'py-TOL-i-sant', ARRAY['pitolisent', 'pytolisant']::text[], 'Nervous system', 'Neurology'),
('Sodium oxybate', 'medication', 'SO-dee-um OX-i-bate', ARRAY['sodium oxybat', 'sodium oxibate']::text[], 'Nervous system', 'Neurology');
