-- Veyn: hospitals directory as a real database table, so admin can apply
-- secretary-submitted contact suggestions (see migration_48_contact_suggestions.sql)
-- directly instead of just marking them applied as a record. Replaces the
-- static account/hospitals-data.js (297 entries), which is deleted once
-- every page that read it has been switched over to querying this table.
-- gp-practices.json (15,574 rows, a bulk NHS import) is intentionally NOT
-- migrated — GP suggestions stay a manual "admin edits the file" review.
-- Run this in the Supabase SQL editor.

create table hospitals (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  area text,
  town text,
  type text,
  contact text,
  website text,
  specialties text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index hospitals_name_idx on hospitals (lower(name));

alter table hospitals enable row level security;

create policy "Hospitals are publicly readable"
  on hospitals for select using (true);

create policy "Admins can insert hospitals"
  on hospitals for insert with check (is_admin());

create policy "Admins can update hospitals"
  on hospitals for update using (is_admin());

create policy "Admins can delete hospitals"
  on hospitals for delete using (is_admin());

-- One-time seed from account/hospitals-data.js (297 rows), generated
-- programmatically from the file, not hand-typed.
insert into hospitals (name, area, town, type, contact, website, specialties, notes) values
  ('The Manor Hospital', 'Bedfordshire', 'Bedford', 'Private - Circle', '01234 364252', 'circlehealthgroup.co.uk', 'Orthopaedics, ENT, Gynae, Imaging, Surgery', 'Major private referral hospital'),
  ('Bedford Hospital Private Patients', 'Bedfordshire', 'Bedford', 'NHS + Private', '01234 355122', 'bedfordshirehospitals.nhs.uk', 'Diagnostics, consultants, outpatient clinics', 'NHS consultant private work'),
  ('Luton & Dunstable Private Patients', 'Bedfordshire', 'Luton', 'NHS + Private', '01582 491166', 'bedfordshirehospitals.nhs.uk', 'Surgery, imaging, diagnostics', 'Useful NHS/private consultant route'),
  ('Spire Harpenden Hospital', 'Bedfordshire', 'Harpenden', 'Private - Spire', '01582 763191', 'spirehealthcare.com', 'Imaging, Surgery, Outpatients, Orthopaedics', 'Often used by Bedfordshire patients'),
  ('Circle Reading Hospital', 'Berkshire', 'Reading', 'Private Hospital - Circle Health', '0118 922 6888', 'circlehealthgroup.co.uk', 'Outpatients, imaging, diagnostics, surgery, orthopaedics, endoscopy', 'Useful for consultant secretaries, imaging bookings, admissions and theatre coordination'),
  ('Berkshire Independent Hospital', 'Berkshire', 'Reading', 'Private Hospital - Ramsay', '0118 902 8000', 'ramsayhealth.co.uk', 'Surgery, diagnostics, orthopaedics, physiotherapy, imaging', 'Good private referral route for outpatient clinics and procedure bookings'),
  ('Royal Berkshire Private Healthcare', 'Berkshire', 'Reading', 'NHS + Private PPU', '0118 322 5111', 'royalberkshireprivate.co.uk', 'Consultant-led private care, radiology, surgery, diagnostics, outpatients', 'Useful NHS consultant private pathway; dedicated radiology/private healthcare route'),
  ('Royal Berkshire Hospital Radiology Private Services', 'Berkshire', 'Reading', 'NHS + Private Imaging', '0118 322 5111', 'royalberkshireprivate.co.uk', 'Private radiology, imaging, interventional radiology, diagnostics', 'Strong secretary usefulness for scan/referral coordination'),
  ('Parkside Suite Wexham', 'Berkshire', 'Slough / Wexham', 'NHS + Private PPU', '0300 615 3365', 'parkside-suite-wexham.org.uk', 'Private healthcare within Wexham Park Hospital, admissions, appointments, diagnostics', 'Useful for private patient admissions and NHS consultant pathways'),
  ('Spire Dunedin Hospital', 'Berkshire', 'Reading', 'Private Hospital - Spire', '0118 958 7676', 'spirehealthcare.com', 'Outpatients, diagnostics, surgery, orthopaedics, imaging', 'Good consultant room/private referral route'),
  ('Berkshire Imaging / InHealth routes', 'Berkshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound and diagnostic pathways depending on site', 'Useful for imaging booking and diagnostics referrals'),
  ('Spire Bristol Hospital', 'Bristol', 'Bristol', 'Private Hospital - Spire', '0117 980 4000', 'spirehealthcare.com', 'Private hospital, diagnostics, imaging, outpatients, surgery, orthopaedics', 'Large private hospital; useful for consultant secretaries, admissions and imaging'),
  ('Nuffield Health Bristol Hospital', 'Bristol', 'Clifton / Bristol', 'Private Hospital - Nuffield', '0117 906 4870', 'nuffieldhealth.com', '30-bed private hospital, digital theatres, surgery, outpatients, diagnostics', 'Useful for consultant clinics, theatres and private referral routes'),
  ('Practice Plus Group Hospital Emersons Green', 'Bristol', 'Emersons Green', 'Independent Sector / NHS + Private', '0330 162 0974', 'practiceplusgroup.com', 'NHS and private care, hip/knee surgery, cataracts, general surgery, diagnostics', 'Very useful for NHS/private referrals and elective pathway coordination'),
  ('University Hospitals Bristol and Weston Private Services', 'Bristol', 'Bristol', 'NHS + Private', '0117 923 0000', 'uhbristol.nhs.uk', 'Private services, specialist consultants, diagnostics, outpatient specialties', 'Useful NHS consultant/private patient route'),
  ('Bristol Eye Hospital Private / Specialist Pathways', 'Bristol', 'Bristol', 'NHS + Private / Specialist', '0117 923 0000', 'uhbristol.nhs.uk', 'Ophthalmology, diagnostics, outpatient eye services', 'Useful ophthalmology secretary and clinic routing'),
  ('Bristol Royal Infirmary Private Patient Pathways', 'Bristol', 'Bristol', 'NHS + Private', '0117 923 0000', 'uhbristol.nhs.uk', 'Surgery, cardiology, diagnostics, specialist medicine', 'Useful NHS/private consultant secretary route'),
  ('Vista Health Bristol Area', 'Bristol', 'Bristol area', 'Private Diagnostics', '0333 200 2064', 'vista-health.co.uk', 'MRI, CT, ultrasound and diagnostic scans depending on site', 'Useful self-pay/private imaging route'),
  ('The Chiltern Hospital', 'Buckinghamshire', 'Great Missenden', 'Private - Circle', '01494 890890', 'circlehealthgroup.co.uk', 'Outpatients, Imaging/X-ray, Surgery, Endoscopy, Physio', 'Consultants, referrals, admissions, imaging'),
  ('The Shelburne Hospital', 'Buckinghamshire', 'High Wycombe', 'Private - Circle', '01494 888700', 'circlehealthgroup.co.uk', 'Outpatients, Imaging, Orthopaedics, Surgery', 'Consultant rooms and private referrals'),
  ('The Saxon Clinic', 'Buckinghamshire', 'Milton Keynes', 'Private - Circle', '01908 665533', 'circlehealthgroup.co.uk', 'Imaging, Surgery, Outpatients, Physio', 'Useful for appointments and bookings'),
  ('Blakelands Hospital', 'Buckinghamshire', 'Milton Keynes', 'Private - Ramsay', '01908 334200', 'ramsayhealth.co.uk', 'Day surgery, diagnostics, outpatient clinics', 'Admissions and theatre bookings'),
  ('Royal Buckinghamshire Hospital', 'Buckinghamshire', 'Aylesbury', 'Private', '01296 678800', 'royalbucks.co.uk', 'Neuro rehab, spinal, private GP', 'Specialist referrals'),
  ('Stoke Mandeville Hospital Private Patients', 'Buckinghamshire', 'Aylesbury', 'NHS + Private', '01296 315000', 'buckshealthcare.nhs.uk', 'NHS consultants, imaging, surgery', 'Private patient office route'),
  ('Wycombe Hospital Private Patients', 'Buckinghamshire', 'High Wycombe', 'NHS + Private', '01494 526161', 'buckshealthcare.nhs.uk', 'Cardiology, diagnostics, imaging', 'Consultant secretary route'),
  ('Nuffield Health Cambridge Hospital', 'Cambridgeshire', 'Cambridge', 'Private Hospital', '01223 370922', 'nuffieldhealth.com', 'Outpatients, MRI, CT, X-ray, surgery, oncology, orthopaedics, cardiology, private GP', 'Excellent consultant secretary contact route; referrals, imaging, admissions and theatre bookings'),
  ('Spire Cambridge Lea Hospital', 'Cambridgeshire', 'Impington / Cambridge', 'Private Hospital', '01223 266900', 'spirehealthcare.com', 'Diagnostics, imaging, outpatient clinics, surgery, orthopaedics, robotic surgery', 'Useful for consultant rooms, outpatient bookings, admissions and imaging'),
  ('Addenbrooke''s Hospital Private Patient Pathways', 'Cambridgeshire', 'Cambridge', 'NHS + Private / Specialist', '01223 805000', 'cuh.nhs.uk', 'Specialist medicine, surgery, imaging, oncology, neurosciences, diagnostics', 'NHS consultant secretary route; tertiary specialist referrals'),
  ('Cambridge University Hospitals Private Care', 'Cambridgeshire', 'Cambridge', 'NHS + Private', '01223 805000', 'cuh.nhs.uk', 'Consultants, diagnostics, outpatient specialties', 'Useful for locating NHS consultants with private practice'),
  ('Royal Papworth Hospital Private Care', 'Cambridgeshire', 'Cambridge Biomedical Campus', 'NHS + Private Specialist', '01223 638000', 'royalpapworth.nhs.uk', 'Cardiology, cardiothoracic surgery, respiratory medicine, imaging', 'Specialist heart/lung referrals; consultant secretary pathway'),
  ('Cambridge Heart Clinic', 'Cambridgeshire', 'Cambridge', 'Private Specialist Clinic', '01223 370922', 'cambridgeheartclinic.co.uk', 'Cardiology, cardiac investigations', 'Useful cardiology referral contact'),
  ('Momentm Health Cambridge Diagnostic Centre', 'Cambridgeshire', 'Great Shelford', 'Private Imaging / Diagnostics', '01223 344366', 'momentmhealth.com', 'MRI, ultrasound, diagnostic imaging', 'Useful direct imaging pathway for secretaries'),
  ('InHealth Diagnostics Cambridge Area', 'Cambridgeshire', 'Cambridge area', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound, diagnostic services', 'Useful imaging booking route'),
  ('Vista Health Cambridge Area', 'Cambridgeshire', 'Cambridge area', 'Private Diagnostics', '0333 200 2064', 'vista-health.co.uk', 'MRI, CT, ultrasound diagnostics', 'Useful for self-pay imaging referrals'),
  ('North Cambridgeshire Hospital', 'Cambridgeshire', 'Wisbech', 'NHS Services', '01945 488000', 'nwangliaft.nhs.uk', 'Outpatients, diagnostics, community services', 'Useful local NHS contact pathway'),
  ('Hinchingbrooke Hospital Private Patient Pathways', 'Cambridgeshire', 'Huntingdon', 'NHS + Private', '01480 416416', 'nwangliaft.nhs.uk', 'Surgery, imaging, outpatient clinics, diagnostics', 'Consultant secretary and NHS/private referral route'),
  ('Peterborough City Hospital Private Patient Pathways', 'Cambridgeshire', 'Peterborough', 'NHS + Private', '01733 678000', 'nwangliaft.nhs.uk', 'Diagnostics, surgery, specialist consultants', 'Useful for consultant secretaries and referrals'),
  ('Spire Cheshire Hospital', 'Cheshire', 'Warrington / Stretton', 'Private Hospital - Spire', '01925 265000', 'spirehealthcare.com', 'Scans and investigations, MRI, CT, X-ray, ultrasound, outpatients, surgery', 'Strong secretary usefulness for imaging, appointments and theatre booking routes'),
  ('Circle Cheshire Clinic', 'Cheshire', 'Northwich', 'Private Clinic - Circle Health', '01606 535500', 'circlehealthgroup.co.uk', 'Diagnostics, CT scan, outpatient services, NHS and private patients', 'Useful private/NHS clinic route and radiology coordination'),
  ('Nuffield Health Chester Hospital', 'Cheshire', 'Chester', 'Private Hospital - Nuffield', '01244 680444', 'nuffieldhealth.com', 'Private hospital, imaging, surgery, outpatients, orthopaedics', 'Useful for consultant clinics and private patient admissions'),
  ('The Wilmslow Hospital', 'Cheshire', 'Wilmslow', 'Private Hospital / HCA Healthcare UK', '01625 545000', 'hcahealthcare.co.uk', 'Private diagnostics, imaging, outpatient clinics, surgery, women''s and men''s health', 'High-value consultant-led centre; useful for secretary referrals and imaging'),
  ('HCA Cheshire Imaging and Diagnostics', 'Cheshire', 'Wilmslow / Cheshire', 'Private Diagnostics - HCA', '01625 545000', 'hcahealthcare.co.uk', 'MRI, X-ray, ultrasound, mammography, DEXA and rapid access clinics', 'Excellent radiology/imaging route for secretaries'),
  ('Cheshire Medical Imaging', 'Cheshire', 'Cheshire area', 'Imaging / Radiology Provider', 'Not listed', 'cheshiremedicalimaging.co.uk', 'Diagnostic and screening radiology support for NHS and private hospitals', 'Useful radiology provider reference; confirm direct contact online'),
  ('Countess of Chester Hospital Private Patient Pathways', 'Cheshire', 'Chester', 'NHS + Private', '01244 365000', 'coch.nhs.uk', 'Diagnostics, outpatient clinics, specialist consultants', 'NHS consultant/private pathway; confirm private patient contacts through switchboard'),
  ('Duchy Hospital', 'Cornwall', 'Truro', 'Private Hospital - Ramsay', '01872 226100', 'ramsayhealth.co.uk', 'Cornwall private hospital, X-ray, MRI, CT, ultrasound, endoscopy, day surgery', 'Main private hospital route in Cornwall; useful for imaging/admissions/theatre bookings'),
  ('Royal Cornwall Hospital Private Patient Pathways', 'Cornwall', 'Truro', 'NHS + Private', '01872 250000', 'royalcornwall.nhs.uk', 'Private patient policy, consulting rooms, diagnostics, specialist services', 'NHS consultant/private pathway; verify service availability before use'),
  ('West Cornwall Hospital Private Patient Pathways', 'Cornwall', 'Penzance', 'NHS + Private', '01736 874000', 'royalcornwall.nhs.uk', 'Diagnostics, outpatients, local services', 'NHS private patient policy applies; confirm current services via switchboard'),
  ('St Michael''s Hospital Private Patient Pathways', 'Cornwall', 'Hayle', 'NHS + Private', '01736 753234', 'royalcornwall.nhs.uk', 'Elective surgery, orthopaedics, outpatient pathways', 'Useful for elective/private pathway checking'),
  ('Duchy Hospital Imaging Centre', 'Cornwall', 'Truro', 'Private Imaging - Ramsay', '01872 226100', 'ramsayhealth.co.uk', 'MRI, CT, X-ray, ultrasound, scan booking', 'Direct imaging usefulness for medical secretaries'),
  ('Vista Health Cornwall Diagnostic Centre', 'Cornwall', 'Cornwall area', 'Private Diagnostics', '0333 200 2064', 'vista-health.co.uk', 'Private MRI, X-ray and CT depending on site', 'Useful for self-pay scan referrals; verify exact local site'),
  ('InHealth Cornwall Area Diagnostics', 'Cornwall', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound and community diagnostic services depending on site', 'Useful diagnostic provider route'),
  ('Woodlands Hospital', 'County Durham', 'Darlington', 'Private Hospital - Circle Health', '01325 341700', 'circlehealthgroup.co.uk', 'Private hospital, advanced treatments, surgery, diagnostics, imaging, outpatients', 'Useful for private referrals, radiology, admissions and theatre coordination'),
  ('Woodlands Hospital Private Imaging', 'County Durham', 'Darlington', 'Private Imaging - Circle Health', '01325 341700', 'circlehealthgroup.co.uk', 'Private imaging facilities, diagnostics, scans', 'Useful direct radiology/imaging route for secretaries'),
  ('Nuffield Health Tees Hospital', 'County Durham', 'Stockton-on-Tees / Tees area', 'Private Hospital - Nuffield', '01642 360100', 'nuffieldhealth.com', 'MRI, CT, breast screening, ultrasound, surgery, physiotherapy', 'Useful private imaging, admissions and consultant referral route'),
  ('Spire Washington Hospital', 'County Durham / Tyne and Wear border', 'Washington', 'Private Hospital - Spire', '0191 415 1272', 'spirehealthcare.com', 'Consultations, diagnosis, treatment, aftercare, X-rays and scans, surgery', 'Useful for North East private referrals and imaging/theatre coordination'),
  ('University Hospital of North Durham', 'County Durham', 'Durham', 'NHS + Private Pathways', '0191 333 2333', 'cddft.nhs.uk', 'Radiology, plain film, CT, ultrasound, diagnostics, consultant specialties', 'NHS consultant/private pathway; use switchboard for relevant secretary/department'),
  ('Darlington Memorial Hospital', 'County Durham', 'Darlington', 'NHS + Private Pathways', '01325 380100', 'cddft.nhs.uk', 'Radiology, CT, plain film, outpatient specialties, diagnostics', 'NHS consultant/private pathway; use switchboard for relevant secretary/department'),
  ('County Durham and Darlington Radiology', 'County Durham', 'Durham / Darlington', 'NHS Diagnostics', '0191 333 2333', 'cddft.nhs.uk', 'Diagnostic imaging, interventional procedures, plain film, CT, ultrasound', 'Useful for imaging/radiology routing and reports'),
  ('Cumberland Infirmary Private Patient Pathways', 'Cumbria', 'Carlisle', 'NHS + Private Pathways', '01228 523444', 'ncic.nhs.uk', 'Diagnostics, imaging, consultants, outpatient services', 'Use switchboard/private routes for consultant secretaries'),
  ('West Cumberland Hospital Private Patient Pathways', 'Cumbria', 'Whitehaven', 'NHS + Private Pathways', '01946 693181', 'ncic.nhs.uk', 'Diagnostics, outpatient clinics, imaging', 'Useful NHS consultant contact pathway'),
  ('Nuffield Health Carlisle links', 'Cumbria', 'Cumbria area', 'Private Healthcare Network', NULL, 'nuffieldhealth.com', 'Private referrals and consultant pathways where available', 'Check current local provision'),
  ('InHealth Cumbria Diagnostics', 'Cumbria', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound depending on site', 'Useful imaging referral route'),
  ('Nuffield Health Derby Hospital', 'Derbyshire', 'Derby', 'Private Hospital', '01332 540100', 'nuffieldhealth.com', 'Surgery, imaging, outpatients, diagnostics', 'Useful for consultant secretaries/admissions'),
  ('Royal Derby Hospital Private Patient Pathways', 'Derbyshire', 'Derby', 'NHS + Private', '01332 340131', 'uhdb.nhs.uk', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant private route'),
  ('Chesterfield Royal Hospital Private Pathways', 'Derbyshire', 'Chesterfield', 'NHS + Private', '01246 277271', 'chesterfieldroyal.nhs.uk', 'Outpatients, diagnostics, imaging', 'Useful secretary route'),
  ('InHealth Derbyshire Diagnostics', 'Derbyshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound', 'Imaging referrals'),
  ('Nuffield Health Exeter Hospital', 'Devon', 'Exeter', 'Private Hospital', '01392 276591', 'nuffieldhealth.com', 'Imaging, surgery, outpatients, orthopaedics', 'Consultant secretary/admission route'),
  ('Mount Stuart Hospital', 'Devon', 'Torquay', 'Private Hospital - Ramsay', '01803 321612', 'ramsayhealth.co.uk', 'Surgery, diagnostics, outpatients', 'Private referrals and theatre bookings'),
  ('Exeter Medical / Royal Devon Private Pathways', 'Devon', 'Exeter', 'NHS + Private', '01392 411611', 'royaldevon.nhs.uk', 'Consultants, diagnostics, specialist care', 'NHS/private consultant pathway'),
  ('Plymouth Hospitals Private Pathways', 'Devon', 'Plymouth', 'NHS + Private', '01752 202082', 'plymouthhospitals.nhs.uk', 'Diagnostics, surgery, specialists', 'Useful referral pathway'),
  ('Nuffield Health Bournemouth Hospital', 'Dorset', 'Bournemouth', 'Private Hospital', '01202 702830', 'nuffieldhealth.com', 'Surgery, imaging, diagnostics, outpatients', 'Consultant secretary route'),
  ('Harbour Hospital', 'Dorset', 'Poole', 'Private Hospital - Circle Health', '01202 244200', 'circlehealthgroup.co.uk', 'Imaging, surgery, orthopaedics, outpatients', 'Private referrals/admissions'),
  ('Dorset County Hospital Private Pathways', 'Dorset', 'Dorchester', 'NHS + Private', '01305 251150', 'dchft.nhs.uk', 'Diagnostics, consultants, imaging', 'NHS/private consultant route'),
  ('University Hospitals Dorset Private Pathways', 'Dorset', 'Bournemouth/Poole', 'NHS + Private', '0300 019 8499', 'uhd.nhs.uk', 'Specialists, imaging, outpatient care', 'Secretary contact via hospital routes'),
  ('Spire Hull and East Riding Hospital', 'East Riding of Yorkshire', 'Hull', 'Private Hospital - Spire', '01482 659471', 'spirehealthcare.com', 'Outpatients, imaging, diagnostics, surgery, orthopaedics', 'Useful for consultant secretaries, admissions and radiology bookings'),
  ('Hull Royal Infirmary Private Patient Pathways', 'East Riding of Yorkshire', 'Hull', 'NHS + Private Pathways', '01482 875875', 'hey.nhs.uk', 'Specialists, diagnostics, imaging, outpatient services', 'NHS consultant/private referral route'),
  ('Castle Hill Hospital Private Patient Pathways', 'East Riding of Yorkshire', 'Cottingham', 'NHS + Private Pathways', '01482 875875', 'hey.nhs.uk', 'Cardiology, cancer, surgery, diagnostics', 'Specialist NHS consultant route'),
  ('InHealth East Yorkshire Diagnostics', 'East Riding of Yorkshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound pathways', 'Useful imaging referral contact'),
  ('Nuffield Health Brighton Hospital', 'East Sussex', 'Brighton', 'Private Hospital - Nuffield', '01273 624488', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatients', 'Consultant clinics, admissions and theatre bookings'),
  ('Spire Sussex Hospital', 'East Sussex', 'Hastings', 'Private Hospital - Spire', '01424 757400', 'spirehealthcare.com', 'Imaging, surgery, orthopaedics, outpatient clinics', 'Useful private referral route'),
  ('Montefiore Hospital', 'East Sussex', 'Hove', 'Private Hospital - Spire', '01273 828120', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, private consultants', 'Useful for consultant secretary contacts'),
  ('Royal Sussex County Hospital Private Pathways', 'East Sussex', 'Brighton', 'NHS + Private', '01273 696955', 'uhsussex.nhs.uk', 'Specialists, imaging, diagnostics', 'NHS consultant/private pathway'),
  ('Springfield Hospital', 'Essex', 'Chelmsford', 'Private Hospital - Ramsay', '01245 234000', 'ramsayhealth.co.uk', 'Imaging, surgery, outpatients, diagnostics', 'Private admissions and consultant referrals'),
  ('Spire Wellesley Hospital', 'Essex', 'Southend', 'Private Hospital - Spire', '01702 462944', 'spirehealthcare.com', 'Diagnostics, surgery, imaging, outpatient clinics', 'Secretary referral and booking route'),
  ('Nuffield Health Brentwood Hospital', 'Essex', 'Brentwood', 'Private Hospital - Nuffield', '01277 695695', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, orthopaedics', 'Consultant secretary pathway'),
  ('Phoenix Hospital Chelmsford', 'Essex', 'Chelmsford', 'Private Hospital', '01245 801234', 'phoenixhospitalgroup.com', 'Private surgery, diagnostics, outpatient services', 'Useful consultant-led pathway'),
  ('Broomfield Hospital Private Pathways', 'Essex', 'Chelmsford', 'NHS + Private', '01245 362000', 'mse.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS consultant/private route'),
  ('Nuffield Health Cheltenham Hospital', 'Gloucestershire', 'Cheltenham', 'Private Hospital - Nuffield', '01242 246500', 'nuffieldhealth.com', 'Diagnostics, surgery, imaging, outpatients', 'Consultant rooms and admissions route'),
  ('Winfield Hospital', 'Gloucestershire', 'Gloucester', 'Private Hospital - Ramsay', '01452 331111', 'ramsayhealth.co.uk', 'Surgery, orthopaedics, imaging, diagnostics', 'Useful referral/admissions pathway'),
  ('Gloucestershire Hospitals Private Pathways', 'Gloucestershire', 'Gloucester/Cheltenham', 'NHS + Private', '0300 422 2222', 'gloshospitals.nhs.uk', 'Consultants, imaging, specialist services', 'NHS consultant secretary route'),
  ('InHealth Gloucestershire Diagnostics', 'Gloucestershire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound services', 'Useful imaging route'),
  ('Chelsea and Westminster Hospital Private Care', 'Greater London', 'Chelsea / Kensington', 'NHS + Private PPU', '020 3315 8484', 'chelwestprivatecare.co.uk', 'Private care, maternity, diagnostics, surgery, outpatients', 'Useful for consultants with NHS/private practice; check private care office for booking routes'),
  ('OneWelbeck', 'Greater London', 'Marylebone', 'Private Specialist Centre', '020 3653 2000', 'welbeck.com', 'Cardiology, digestive health, ENT, lung health, orthopaedics, imaging', 'Large consultant-suite model; useful for secretary referral routing'),
  ('The London Clinic', 'Greater London', 'Marylebone', 'Private Hospital', '020 7935 4444', 'thelondonclinic.co.uk', 'Cancer care, surgery, imaging, outpatients', 'Major central London private hospital with consultant rooms'),
  ('King Edward VII''s Hospital', 'Greater London', 'Marylebone', 'Private Hospital', '020 7486 4411', 'kingedwardvii.co.uk', 'Surgery, urology, orthopaedics, women''s health', 'Consultant-led private admissions and diagnostics'),
  ('Cromwell Hospital', 'Greater London', 'Kensington', 'Private Hospital - Bupa', '020 7460 5700', 'cromwellhospital.com', 'Diagnostics, surgery, cancer, cardiology', 'Large private hospital with outpatient and imaging departments'),
  ('Royal Free London Private Patients Unit', 'Greater London', 'Hampstead', 'NHS + Private PPU', '020 7317 7751', 'royalfreeprivatepatients.com', 'Liver, renal, cancer, surgery, diagnostics, dialysis', 'Large NHS PPU; useful for tertiary consultant referrals'),
  ('Imperial College Healthcare Private Care', 'Greater London', 'Paddington / Hammersmith', 'NHS + Private PPU', '020 3311 7700', 'private.imperial.nhs.uk', 'Cardiology, cancer, surgery, neurology, diagnostics', 'Private care across Imperial NHS hospitals'),
  ('Guy''s and St Thomas'' Specialist Care', 'Greater London', 'Westminster / London Bridge', 'NHS + Private PPU', '020 7188 5197', 'guysandstthomasprivatehealthcare.co.uk', 'Cardiology, cancer, transplant, complex surgery', 'NHS private care across five leading hospitals'),
  ('Royal Marsden Private Care', 'Greater London', 'Chelsea / Sutton', 'NHS + Private PPU', '020 7811 8111', 'royalmarsdenprivatecare.co.uk', 'Cancer, chemotherapy, radiotherapy, diagnostics', 'Major specialist oncology private care'),
  ('Moorfields Private Eye Hospital', 'Greater London', 'City Road / Marylebone', 'NHS + Private PPU', '020 7566 2803', 'moorfields-private.co.uk', 'Cataract, retina, glaucoma, cornea, ophthalmology', 'Specialist eye hospital; outpatient and theatre relevance'),
  ('The Christie Private Care', 'Greater Manchester', 'Manchester', 'NHS + Private / HCA', '0161 918 7296', 'hcahealthcare.co.uk', 'Cancer, chemotherapy, radiotherapy, diagnostics', 'Major oncology consultant pathway'),
  ('Spire Manchester Hospital', 'Greater Manchester', 'Manchester', 'Private Hospital - Spire', '0161 447 6677', 'spirehealthcare.com', 'Imaging, surgery, outpatients, diagnostics', 'Large consultant base'),
  ('The Alexandra Hospital', 'Greater Manchester', 'Cheadle', 'Private Hospital - Circle', '0161 428 3656', 'circlehealthgroup.co.uk', 'Diagnostics, surgery, imaging, orthopaedics', 'Useful for admissions and consultant secretaries'),
  ('Manchester Royal Infirmary Private Pathways', 'Greater Manchester', 'Manchester', 'NHS + Private', '0161 276 1234', 'mft.nhs.uk', 'Specialist medicine, diagnostics, imaging', 'NHS consultant/private route'),
  ('Wythenshawe Hospital Private Pathways', 'Greater Manchester', 'Manchester', 'NHS + Private', '0161 998 7070', 'mft.nhs.uk', 'Cardiac, respiratory, surgery, diagnostics', 'Specialist referral pathway'),
  ('Spire Southampton Hospital', 'Hampshire', 'Southampton', 'Private Hospital - Spire', '023 8077 5544', 'spirehealthcare.com', 'Imaging, diagnostics, surgery, orthopaedics, outpatient clinics', 'Useful for consultant secretaries, admissions and radiology bookings'),
  ('Nuffield Health Wessex Hospital', 'Hampshire', 'Eastleigh', 'Private Hospital - Nuffield', '023 8026 6377', 'nuffieldhealth.com', 'MRI, X-ray, surgery, diagnostics, outpatients', 'Private referral and consultant pathway'),
  ('Sarum Road Hospital', 'Hampshire', 'Winchester', 'Private Hospital - Circle Health', '01962 844555', 'circlehealthgroup.co.uk', 'Diagnostics, surgery, imaging, outpatient care', 'Admissions and consultant secretary route'),
  ('Queen Alexandra Hospital Private Pathways', 'Hampshire', 'Portsmouth', 'NHS + Private', '023 9228 6000', 'porthosp.nhs.uk', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant/private patient route'),
  ('University Hospital Southampton Private Care', 'Hampshire', 'Southampton', 'NHS + Private', '023 8077 7222', 'uhs.nhs.uk', 'Cancer, cardiac, surgery, imaging, specialist consultants', 'Useful tertiary consultant route'),
  ('Nuffield Health Hereford Hospital', 'Herefordshire', 'Hereford', 'Private Hospital - Nuffield', '01432 355131', 'nuffieldhealth.com', 'Outpatients, diagnostics, surgery, imaging', 'Consultant secretary and referral pathway'),
  ('Hereford County Hospital Private Patient Pathways', 'Herefordshire', 'Hereford', 'NHS + Private', '01432 355444', 'wyevalley.nhs.uk', 'Diagnostics, consultants, outpatient specialties', 'NHS consultant/private care route'),
  ('Wye Valley NHS Diagnostics', 'Herefordshire', 'Countywide', 'NHS Diagnostics', '01432 355444', 'wyevalley.nhs.uk', 'Radiology, scans, outpatient diagnostics', 'Useful imaging contact pathway'),
  ('InHealth Herefordshire Diagnostics', 'Herefordshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound routes', 'Useful for diagnostic referrals'),
  ('Spire Harpenden Hospital', 'Hertfordshire', 'Harpenden', 'Private Hospital - Spire', '01582 763191', 'spirehealthcare.com', 'Imaging, surgery, diagnostics, outpatient clinics', 'Consultant rooms and private referrals'),
  ('One Hatfield Hospital', 'Hertfordshire', 'Hatfield', 'Private Hospital', '01707 443333', 'onehealthcare.co.uk', 'MRI, diagnostics, surgery, outpatients', 'Useful for admissions and consultant secretaries'),
  ('Pinehill Hospital', 'Hertfordshire', 'Hitchin', 'Private Hospital - Ramsay', '01462 422822', 'ramsayhealth.co.uk', 'Surgery, imaging, diagnostics, orthopaedics', 'Private referral pathway'),
  ('Rivers Hospital', 'Hertfordshire', 'Sawbridgeworth', 'Private Hospital - Ramsay', '01279 600282', 'ramsayhealth.co.uk', 'Diagnostics, imaging, surgery, outpatient care', 'Useful consultant pathway'),
  ('Lister Hospital Private Pathways', 'Hertfordshire', 'Stevenage', 'NHS + Private', '01438 314333', 'enherts-tr.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS consultant route'),
  ('St Mary''s Hospital Private Patient Pathways', 'Isle of Wight', 'Newport', 'NHS + Private', '01983 524081', 'iow.nhs.uk', 'Diagnostics, imaging, outpatient specialties', 'NHS consultant/private route'),
  ('Isle of Wight Diagnostic Services', 'Isle of Wight', 'Newport', 'NHS Diagnostics', '01983 524081', 'iow.nhs.uk', 'Radiology, scans, diagnostics', 'Useful imaging pathway'),
  ('Mainland private referral routes', 'Isle of Wight', 'Southampton/Portsmouth links', 'Private Pathways', NULL, NULL, 'Spire/Nuffield/Circle mainland referral options', 'Often used for specialist private referrals'),
  ('KIMS Hospital', 'Kent', 'Maidstone', 'Private Hospital', '01622 237500', 'kims.org.uk', 'MRI, CT, imaging, surgery, outpatients, orthopaedics', 'Major Kent private hospital; useful secretary pathway'),
  ('Spire Alexandra Hospital', 'Kent', 'Chatham', 'Private Hospital - Spire', '01634 687166', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, outpatients', 'Consultant/admission route'),
  ('Benenden Hospital', 'Kent', 'Benenden', 'Independent Hospital', '01580 240333', 'benendenhospital.org.uk', 'Surgery, diagnostics, imaging, ophthalmology', 'Useful NHS/private pathway'),
  ('One Ashford Hospital', 'Kent', 'Ashford', 'Private Hospital', '01233 423000', 'onehealthcare.co.uk', 'Diagnostics, surgery, imaging, outpatient care', 'Consultant secretary route'),
  ('Maidstone and Tunbridge Wells Private Pathways', 'Kent', 'Maidstone/Tunbridge Wells', 'NHS + Private', '01622 729000', 'mtw.nhs.uk', 'Cancer, diagnostics, surgery, imaging', 'NHS consultant/private route'),
  ('Euxton Hall Hospital', 'Lancashire', 'Chorley', 'Private Hospital - Ramsay', '01257 276261', 'ramsayhealth.co.uk', 'Orthopaedics, surgery, diagnostics, imaging, outpatients', 'Useful for consultant secretaries, admissions and theatre bookings'),
  ('Fulwood Hall Hospital', 'Lancashire', 'Preston', 'Private Hospital - Ramsay', '01772 704111', 'ramsayhealth.co.uk', 'Imaging, diagnostics, surgery, outpatient clinics', 'Useful referral and booking route'),
  ('Spire Fylde Coast Hospital', 'Lancashire', 'Blackpool', 'Private Hospital - Spire', '01253 308031', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, orthopaedics', 'Consultant and imaging pathway'),
  ('Lancashire Teaching Hospitals Private Patient Pathways', 'Lancashire', 'Preston', 'NHS + Private', '01772 716565', 'lancsteachinghospitals.nhs.uk', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant/private route'),
  ('Nuffield Health Leicester Hospital', 'Leicestershire', 'Leicester', 'Private Hospital - Nuffield', '0116 276 9401', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatients', 'Useful consultant secretary pathway'),
  ('Spire Leicester Hospital', 'Leicestershire', 'Leicester', 'Private Hospital - Spire', '0116 265 3685', 'spirehealthcare.com', 'MRI, CT, X-ray, surgery, outpatient clinics', 'Useful for admissions and imaging bookings'),
  ('Leicester Royal Infirmary Private Pathways', 'Leicestershire', 'Leicester', 'NHS + Private', '0300 303 1573', 'uhl-tr.nhs.uk', 'Specialist consultants, imaging, diagnostics', 'NHS/private consultant route'),
  ('Glenfield Hospital Private Pathways', 'Leicestershire', 'Leicester', 'NHS + Private', '0300 303 1573', 'uhl-tr.nhs.uk', 'Cardiac, respiratory, diagnostics', 'Specialist referral route'),
  ('The Lincoln Hospital', 'Lincolnshire', 'Lincoln', 'Private Hospital - Circle Health', '01522 578000', 'circlehealthgroup.co.uk', 'Surgery, imaging, diagnostics, outpatient care', 'Consultant/admissions pathway'),
  ('St Hugh''s Hospital', 'Lincolnshire', 'Grimsby', 'Independent Hospital', '01472 251100', 'hmtsthughs.org', 'Diagnostics, imaging, surgery, outpatients', 'Useful private and NHS pathway'),
  ('Lincoln County Hospital Private Pathways', 'Lincolnshire', 'Lincoln', 'NHS + Private', '01522 512512', 'ulh.nhs.uk', 'Diagnostics, specialists, imaging', 'NHS consultant pathway'),
  ('Pilgrim Hospital Private Pathways', 'Lincolnshire', 'Boston', 'NHS + Private', '01205 364801', 'ulh.nhs.uk', 'Outpatients, diagnostics, imaging', 'Secretary referral route'),
  ('Spire Liverpool Hospital', 'Merseyside', 'Liverpool', 'Private Hospital - Spire', '0151 733 7123', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, outpatient clinics', 'Consultant secretary route'),
  ('Liverpool Women''s Private Patient Pathways', 'Merseyside', 'Liverpool', 'NHS + Private', '0151 708 9988', 'liverpoolwomens.nhs.uk', 'Women''s health, fertility, diagnostics', 'Specialist consultant pathway'),
  ('The Clatterbridge Cancer Centre Private Pathways', 'Merseyside', 'Liverpool', 'NHS + Private Specialist', '0151 556 5000', 'clatterbridgecc.nhs.uk', 'Cancer, oncology, chemotherapy, radiotherapy', 'Specialist oncology route'),
  ('Liverpool University Hospitals Private Pathways', 'Merseyside', 'Liverpool', 'NHS + Private', '0151 706 2000', 'liverpoolft.nhs.uk', 'Diagnostics, imaging, specialist medicine', 'NHS consultant/private route'),
  ('Spire Norwich Hospital', 'Norfolk', 'Norwich', 'Private Hospital - Spire', '01603 456181', 'spirehealthcare.com', 'Imaging, diagnostics, surgery, orthopaedics, outpatients', 'Useful consultant and radiology route'),
  ('Nuffield Health Norwich Hospital', 'Norfolk', 'Norwich', 'Private Hospital - Nuffield', '01603 456181', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatient services', 'Private referral pathway'),
  ('Norfolk and Norwich University Hospital Private Pathways', 'Norfolk', 'Norwich', 'NHS + Private', '01603 286286', 'nnuh.nhs.uk', 'Specialists, imaging, diagnostics, surgery', 'NHS consultant/private route'),
  ('Queen Elizabeth Hospital King''s Lynn Private Pathways', 'Norfolk', 'King''s Lynn', 'NHS + Private', '01553 613613', 'qehkl.nhs.uk', 'Diagnostics, imaging, outpatient specialties', 'Useful secretary route'),
  ('Nuffield Health York Hospital', 'North Yorkshire', 'York', 'Private Hospital - Nuffield', '01904 715000', 'nuffieldhealth.com', 'Outpatients, imaging, diagnostics, surgery, orthopaedics', 'Useful for consultant secretaries, admissions and imaging bookings'),
  ('York Hospital Private Patient Pathways', 'North Yorkshire', 'York', 'NHS + Private', '01904 631313', 'yorkhospitals.nhs.uk', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant/private patient route'),
  ('Harrogate District Hospital Private Pathways', 'North Yorkshire', 'Harrogate', 'NHS + Private', '01423 885959', 'hdft.nhs.uk', 'Diagnostics, outpatient specialties, imaging', 'Useful consultant secretary pathway'),
  ('InHealth North Yorkshire Diagnostics', 'North Yorkshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound services', 'Useful imaging route'),
  ('Three Shires Hospital', 'Northamptonshire', 'Northampton', 'Private - Circle', '01604 620311', 'circlehealthgroup.co.uk', 'Imaging, Outpatients, Surgery, Orthopaedics', 'Large consultant base'),
  ('Woodland Hospital', 'Northamptonshire', 'Kettering', 'Private - Ramsay', '01536 210019', 'ramsayhealth.co.uk', 'Orthopaedics, Surgery, Diagnostics', 'Admissions/referrals'),
  ('Northampton General Private Patients', 'Northamptonshire', 'Northampton', 'NHS + Private', '01604 634700', 'ngh.nhs.uk', 'Consultants, diagnostics, surgery', 'NHS private patient route'),
  ('Kettering General Private Patients', 'Northamptonshire', 'Kettering', 'NHS + Private', '01536 492000', 'kgh.nhs.uk', 'Outpatients, diagnostics, imaging', 'Consultant secretary route'),
  ('Northumbria Healthcare Private Pathways', 'Northumberland', 'Cramlington / Northumberland', 'NHS + Private', '0344 811 8111', 'northumbria.nhs.uk', 'Consultants, diagnostics, surgery, imaging', 'NHS/private consultant route'),
  ('Northumbria Specialist Emergency Care Hospital', 'Northumberland', 'Cramlington', 'NHS + Private Pathways', '0344 811 8111', 'northumbria.nhs.uk', 'Specialists, diagnostics, imaging', 'Secretary routing via trust contacts'),
  ('Wansbeck General Hospital Pathways', 'Northumberland', 'Ashington', 'NHS + Private Pathways', '0344 811 8111', 'northumbria.nhs.uk', 'Outpatients, diagnostics, imaging', 'Useful referral route'),
  ('InHealth Northumberland Diagnostics', 'Northumberland', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound', 'Useful scan pathway'),
  ('Spire Nottingham Hospital', 'Nottinghamshire', 'Nottingham', 'Private Hospital - Spire', '0115 937 7800', 'spirehealthcare.com', 'Imaging, diagnostics, surgery, orthopaedics, outpatients', 'Useful for consultant secretaries and admissions'),
  ('The Park Hospital', 'Nottinghamshire', 'Nottingham', 'Private Hospital - Circle Health', '0115 966 2000', 'circlehealthgroup.co.uk', 'MRI, CT, surgery, diagnostics, outpatient clinics', 'Private referral and booking route'),
  ('Nottingham University Hospitals Private Pathways', 'Nottinghamshire', 'Nottingham', 'NHS + Private', '0115 924 9924', 'nuh.nhs.uk', 'Specialist consultants, imaging, diagnostics', 'NHS consultant/private route'),
  ('Sherwood Forest Hospitals Private Pathways', 'Nottinghamshire', 'Mansfield', 'NHS + Private', '01623 622515', 'sfh-tr.nhs.uk', 'Diagnostics, imaging, outpatient care', 'Secretary contact pathway'),
  ('Nuffield Health Oxford The Manor', 'Oxfordshire', 'Oxford', 'Private - Nuffield', '01865 307777', 'nuffieldhealth.com', 'Imaging, Surgery, Orthopaedics, Oncology', 'Consultant secretary pathway'),
  ('The New Foscote Hospital', 'Oxfordshire', 'Banbury', 'Private', '01295 252281', 'thefoscotehospital.co.uk', 'Imaging, Surgery, Outpatients', 'Private referrals'),
  ('The Cherwell Hospital', 'Oxfordshire', 'Banbury', 'Private - Ramsay', '01295 755000', 'ramsayhealth.co.uk', 'Diagnostics, Surgery, Outpatients', 'Bookings and admissions'),
  ('Oxford University Hospitals Private Healthcare', 'Oxfordshire', 'Oxford', 'NHS + Private', '01865 221473', 'ouh.nhs.uk', 'Cancer, Cardiac, Neurosurgery, Diagnostics', 'NHS consultant private pathway'),
  ('John Radcliffe Hospital Private Patients', 'Oxfordshire', 'Oxford', 'NHS + Private', '01865 741166', 'ouh.nhs.uk', 'Specialist medicine, imaging, surgery', 'Useful tertiary referrals'),
  ('Churchill Hospital Private Care', 'Oxfordshire', 'Oxford', 'NHS + Private', '01865 741841', 'ouh.nhs.uk', 'Cancer, renal, diagnostics', 'Specialist consultants'),
  ('Rutland Memorial Hospital Pathways', 'Rutland', 'Oakham', 'NHS Pathways', '01572 722552', 'leicspart.nhs.uk', 'Outpatients, diagnostics, community services', 'Useful local routing; private care often via neighbouring counties'),
  ('Leicester / Peterborough Private Referral Routes', 'Rutland', 'Regional links', 'Private Pathways', NULL, NULL, 'Private hospitals accessed nearby', 'Useful for Rutland patient referrals'),
  ('InHealth Rutland Area Diagnostics', 'Rutland', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound options', 'Useful imaging route'),
  ('Nuffield Health Shrewsbury Hospital', 'Shropshire', 'Shrewsbury', 'Private Hospital - Nuffield', '01743 282500', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatients', 'Consultant secretary/admission pathway'),
  ('The Shrewsbury and Telford Hospital Private Pathways', 'Shropshire', 'Shrewsbury/Telford', 'NHS + Private', '01743 261000', 'sath.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS consultant/private route'),
  ('Robert Jones and Agnes Hunt Orthopaedic Hospital Private Care', 'Shropshire', 'Oswestry', 'NHS + Private Specialist', '01691 404000', 'rjah.nhs.uk', 'Orthopaedics, diagnostics, specialist surgery', 'Excellent specialist referral route'),
  ('InHealth Shropshire Diagnostics', 'Shropshire', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound', 'Useful imaging pathway'),
  ('Nuffield Health Taunton Hospital', 'Somerset', 'Taunton', 'Private Hospital - Nuffield', '01823 286991', 'nuffieldhealth.com', 'Outpatients, imaging, diagnostics, surgery, orthopaedics', 'Useful for consultant secretaries, admissions and imaging referrals'),
  ('Circle Bath Hospital', 'Somerset', 'Bath', 'Private Hospital - Circle Health', '01761 422222', 'circlehealthgroup.co.uk', 'MRI, CT, X-ray, surgery, diagnostics, outpatient clinics', 'Useful private referral/admission route'),
  ('Musgrove Park Hospital Private Pathways', 'Somerset', 'Taunton', 'NHS + Private', '01823 333444', 'somersetft.nhs.uk', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant/private route'),
  ('Yeovil District Hospital Private Pathways', 'Somerset', 'Yeovil', 'NHS + Private', '01935 475122', 'somersetft.nhs.uk', 'Outpatients, diagnostics, imaging', 'Useful secretary pathway'),
  ('Thornbury Hospital', 'South Yorkshire', 'Sheffield', 'Private Hospital - Circle Health', '0114 266 1133', 'circlehealthgroup.co.uk', 'Imaging, diagnostics, surgery, orthopaedics, outpatients', 'Consultant secretary and admissions route'),
  ('Claremont Private Hospital', 'South Yorkshire', 'Sheffield', 'Private Hospital', '0114 263 2114', 'claremont-hospital.co.uk', 'MRI, diagnostics, surgery, outpatient services', 'Useful referral and imaging route'),
  ('Sheffield Teaching Hospitals Private Pathways', 'South Yorkshire', 'Sheffield', 'NHS + Private', '0114 243 4343', 'sth.nhs.uk', 'Specialists, imaging, diagnostics, surgery', 'NHS consultant/private pathway'),
  ('Doncaster Royal Infirmary Private Pathways', 'South Yorkshire', 'Doncaster', 'NHS + Private', '01302 366666', 'dbth.nhs.uk', 'Diagnostics, imaging, outpatient specialties', 'Useful secretary route'),
  ('Rowley Hall Hospital', 'Staffordshire', 'Stafford', 'Private Hospital - Ramsay', '01785 238661', 'ramsayhealth.co.uk', 'Surgery, diagnostics, imaging, outpatients', 'Consultant/admission route'),
  ('Nuffield Health North Staffordshire Hospital', 'Staffordshire', 'Newcastle-under-Lyme', 'Private Hospital - Nuffield', '01782 625431', 'nuffieldhealth.com', 'MRI, surgery, diagnostics, orthopaedics', 'Useful consultant pathway'),
  ('Royal Stoke University Hospital Private Pathways', 'Staffordshire', 'Stoke-on-Trent', 'NHS + Private', '01782 715444', 'uhnm.nhs.uk', 'Specialists, imaging, diagnostics', 'NHS consultant/private route'),
  ('County Hospital Stafford Private Pathways', 'Staffordshire', 'Stafford', 'NHS + Private', '01785 257731', 'uhnm.nhs.uk', 'Diagnostics, outpatient services', 'Secretary referral route'),
  ('Nuffield Health Ipswich Hospital', 'Suffolk', 'Ipswich', 'Private Hospital - Nuffield', '01473 279100', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatient clinics', 'Useful consultant secretary route'),
  ('Ipswich Hospital Private Pathways', 'Suffolk', 'Ipswich', 'NHS + Private', '01473 712233', 'esneft.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS consultant pathway'),
  ('West Suffolk Hospital Private Pathways', 'Suffolk', 'Bury St Edmunds', 'NHS + Private', '01284 713000', 'wsh.nhs.uk', 'Outpatients, diagnostics, imaging', 'Useful referral pathway'),
  ('InHealth Suffolk Diagnostics', 'Suffolk', 'Countywide', 'Diagnostics Provider', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound routes', 'Useful imaging contact'),
  ('Nuffield Health Guildford Hospital', 'Surrey', 'Guildford', 'Private Hospital - Nuffield', '01483 555800', 'nuffieldhealth.com', 'Imaging, surgery, oncology, diagnostics, outpatients', 'Consultant secretary/admissions route'),
  ('Mount Alvernia Hospital', 'Surrey', 'Guildford', 'Private Hospital - Circle Health', '01483 570122', 'circlehealthgroup.co.uk', 'MRI, diagnostics, surgery, outpatient care', 'Private referral route'),
  ('Ashtead Hospital', 'Surrey', 'Ashtead', 'Private Hospital - Ramsay', '01372 221400', 'ramsayhealth.co.uk', 'Diagnostics, surgery, orthopaedics, imaging', 'Admissions and consultant route'),
  ('Royal Surrey Private Patient Pathways', 'Surrey', 'Guildford', 'NHS + Private', '01483 571122', 'royalsurrey.nhs.uk', 'Cancer, diagnostics, surgery, specialist consultants', 'NHS private patient route'),
  ('Nuffield Health Newcastle Hospital', 'Tyne and Wear', 'Newcastle', 'Private Hospital - Nuffield', '0191 281 6131', 'nuffieldhealth.com', 'Imaging, diagnostics, surgery, orthopaedics, outpatients', 'Useful consultant secretary and admission route'),
  ('Spire Washington Hospital', 'Tyne and Wear', 'Washington', 'Private Hospital - Spire', '0191 415 1272', 'spirehealthcare.com', 'Diagnostics, scans, surgery, outpatient clinics', 'Useful imaging and referral pathway'),
  ('Freeman Hospital Private Pathways', 'Tyne and Wear', 'Newcastle', 'NHS + Private', '0191 233 6161', 'newcastle-hospitals.nhs.uk', 'Cardiology, transplant, specialist surgery, diagnostics', 'Specialist consultant/private route'),
  ('Royal Victoria Infirmary Private Pathways', 'Tyne and Wear', 'Newcastle', 'NHS + Private', '0191 233 6161', 'newcastle-hospitals.nhs.uk', 'Specialists, imaging, outpatient care', 'Secretary referral route'),
  ('Nuffield Health Warwickshire Hospital', 'Warwickshire', 'Leamington Spa', 'Private Hospital - Nuffield', '01926 427971', 'nuffieldhealth.com', 'Diagnostics, imaging, surgery, outpatients', 'Consultant/admissions pathway'),
  ('The Meriden Hospital', 'Warwickshire', 'Coventry', 'Private Hospital - Circle Health', '02476 647000', 'circlehealthgroup.co.uk', 'MRI, CT, surgery, diagnostics, orthopaedics', 'Useful consultant and imaging route'),
  ('South Warwickshire NHS Private Pathways', 'Warwickshire', 'Warwick', 'NHS + Private', '01926 495321', 'swft.nhs.uk', 'Consultants, diagnostics, imaging', 'NHS/private consultant route'),
  ('George Eliot Hospital Private Pathways', 'Warwickshire', 'Nuneaton', 'NHS + Private', '02476 351351', 'geh.nhs.uk', 'Outpatients, imaging, diagnostics', 'Useful secretary pathway'),
  ('The Priory Hospital Birmingham', 'West Midlands', 'Birmingham', 'Private Hospital - Circle Health', '0121 440 2323', 'circlehealthgroup.co.uk', 'Imaging, surgery, cancer care, diagnostics', 'Large consultant base and admissions route'),
  ('Spire Little Aston Hospital', 'West Midlands', 'Sutton Coldfield', 'Private Hospital - Spire', '0121 353 2444', 'spirehealthcare.com', 'MRI, CT, surgery, outpatients', 'Useful private referral route'),
  ('HCA The Harborne Hospital', 'West Midlands', 'Birmingham', 'Private Hospital - HCA', '0121 468 3000', 'hcahealthcare.co.uk', 'Specialist private care, imaging, surgery, diagnostics', 'Major consultant-led private pathway'),
  ('Queen Elizabeth Hospital Birmingham Private Care', 'West Midlands', 'Birmingham', 'NHS + Private', '0121 371 2000', 'uhb.nhs.uk', 'Specialist surgery, cancer, imaging, diagnostics', 'NHS tertiary consultant pathway'),
  ('Nuffield Health Chichester Hospital', 'West Sussex', 'Chichester', 'Private Hospital - Nuffield', '01243 530600', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatient clinics', 'Consultant secretary route'),
  ('Goring Hall Hospital', 'West Sussex', 'Worthing', 'Private Hospital - Circle Health', '01903 506699', 'circlehealthgroup.co.uk', 'Imaging, diagnostics, surgery, orthopaedics', 'Useful admissions/referral pathway'),
  ('St Richard''s Hospital Private Pathways', 'West Sussex', 'Chichester', 'NHS + Private', '01243 788122', 'uhsussex.nhs.uk', 'Diagnostics, specialists, imaging', 'NHS/private consultant route'),
  ('Worthing Hospital Private Pathways', 'West Sussex', 'Worthing', 'NHS + Private', '01903 205111', 'uhsussex.nhs.uk', 'Outpatients, diagnostics, imaging', 'Secretary contact route'),
  ('Spire Leeds Hospital', 'West Yorkshire', 'Leeds', 'Private Hospital - Spire', '0113 269 3939', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, outpatients', 'Consultant and admissions route'),
  ('Nuffield Health Leeds Hospital', 'West Yorkshire', 'Leeds', 'Private Hospital - Nuffield', '0113 388 2000', 'nuffieldhealth.com', 'MRI, surgery, diagnostics, specialist clinics', 'Useful secretary pathway'),
  ('Leeds Teaching Hospitals Private Pathways', 'West Yorkshire', 'Leeds', 'NHS + Private', '0113 243 3144', 'leedsth.nhs.uk', 'Specialists, imaging, diagnostics, surgery', 'NHS consultant/private route'),
  ('Bradford Teaching Hospitals Private Pathways', 'West Yorkshire', 'Bradford', 'NHS + Private', '01274 542200', 'bradfordhospitals.nhs.uk', 'Diagnostics, imaging, outpatient specialties', 'Useful referral route'),
  ('New Hall Hospital', 'Wiltshire', 'Salisbury', 'Private Hospital - Ramsay', '01722 422333', 'ramsayhealth.co.uk', 'Surgery, diagnostics, imaging, orthopaedics, outpatients', 'Useful for consultant secretaries, referrals and admissions'),
  ('Sulis Hospital Bath', 'Wiltshire / Bath area', 'Bath', 'Independent Hospital', '01761 422288', 'sulishospital.com', 'Diagnostics, surgery, imaging, outpatient clinics', 'Useful regional private pathway'),
  ('Great Western Hospital Private Pathways', 'Wiltshire', 'Swindon', 'NHS + Private', '01793 604020', 'gwh.nhs.uk', 'Consultants, diagnostics, imaging, surgery', 'NHS/private consultant route'),
  ('Salisbury District Hospital Private Pathways', 'Wiltshire', 'Salisbury', 'NHS + Private', '01722 336262', 'salisbury.nhs.uk', 'Specialists, imaging, diagnostics', 'Useful secretary route'),
  ('The Droitwich Spa Hospital', 'Worcestershire', 'Droitwich', 'Private Hospital', '01905 793333', 'bmi/circlehealthgroup.co.uk', 'Surgery, diagnostics, imaging, outpatients', 'Consultant referral and admissions route'),
  ('Spire South Bank Hospital', 'Worcestershire', 'Worcester', 'Private Hospital - Spire', '01905 350003', 'spirehealthcare.com', 'MRI, diagnostics, surgery, outpatient clinics', 'Useful imaging and consultant pathway'),
  ('Worcestershire Royal Hospital Private Pathways', 'Worcestershire', 'Worcester', 'NHS + Private', '01905 763333', 'worcsacute.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS consultant/private route'),
  ('Alexandra Hospital Private Pathways', 'Worcestershire', 'Redditch', 'NHS + Private', '01527 503030', 'worcsacute.nhs.uk', 'Outpatients, imaging, diagnostics', 'Useful referral pathway'),
  ('Ysbyty Gwynedd Private Pathways', 'Anglesey', 'Bangor (regional access)', 'NHS + Private Pathways', '01248 384384', 'bcuhb.nhs.wales', 'Diagnostics, imaging, consultants, outpatient services', 'Main North Wales consultant/referral pathway'),
  ('North Wales private referral routes', 'Anglesey', 'Regional', 'Private Access Route', NULL, NULL, 'Private imaging and consultant services via North Wales providers', 'Useful secretary referral route'),
  ('Princess of Wales Hospital Private Pathways', 'Bridgend', 'Bridgend', 'NHS + Private Pathways', '01656 752752', 'ctmuhb.nhs.wales', 'Diagnostics, imaging, outpatient specialties', 'NHS consultant/private route'),
  ('Nuffield / Cardiff private referral links', 'Bridgend', 'Regional', 'Private Referral Route', NULL, 'nuffieldhealth.com', 'Private diagnostics and consultant pathways nearby', 'Useful regional pathway'),
  ('Ysbyty Ystrad Fawr Pathways', 'Caerphilly', 'Ystrad Mynach', 'NHS Pathways', '01443 802200', 'abuhb.nhs.wales', 'Outpatients, diagnostics, imaging', 'Useful consultant routing'),
  ('South Wales private provider links', 'Caerphilly', 'Regional', 'Private Referral Route', NULL, NULL, 'Private imaging and consultant pathways', 'Use nearby Newport/Cardiff private providers'),
  ('Spire Cardiff Hospital', 'Cardiff', 'Cardiff', 'Private Hospital - Spire', '02920 735515', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, outpatient clinics', 'Consultant secretary/admission pathway'),
  ('Nuffield Health Cardiff Bay Hospital', 'Cardiff', 'Cardiff Bay', 'Private Hospital - Nuffield', '02920 836700', 'nuffieldhealth.com', 'Surgery, diagnostics, imaging, outpatients', 'Useful private referral route'),
  ('University Hospital of Wales Private Pathways', 'Cardiff', 'Cardiff', 'NHS + Private', '02920 747747', 'cavuhb.nhs.wales', 'Specialist medicine, imaging, diagnostics', 'NHS consultant/private route'),
  ('Glangwili Hospital Pathways', 'Carmarthenshire', 'Carmarthen', 'NHS + Private Pathways', '01267 235151', 'hduhb.nhs.wales', 'Diagnostics, imaging, consultants', 'NHS/private consultant route'),
  ('Bronglais Hospital Pathways', 'Ceredigion', 'Aberystwyth', 'NHS + Private Pathways', '01970 623131', 'hduhb.nhs.wales', 'Diagnostics, imaging, outpatient specialties', 'Consultant routing pathway'),
  ('Glan Clwyd Hospital Private Pathways', 'Conwy', 'Bodelwyddan', 'NHS + Private', '01745 583910', 'bcuhb.nhs.wales', 'Specialists, diagnostics, imaging, surgery', 'Consultant secretary pathway'),
  ('North Wales Diagnostic Access', 'Conwy', 'Countywide', 'Diagnostics', '0333 202 0300', 'inhealthgroup.com', 'MRI, CT, ultrasound options', 'Useful imaging route'),
  ('Glan Clwyd Regional Pathways', 'Denbighshire', 'Rhyl area', 'NHS + Private Pathways', '01745 583910', 'bcuhb.nhs.wales', 'Consultants, diagnostics, imaging', 'Useful NHS/private route'),
  ('Deeside Community Hospital Pathways', 'Flintshire', 'Deeside', 'NHS Pathways', '03000 850000', 'bcuhb.nhs.wales', 'Outpatients, diagnostics, community services', 'Regional referral pathway'),
  ('Ysbyty Gwynedd', 'Gwynedd', 'Bangor', 'NHS + Private Pathways', '01248 384384', 'bcuhb.nhs.wales', 'Radiology, diagnostics, surgery, outpatient specialties', 'NHS consultant/private pathway'),
  ('Spire Yale Regional Access', 'Gwynedd', 'North Wales', 'Private Hospital Access', '01978 291306', 'spirehealthcare.com', 'Diagnostics, surgery, imaging', 'Regional private referral option'),
  ('Nevill Hall Hospital Pathways', 'Monmouthshire', 'Abergavenny', 'NHS + Private Pathways', '01873 732732', 'abuhb.nhs.wales', 'Diagnostics, outpatient specialties, imaging', 'NHS consultant route'),
  ('St Joseph''s Hospital Regional Access', 'Monmouthshire', 'Newport area', 'Private Hospital Access', '01633 820300', 'stjosephshospital.co.uk', 'Private surgery, imaging, diagnostics', 'Useful private referral route'),
  ('Neath Port Talbot Hospital Pathways', 'Neath Port Talbot', 'Port Talbot', 'NHS + Private Pathways', '01639 862000', 'sbuhb.nhs.wales', 'Diagnostics, imaging, outpatient services', 'Useful referral route'),
  ('St Joseph''s Hospital', 'Newport', 'Newport', 'Private Hospital', '01633 820300', 'stjosephshospital.co.uk', 'Diagnostics, imaging, surgery, orthopaedics, outpatients', 'Major South Wales private referral route'),
  ('Royal Gwent Hospital Private Pathways', 'Newport', 'Newport', 'NHS + Private', '01633 234234', 'abuhb.nhs.wales', 'Specialists, diagnostics, imaging', 'NHS consultant route'),
  ('Withybush Hospital Private Pathways', 'Pembrokeshire', 'Haverfordwest', 'NHS + Private Pathways', '01437 764545', 'hduhb.nhs.wales', 'Diagnostics, imaging, outpatient specialties', 'NHS consultant route'),
  ('West Wales private referral routes', 'Pembrokeshire', 'Regional', 'Private Pathways', NULL, NULL, 'Private diagnostics and consultant services', 'Use regional private provider access'),
  ('Powys Teaching Health Board Pathways', 'Powys', 'Countywide', 'NHS + Private Pathways', '01874 711661', 'pthb.nhs.wales', 'Diagnostics, outpatient pathways', 'Often linked to neighbouring private hospitals'),
  ('HMT Sancta Maria Hospital', 'Swansea', 'Swansea', 'Private Hospital', '01792 479040', 'hmtsanctamaria.org', 'MRI, CT, diagnostics, surgery, outpatients', 'Useful consultant and imaging pathway'),
  ('Singleton Hospital Private Pathways', 'Swansea', 'Swansea', 'NHS + Private', '01792 205666', 'sbuhb.nhs.wales', 'Specialists, diagnostics, imaging', 'NHS/private route'),
  ('Morriston Hospital Private Pathways', 'Swansea', 'Swansea', 'NHS + Private', '01792 702222', 'sbuhb.nhs.wales', 'Specialist surgery, diagnostics, imaging', 'Consultant pathway'),
  ('Aneurin Bevan Regional Pathways', 'Torfaen', 'Cwmbran area', 'NHS + Private Pathways', '01633 493100', 'abuhb.nhs.wales', 'Specialists, diagnostics, imaging', 'Regional consultant pathway'),
  ('University Hospital Llandough Private Pathways', 'Vale of Glamorgan', 'Llandough', 'NHS + Private', '02920 715171', 'cavuhb.nhs.wales', 'Specialists, diagnostics, imaging', 'Consultant secretary pathway'),
  ('Spire Cardiff Regional Access', 'Vale of Glamorgan', 'Cardiff area', 'Private Hospital Access', '02920 735515', 'spirehealthcare.com', 'Imaging, surgery, diagnostics', 'Regional private referral route'),
  ('Spire Yale Hospital', 'Wrexham', 'Wrexham', 'Private Hospital - Spire', '01978 291306', 'spirehealthcare.com', 'Diagnostics, imaging, surgery, outpatients', 'Useful consultant secretary route'),
  ('Wrexham Maelor Hospital Private Pathways', 'Wrexham', 'Wrexham', 'NHS + Private', '01978 291100', 'bcuhb.nhs.wales', 'Specialists, imaging, diagnostics', 'NHS/private consultant route'),
  ('Albyn Hospital', 'Aberdeen City', 'Aberdeen', 'Private Hospital - Circle Health', '01224 595993', 'circlehealthgroup.co.uk', 'Outpatients, imaging, diagnostics, surgery, orthopaedics', 'Useful for consultant secretaries, admissions and imaging referrals'),
  ('Aberdeen Royal Infirmary Private Pathways', 'Aberdeen City', 'Aberdeen', 'NHS + Private Pathways', '0345 456 6000', 'nhsgrampian.org', 'Specialists, diagnostics, imaging, surgery', 'NHS consultant/private referral route'),
  ('BMI/Circle Aberdeen Diagnostics', 'Aberdeen City', 'Aberdeen', 'Private Diagnostics', '01224 595993', 'circlehealthgroup.co.uk', 'MRI, CT, X-ray, ultrasound', 'Useful radiology pathway'),
  ('NHS Grampian Regional Private Pathways', 'Aberdeenshire', 'Countywide', 'NHS + Private Pathways', '0345 456 6000', 'nhsgrampian.org', 'Consultants, diagnostics, outpatient services', 'Regional consultant secretary route'),
  ('Albyn Hospital Regional Access', 'Aberdeenshire', 'Aberdeen area', 'Private Hospital Access', '01224 595993', 'circlehealthgroup.co.uk', 'Private imaging, surgery, consultant clinics', 'Main private referral option for area'),
  ('Ninewells Hospital Private Pathways', 'Angus', 'Dundee regional access', 'NHS + Private Pathways', '01382 660111', 'nhstayside.scot.nhs.uk', 'Specialists, diagnostics, imaging', 'Regional NHS/private consultant pathway'),
  ('Tayside private referral routes', 'Angus', 'Regional', 'Private Access Route', NULL, NULL, 'Private diagnostics and consultant services nearby', 'Useful referral pathway'),
  ('NHS Highland Argyll & Bute Pathways', 'Argyll and Bute', 'Countywide', 'NHS + Private Pathways', '01463 704000', 'nhshighland.scot.nhs.uk', 'Diagnostics, outpatient services, consultant pathways', 'Regional secretary route'),
  ('Glasgow Private Hospital Referral Routes', 'Argyll and Bute', 'Regional', 'Private Access Route', NULL, NULL, 'Private imaging, consultants and surgery access', 'Often referred to Glasgow private providers'),
  ('Fernbrae Hospital', 'Dundee City', 'Dundee', 'Private Hospital', '01382 549088', 'fern brae hospital / spirehealthcare.com', 'Private surgery, diagnostics, outpatient clinics', 'Useful consultant secretary route'),
  ('Ninewells Hospital Private Pathways', 'Dundee City', 'Dundee', 'NHS + Private Pathways', '01382 660111', 'nhstayside.scot.nhs.uk', 'Specialist medicine, surgery, imaging, diagnostics', 'NHS consultant route'),
  ('University Hospital Crosshouse Private Pathways', 'East Ayrshire', 'Kilmarnock', 'NHS + Private Pathways', '01563 521133', 'nhsaaa.net', 'Diagnostics, imaging, outpatient specialties', 'Consultant/private route'),
  ('East Lothian Community Hospital Pathways', 'East Lothian', 'Haddington', 'NHS Pathways', '0131 536 8300', 'nhslothian.scot', 'Diagnostics, outpatient clinics', 'Regional private referrals via Edinburgh'),
  ('Spire Murrayfield Hospital Edinburgh', 'Edinburgh', 'Edinburgh', 'Private Hospital - Spire', '0131 334 0363', 'spirehealthcare.com', 'MRI, CT, X-ray, diagnostics, surgery, orthopaedics, outpatient clinics', 'Useful consultant secretary route, imaging and admissions'),
  ('The Edinburgh Clinic', 'Edinburgh', 'Edinburgh', 'Private Clinic - Aspen Healthcare', '0131 447 2340', 'edinburghclinic.com', 'Diagnostics, imaging, ophthalmology, outpatient consultants', 'Useful outpatient and scan pathway'),
  ('Royal Infirmary of Edinburgh Private Pathways', 'Edinburgh', 'Edinburgh', 'NHS + Private Pathways', '0131 536 1000', 'nhslothian.scot', 'Specialist medicine, surgery, diagnostics, imaging', 'NHS consultant/private referral route'),
  ('Victoria Hospital Kirkcaldy Private Pathways', 'Fife', 'Kirkcaldy', 'NHS + Private Pathways', '01592 643355', 'nhsfife.org', 'Diagnostics, imaging, outpatient specialties', 'Consultant/private pathway route'),
  ('Spire / Edinburgh Private Referral Links', 'Fife', 'Regional', 'Private Access Route', NULL, NULL, 'Private imaging and consultant services nearby', 'Useful for private referrals'),
  ('Nuffield Health Glasgow Hospital', 'Glasgow City', 'Glasgow', 'Private Hospital - Nuffield', '0141 334 9441', 'nuffieldhealth.com', 'Diagnostics, imaging, surgery, orthopaedics, outpatients', 'Consultant secretaries, admissions and imaging referrals'),
  ('Ross Hall Hospital', 'Glasgow City', 'Glasgow', 'Private Hospital - Circle Health', '0141 810 3151', 'circlehealthgroup.co.uk', 'MRI, CT, diagnostics, cancer care, surgery, outpatient clinics', 'Major private referral hospital'),
  ('Glasgow Royal Infirmary Private Pathways', 'Glasgow City', 'Glasgow', 'NHS + Private Pathways', '0141 211 4000', 'nhsggc.scot', 'Specialists, diagnostics, imaging', 'NHS consultant pathway'),
  ('Raigmore Hospital Private Pathways', 'Highland', 'Inverness', 'NHS + Private Pathways', '01463 704000', 'nhshighland.scot.nhs.uk', 'Consultants, diagnostics, imaging, outpatient specialties', 'Main Highland consultant referral route'),
  ('Kingsmills Hospital Private Healthcare', 'Highland', 'Inverness', 'Private Healthcare', '01463 257000', 'kingsmillshospital.co.uk', 'Private consultants, diagnostics and outpatient services', 'Useful private referral pathway'),
  ('Inverclyde Royal Hospital Private Pathways', 'Inverclyde', 'Greenock', 'NHS + Private Pathways', '01475 633777', 'nhsggc.scot', 'Diagnostics, imaging, outpatient specialties', 'NHS consultant/private route'),
  ('Glasgow private hospital access routes', 'Inverclyde', 'Regional', 'Private Access Route', NULL, NULL, 'Ross Hall/Nuffield Glasgow access', 'Useful nearby private referral pathway'),
  ('Royal Infirmary Edinburgh Regional Access', 'Midlothian', 'Edinburgh area', 'NHS + Private Pathways', '0131 536 1000', 'nhslothian.scot', 'Specialists, diagnostics, imaging', 'Main consultant pathway'),
  ('Western Isles Hospital Pathways', 'Na h-Eileanan Siar', 'Stornoway', 'NHS Pathways', '01851 704704', 'wi h b.scot.nhs.uk', 'Diagnostics, outpatient services', 'Regional specialist referral links'),
  ('Ayrshire Central Hospital Pathways', 'North Ayrshire', 'Irvine', 'NHS Pathways', '01294 274191', 'nhsaaa.net', 'Diagnostics, outpatient services', 'Regional referral route'),
  ('University Hospital Monklands Private Pathways', 'North Lanarkshire', 'Airdrie', 'NHS + Private Pathways', '01236 748748', 'nhslanarkshire.scot.nhs.uk', 'Diagnostics, imaging, specialists', 'Consultant secretary pathway'),
  ('Lanarkshire Private Referral Routes', 'North Lanarkshire', 'Regional', 'Private Access Route', NULL, NULL, 'Glasgow private hospitals and diagnostics', 'Useful private referral option'),
  ('The Balfour Hospital Pathways', 'Orkney Islands', 'Kirkwall', 'NHS Pathways', '01856 888000', 'ohb.scot.nhs.uk', 'Diagnostics, outpatient services', 'Regional specialist referral links'),
  ('Perth Royal Infirmary Private Pathways', 'Perth and Kinross', 'Perth', 'NHS + Private Pathways', '01738 623311', 'nhstayside.scot.nhs.uk', 'Diagnostics, imaging, outpatient specialties', 'Consultant pathway'),
  ('Borders General Hospital Private Pathways', 'Scottish Borders', 'Melrose', 'NHS + Private Pathways', '01896 826000', 'borders.scot.nhs.uk', 'Diagnostics, imaging, outpatient services', 'Consultant secretary route'),
  ('Gilbert Bain Hospital Pathways', 'Shetland Islands', 'Lerwick', 'NHS Pathways', '01595 743000', 'nhsshetland.scot', 'Diagnostics, outpatient services', 'Regional referral route'),
  ('University Hospital Ayr Private Pathways', 'South Ayrshire', 'Ayr', 'NHS + Private Pathways', '01292 610555', 'nhsaaa.net', 'Specialists, imaging, diagnostics', 'NHS consultant pathway'),
  ('University Hospital Hairmyres Private Pathways', 'South Lanarkshire', 'East Kilbride', 'NHS + Private Pathways', '01355 585000', 'nhslanarkshire.scot.nhs.uk', 'Specialists, diagnostics, imaging', 'NHS/private consultant route'),
  ('University Hospital Wishaw Private Pathways', 'South Lanarkshire', 'Wishaw', 'NHS + Private Pathways', '01698 361100', 'nhslanarkshire.scot.nhs.uk', 'Outpatients, imaging, diagnostics', 'Useful secretary route'),
  ('Forth Valley Royal Hospital Private Pathways', 'Stirling', 'Larbert area', 'NHS + Private Pathways', '01324 566000', 'nhsforthvalley.com', 'Specialists, diagnostics, imaging', 'NHS consultant route'),
  ('St John''s Hospital Private Pathways', 'West Lothian', 'Livingston', 'NHS + Private Pathways', '01506 523000', 'nhslothian.scot', 'Diagnostics, imaging, consultants', 'NHS/private consultant route');
