-- Veyn: admin-managed reference data for the Academy spelling search tool
-- (account/spelling-search.html), plus a review queue for secretary-submitted
-- term suggestions. Replaces the static account/spelling-search-data.js file
-- that tool originally shipped with — the table below is now the sole source
-- of truth, seeded with that file's contents.
-- Run this in the Supabase SQL editor.

create table spelling_terms (
  id uuid primary key default gen_random_uuid(),
  term text not null,
  category text not null check (category in ('medication', 'anatomy')),
  phonetic text,
  aliases text[] not null default '{}',
  added_by_profile_id uuid references profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index spelling_terms_term_category_idx on spelling_terms (lower(term), category);

alter table spelling_terms enable row level security;

create policy "Spelling terms are publicly readable"
  on spelling_terms for select using (true);

create policy "Admins can insert spelling terms"
  on spelling_terms for insert with check (is_admin());

create policy "Admins can update spelling terms"
  on spelling_terms for update using (is_admin()) with check (is_admin());

create policy "Admins can delete spelling terms"
  on spelling_terms for delete using (is_admin());

-- Secretary-submitted suggestions for missing/incorrect terms — a review
-- queue, mirroring migration_48_contact_suggestions.sql. Approving one is a
-- manual admin action (add/edit the row in spelling_terms via the admin UI),
-- not an automatic write, so a bad suggestion can never land directly in the
-- publicly-readable table.
create table spelling_term_suggestions (
  id uuid primary key default gen_random_uuid(),
  suggested_term text not null,
  category text check (category in ('medication', 'anatomy')),
  note text,
  submitted_by_profile_id uuid not null references profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'dismissed')),
  admin_notes text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table spelling_term_suggestions enable row level security;

create policy "Users can read their own spelling suggestions"
  on spelling_term_suggestions for select using (auth.uid() = submitted_by_profile_id);

create policy "Admins can read all spelling suggestions"
  on spelling_term_suggestions for select using (is_admin());

create policy "Users can submit spelling suggestions"
  on spelling_term_suggestions for insert with check (auth.uid() = submitted_by_profile_id);

create policy "Admins can update spelling suggestions"
  on spelling_term_suggestions for update using (is_admin());

create policy "Admins can delete spelling suggestions"
  on spelling_term_suggestions for delete using (is_admin());

-- Seed with the tool's 305-term list (179 medications, 126 anatomy terms)
-- covering the specialties in SPECIALTIES/specialties-data.js.
insert into spelling_terms (term, category, phonetic, aliases) values
('Amoxicillin', 'medication', 'a-mox-i-SIL-in', ARRAY['amoxycillin', 'amoxicilin', 'amoxicillan', 'amoxicylin']::text[]),
('Co-amoxiclav', 'medication', 'co-a-MOX-i-clav', ARRAY['coamoxiclav', 'co amoxiclav', 'augmentin']::text[]),
('Flucloxacillin', 'medication', 'floo-clox-a-SIL-in', ARRAY['flucloxacilin', 'floxacillin', 'flucoxacillin']::text[]),
('Erythromycin', 'medication', 'e-rith-ro-MY-sin', ARRAY['errythromycin', 'erythromicin', 'eurythromycin']::text[]),
('Clarithromycin', 'medication', 'cla-rith-ro-MY-sin', ARRAY['clarythromycin', 'claritromycin', 'clarithromicin']::text[]),
('Azithromycin', 'medication', 'a-zith-ro-MY-sin', ARRAY['azythromycin', 'azithromicin', 'azithromyacin']::text[]),
('Doxycycline', 'medication', 'dox-i-SY-kleen', ARRAY['doxycyclin', 'doxicycline', 'doxycyline']::text[]),
('Ciprofloxacin', 'medication', 'sip-ro-FLOX-a-sin', ARRAY['ciproflaxin', 'cyprofloxacin', 'ciprofloxin']::text[]),
('Levofloxacin', 'medication', 'lee-vo-FLOX-a-sin', ARRAY['levofloxin', 'levoflaxacin']::text[]),
('Trimethoprim', 'medication', 'try-METH-o-prim', ARRAY['trimethaprim', 'trimethoprin', 'trimethroprim']::text[]),
('Nitrofurantoin', 'medication', 'ny-tro-fyoor-AN-toyn', ARRAY['nitrofurantoine', 'nitrofuratoin', 'nitrofurantion']::text[]),
('Metronidazole', 'medication', 'met-ro-NY-da-zole', ARRAY['metronidizole', 'metronidasole', 'metronidazol']::text[]),
('Sulfasalazine', 'medication', 'sul-fa-SAL-a-zeen', ARRAY['sulphasalazine', 'sulfasalizine', 'sulfasalazene']::text[]),
('Hydroxychloroquine', 'medication', 'hy-drox-ee-KLOR-o-kwin', ARRAY['hydroxycloroquine', 'hydroxichloroquine', 'hydroxycholoroquine']::text[]),
('Methotrexate', 'medication', 'meth-o-TREX-ate', ARRAY['methotrexat', 'methotrexrate', 'methotrexae']::text[]),
('Azathioprine', 'medication', 'a-za-THY-o-preen', ARRAY['azothioprine', 'azathyoprine', 'azathioprin']::text[]),
('Leflunomide', 'medication', 'le-FLOO-no-mide', ARRAY['leflunimide', 'lefluonamide']::text[]),
('Omeprazole', 'medication', 'oh-MEP-ra-zole', ARRAY['omeprazol', 'omeprozole', 'omeprazoal']::text[]),
('Lansoprazole', 'medication', 'lan-SOP-ra-zole', ARRAY['lanzoprazole', 'lansaprazole', 'lansopazole']::text[]),
('Esomeprazole', 'medication', 'es-oh-MEP-ra-zole', ARRAY['esomeprazol', 'esomaprazole']::text[]),
('Pantoprazole', 'medication', 'pan-TOE-pra-zole', ARRAY['pantoprazol', 'pantroprazole']::text[]),
('Ranitidine', 'medication', 'ra-NIT-i-deen', ARRAY['rantidine', 'ranatidine']::text[]),
('Atorvastatin', 'medication', 'a-TOR-va-sta-tin', ARRAY['atorvostatin', 'atorvastin', 'atorvistatin']::text[]),
('Simvastatin', 'medication', 'sim-va-STA-tin', ARRAY['simvastin', 'simvistatin', 'symvastatin']::text[]),
('Rosuvastatin', 'medication', 'ro-SOO-va-sta-tin', ARRAY['rosuvostatin', 'rosuvastin']::text[]),
('Ezetimibe', 'medication', 'ez-ET-i-mibe', ARRAY['ezetemibe', 'ezetamibe', 'ezetimib']::text[]),
('Bisoprolol', 'medication', 'by-SO-pro-lol', ARRAY['bisoprolal', 'bisopropol', 'bisoprolole']::text[]),
('Atenolol', 'medication', 'a-TEN-o-lol', ARRAY['attenolol', 'atenolal']::text[]),
('Propranolol', 'medication', 'pro-PRAN-o-lol', ARRAY['propanolol', 'propranalol', 'proprananol']::text[]),
('Ramipril', 'medication', 'RAM-i-pril', ARRAY['ramapril', 'rampiril', 'ramipryl']::text[]),
('Lisinopril', 'medication', 'ly-SIN-o-pril', ARRAY['lisinapril', 'lysinopril']::text[]),
('Perindopril', 'medication', 'per-IN-do-pril', ARRAY['perindapril', 'perindopryl']::text[]),
('Losartan', 'medication', 'lo-SAR-tan', ARRAY['lorsartan', 'losarten', 'losertan']::text[]),
('Candesartan', 'medication', 'kan-de-SAR-tan', ARRAY['candersartan', 'candesarten']::text[]),
('Amlodipine', 'medication', 'am-LO-di-peen', ARRAY['amlodapine', 'amlodopine', 'amlodipin']::text[]),
('Felodipine', 'medication', 'fe-LO-di-peen', ARRAY['felodapine', 'felodipin']::text[]),
('Furosemide', 'medication', 'fyoor-OH-se-mide', ARRAY['frusemide', 'furosemid', 'furosamide']::text[]),
('Bendroflumethiazide', 'medication', 'ben-dro-floo-me-THY-a-zide', ARRAY['bendrofluazide', 'bendroflumethazide', 'bendrofluromethiazide']::text[]),
('Spironolactone', 'medication', 'spy-ro-no-LAK-tone', ARRAY['spironolactione', 'spiranolactone', 'spironolacone']::text[]),
('Warfarin', 'medication', 'WAR-fa-rin', ARRAY['warfarrin', 'warfarine']::text[]),
('Rivaroxaban', 'medication', 'riv-a-ROX-a-ban', ARRAY['rivaroxiban', 'rivaraxoban', 'rivoraxaban']::text[]),
('Apixaban', 'medication', 'a-PIX-a-ban', ARRAY['apixiban', 'apixaben']::text[]),
('Dabigatran', 'medication', 'da-BIG-a-tran', ARRAY['dabigatren', 'dabigitran']::text[]),
('Edoxaban', 'medication', 'e-DOX-a-ban', ARRAY['edoxiban', 'edoxaben']::text[]),
('Clopidogrel', 'medication', 'clo-PID-o-grel', ARRAY['clopidogral', 'clopidegrel', 'clopidogrell']::text[]),
('Prasugrel', 'medication', 'PRA-soo-grel', ARRAY['prasugral', 'prasugrell']::text[]),
('Ticagrelor', 'medication', 'ty-KA-gre-lor', ARRAY['ticagrelar', 'ticagrelol']::text[]),
('Levothyroxine', 'medication', 'lee-vo-thy-ROX-een', ARRAY['levothyroxin', 'levothroxine', 'levothyroxene']::text[]),
('Carbimazole', 'medication', 'kar-BIM-a-zole', ARRAY['carbimazol', 'carbamizole']::text[]),
('Metformin', 'medication', 'met-FOR-min', ARRAY['metaformin', 'metphormin', 'metformine']::text[]),
('Gliclazide', 'medication', 'GLIK-la-zide', ARRAY['glyclazide', 'gliclazid']::text[]),
('Sitagliptin', 'medication', 'sit-a-GLIP-tin', ARRAY['sitagliptan', 'sitagluptin']::text[]),
('Empagliflozin', 'medication', 'em-pa-gli-FLOW-zin', ARRAY['empagliflozen', 'empaglifozin']::text[]),
('Dapagliflozin', 'medication', 'dap-a-gli-FLOW-zin', ARRAY['dapagliflozen', 'dapaglifozin']::text[]),
('Pioglitazone', 'medication', 'py-o-GLIT-a-zone', ARRAY['pioglitazon', 'pioglitizone']::text[]),
('Sertraline', 'medication', 'SER-tra-leen', ARRAY['sertaline', 'seteraline', 'sertralene']::text[]),
('Citalopram', 'medication', 'sy-TAL-o-pram', ARRAY['cetalopram', 'citaloprum', 'citalapram']::text[]),
('Escitalopram', 'medication', 'es-sy-TAL-o-pram', ARRAY['escitaloprum', 'escitalapram']::text[]),
('Fluoxetine', 'medication', 'floo-OX-e-teen', ARRAY['fluoxitine', 'fluoxatine', 'fluoxetin']::text[]),
('Paroxetine', 'medication', 'pa-ROX-e-teen', ARRAY['paroxatine', 'paroxitine']::text[]),
('Venlafaxine', 'medication', 'ven-la-FAX-een', ARRAY['venlafaxin', 'venlafaxene', 'venlaflaxine']::text[]),
('Duloxetine', 'medication', 'doo-LOX-e-teen', ARRAY['deloxetine', 'duloxatine']::text[]),
('Mirtazapine', 'medication', 'mir-TAZ-a-peen', ARRAY['mirtazepine', 'mertazapine', 'mirtazapin']::text[]),
('Amitriptyline', 'medication', 'am-i-TRIP-ti-leen', ARRAY['amitryptiline', 'amytriptiline', 'amitriptalin']::text[]),
('Quetiapine', 'medication', 'kwe-TY-a-peen', ARRAY['quitiapine', 'ketiapine', 'quetiapin']::text[]),
('Olanzapine', 'medication', 'oh-LAN-za-peen', ARRAY['olanzepine', 'olanzapin']::text[]),
('Risperidone', 'medication', 'ris-PER-i-done', ARRAY['risperdone', 'risperidon']::text[]),
('Aripiprazole', 'medication', 'a-ri-PIP-ra-zole', ARRAY['ariprazole', 'aripiprazol', 'aripiprizole']::text[]),
('Lamotrigine', 'medication', 'la-MOT-ri-jeen', ARRAY['lamotragine', 'lamitrigine', 'lamotrigene']::text[]),
('Levetiracetam', 'medication', 'lee-ve-tye-RASS-e-tam', ARRAY['leviteracetam', 'levetiracitam', 'levotiracetam']::text[]),
('Phenytoin', 'medication', 'FEN-i-toyn', ARRAY['phenetoin', 'phenytoine']::text[]),
('Carbamazepine', 'medication', 'kar-ba-MAZ-e-peen', ARRAY['carbemazepine', 'carbamezapine', 'carbamazapine']::text[]),
('Sodium valproate', 'medication', 'VAL-pro-ate', ARRAY['valproate', 'valproat', 'sodium valproat']::text[]),
('Pregabalin', 'medication', 'pre-GAB-a-lin', ARRAY['pregabaline', 'pregablin', 'pregabilin']::text[]),
('Gabapentin', 'medication', 'ga-ba-PEN-tin', ARRAY['gabapentine', 'gabapenten']::text[]),
('Baclofen', 'medication', 'BAK-lo-fen', ARRAY['baclophen', 'baclafen']::text[]),
('Tramadol', 'medication', 'TRAM-a-dol', ARRAY['tramadal', 'tramadole']::text[]),
('Co-codamol', 'medication', 'co-CO-da-mol', ARRAY['cocodamol', 'co codamol']::text[]),
('Oxycodone', 'medication', 'ox-i-CO-done', ARRAY['oxycodeine', 'oxicodone', 'oxycodine']::text[]),
('Buprenorphine', 'medication', 'byoo-pre-NOR-feen', ARRAY['buprenorphene', 'buprenorphin', 'buprenorfine']::text[]),
('Naproxen', 'medication', 'na-PROX-en', ARRAY['naproxin', 'naproxem']::text[]),
('Diclofenac', 'medication', 'dy-KLOF-en-ak', ARRAY['diclofenic', 'diclofenak']::text[]),
('Prednisolone', 'medication', 'pred-NIS-o-lone', ARRAY['prednisolon', 'prednisilone', 'prednislone']::text[]),
('Salbutamol', 'medication', 'sal-BYOO-ta-mol', ARRAY['salbutemol', 'salbutamal']::text[]),
('Beclometasone', 'medication', 'be-clo-MET-a-zone', ARRAY['beclomethasone', 'beclametasone', 'becolmetasone']::text[]),
('Tiotropium', 'medication', 'ty-o-TRO-pee-um', ARRAY['tiotropiam', 'tiotropum']::text[]),
('Montelukast', 'medication', 'mon-te-LOO-kast', ARRAY['montelucast', 'monteleukast']::text[]),
('Tamsulosin', 'medication', 'tam-SOO-lo-sin', ARRAY['tamsulocin', 'tansulosin', 'tamsulosine']::text[]),
('Finasteride', 'medication', 'fi-NAS-te-ride', ARRAY['finastride', 'finasteroid']::text[]),
('Solifenacin', 'medication', 'sol-i-FEN-a-sin', ARRAY['solifenacine', 'solefenacin']::text[]),
('Diazepam', 'medication', 'dy-AZ-e-pam', ARRAY['diazapam', 'diazepan']::text[]),
('Zopiclone', 'medication', 'ZOH-pi-klone', ARRAY['zoplicone', 'zopicone']::text[]),
('Adalimumab', 'medication', 'a-da-LIM-yoo-mab', ARRAY['adalimumumab', 'adilimumab']::text[]),
('Etanercept', 'medication', 'e-ta-NER-sept', ARRAY['etanacept', 'etanercep']::text[]),
('Infliximab', 'medication', 'in-FLIX-i-mab', ARRAY['inflicksimab', 'infliximumab']::text[]),
('Rituximab', 'medication', 'ri-TUX-i-mab', ARRAY['rituxamab', 'rituximumab']::text[]),
('Tocilizumab', 'medication', 'toe-si-LIZ-oo-mab', ARRAY['tocilzumab', 'tosilizumab']::text[]),
('Denosumab', 'medication', 'den-OH-soo-mab', ARRAY['denosumumab', 'denosumab injection']::text[]),
('Alendronic acid', 'medication', 'a-len-DRON-ik', ARRAY['alendronate', 'alendronic assid', 'alendronic']::text[]),
('Risedronate', 'medication', 'ri-SED-ro-nate', ARRAY['risedranate', 'risedronat']::text[]),
('Zoledronic acid', 'medication', 'zo-le-DRON-ik', ARRAY['zolendronic acid', 'zoledronic assid']::text[]),
('Colchicine', 'medication', 'KOL-chi-seen', ARRAY['colchacine', 'colcichine', 'colchecine']::text[]),
('Allopurinol', 'medication', 'al-o-PYOOR-i-nol', ARRAY['alopurinol', 'allopurinal']::text[]),
('Febuxostat', 'medication', 'fe-BUX-o-stat', ARRAY['febuxastat', 'febuxostate']::text[]),
('Hydrocortisone', 'medication', 'hy-dro-KOR-ti-zone', ARRAY['hydrocortizone', 'hydrocotisone']::text[]),
('Dexamethasone', 'medication', 'dex-a-METH-a-zone', ARRAY['dexamethasome', 'dexametazone', 'dexamethesone']::text[]),
('Fludrocortisone', 'medication', 'floo-dro-KOR-ti-zone', ARRAY['fludrocortizone', 'fludrocotisone']::text[]),
('Desmopressin', 'medication', 'des-mo-PRESS-in', ARRAY['desmopressen', 'desmopresin']::text[]),
('Oxybutynin', 'medication', 'ox-i-BYOO-ti-nin', ARRAY['oxybutinin', 'oxibutynin']::text[]),
('Dutasteride', 'medication', 'doo-TAS-te-ride', ARRAY['dutastride', 'dutasteroid']::text[]),
('Doxazosin', 'medication', 'dox-AY-zo-sin', ARRAY['doxazocin', 'doxazosine']::text[]),
('Tadalafil', 'medication', 'ta-DAL-a-fil', ARRAY['tadalifil', 'tadalafill']::text[]),
('Clomifene', 'medication', 'KLOM-i-feen', ARRAY['clomiphene', 'clomid']::text[]),
('Letrozole', 'medication', 'LET-ro-zole', ARRAY['letrazole', 'letrozol']::text[]),
('Goserelin', 'medication', 'GO-se-re-lin', ARRAY['gosarelin', 'goserelen']::text[]),
('Leuprorelin', 'medication', 'loo-pro-REL-in', ARRAY['leuporelin', 'leuprorelen']::text[]),
('Tamoxifen', 'medication', 'ta-MOX-i-fen', ARRAY['tamoxafen', 'tamoxefen']::text[]),
('Anastrozole', 'medication', 'a-NAS-tro-zole', ARRAY['anastrazole', 'anastrozol']::text[]),
('Exemestane', 'medication', 'ex-e-MES-tane', ARRAY['exemestame', 'exemestain']::text[]),
('Capecitabine', 'medication', 'ka-pe-SY-ta-been', ARRAY['capcitabine', 'capecitabin']::text[]),
('Cyclophosphamide', 'medication', 'sy-clo-FOS-fa-mide', ARRAY['ciclophosphamide', 'cyclophosphomide', 'cyclophosphamid']::text[]),
('Docetaxel', 'medication', 'do-se-TAX-el', ARRAY['docetaxol', 'docetaxal']::text[]),
('Paclitaxel', 'medication', 'pak-li-TAX-el', ARRAY['paclitaxal', 'paclitaxol']::text[]),
('Bevacizumab', 'medication', 'be-va-SIZ-oo-mab', ARRAY['bevacisumab', 'bevacizumumab']::text[]),
('Trastuzumab', 'medication', 'tras-TOO-zoo-mab', ARRAY['trastuzimab', 'herceptin']::text[]),
('Pembrolizumab', 'medication', 'pem-bro-LIZ-oo-mab', ARRAY['pembrolzumab', 'pembroluzimab']::text[]),
('Nivolumab', 'medication', 'ni-VOL-oo-mab', ARRAY['nivolumumab', 'nivolumab injection']::text[]),
('Isotretinoin', 'medication', 'eye-so-TRET-i-noyn', ARRAY['isotretenoin', 'isotretinoine', 'roaccutane']::text[]),
('Adapalene', 'medication', 'a-DAP-a-leen', ARRAY['adapaline', 'adapalen']::text[]),
('Tretinoin', 'medication', 'TRET-i-noyn', ARRAY['tretinoine', 'tretinoin cream']::text[]),
('Terbinafine', 'medication', 'ter-BIN-a-feen', ARRAY['terbenafine', 'terbinifine']::text[]),
('Fluconazole', 'medication', 'floo-CON-a-zole', ARRAY['flucanazole', 'fluconazol']::text[]),
('Clotrimazole', 'medication', 'klo-TRIM-a-zole', ARRAY['clotrimazol', 'clotrimizole']::text[]),
('Aciclovir', 'medication', 'ay-SY-clo-veer', ARRAY['acyclovir', 'aciclovair', 'aciclovar']::text[]),
('Valaciclovir', 'medication', 'val-ay-SY-clo-veer', ARRAY['valacyclovir', 'valaciclovar']::text[]),
('Famciclovir', 'medication', 'fam-SY-clo-veer', ARRAY['famcyclovir', 'famciclovar']::text[]),
('Oseltamivir', 'medication', 'os-el-TAM-i-veer', ARRAY['oseltamavir', 'tamiflu']::text[]),
('Co-trimoxazole', 'medication', 'co-try-MOX-a-zole', ARRAY['cotrimoxazole', 'co trimoxazole']::text[]),
('Vancomycin', 'medication', 'van-co-MY-sin', ARRAY['vancomicin', 'vancomyacin']::text[]),
('Gentamicin', 'medication', 'jen-ta-MY-sin', ARRAY['gentamycin', 'gentamicine']::text[]),
('Teicoplanin', 'medication', 'ty-co-PLAN-in', ARRAY['tecoplanin', 'teicoplanine']::text[]),
('Piperacillin-tazobactam', 'medication', 'py-per-a-SIL-in taz-o-BAK-tam', ARRAY['tazocin', 'piperacillin tazobactam']::text[]),
('Meropenem', 'medication', 'me-ro-PEN-em', ARRAY['meropenam', 'meropenim']::text[]),
('Linezolid', 'medication', 'li-NEZ-o-lid', ARRAY['linezolide', 'linazolid']::text[]),
('Rifampicin', 'medication', 'ri-FAM-pi-sin', ARRAY['rifampin', 'rifampicine']::text[]),
('Isoniazid', 'medication', 'eye-so-NY-a-zid', ARRAY['isoniazide', 'isoniazyd']::text[]),
('Pyrazinamide', 'medication', 'py-ra-ZIN-a-mide', ARRAY['pyrazinamid', 'pirazinamide']::text[]),
('Ethambutol', 'medication', 'e-THAM-byoo-tol', ARRAY['ethambutal', 'ethambutol tablets']::text[]),
('Budesonide', 'medication', 'byoo-DES-o-nide', ARRAY['budesomide', 'budesenide']::text[]),
('Fluticasone', 'medication', 'floo-TIK-a-zone', ARRAY['fluticasome', 'fluticazone']::text[]),
('Mometasone', 'medication', 'mo-MET-a-zone', ARRAY['mometasome', 'mometazone']::text[]),
('Ipratropium', 'medication', 'ip-ra-TRO-pee-um', ARRAY['ipratropiam', 'ipratropium bromide']::text[]),
('Formoterol', 'medication', 'for-MOH-te-rol', ARRAY['formaterol', 'formeterol']::text[]),
('Theophylline', 'medication', 'thee-OFF-i-lin', ARRAY['theophyline', 'theophylin']::text[]),
('Cetirizine', 'medication', 'se-TEER-i-zeen', ARRAY['cetrizine', 'cetirazine']::text[]),
('Loratadine', 'medication', 'lo-RAT-a-deen', ARRAY['loratidine', 'loratadene']::text[]),
('Fexofenadine', 'medication', 'fex-o-FEN-a-deen', ARRAY['fexofenadin', 'fexofenidine']::text[]),
('Chlorphenamine', 'medication', 'klor-FEN-a-meen', ARRAY['chlorpheniramine', 'chlorphenimine']::text[]),
('Domperidone', 'medication', 'dom-PER-i-done', ARRAY['domperidome', 'domperidon']::text[]),
('Metoclopramide', 'medication', 'met-o-KLO-pra-mide', ARRAY['metaclopramide', 'metoclopramid']::text[]),
('Ondansetron', 'medication', 'on-DAN-se-tron', ARRAY['odansetron', 'ondansatron']::text[]),
('Cyclizine', 'medication', 'SY-kli-zeen', ARRAY['cyclazine', 'ciclizine']::text[]),
('Loperamide', 'medication', 'lo-PER-a-mide', ARRAY['loperimide', 'loperamid']::text[]),
('Mesalazine', 'medication', 'me-SAL-a-zeen', ARRAY['mesalazime', 'mesalamine']::text[]),
('Lactulose', 'medication', 'LAK-tyoo-lose', ARRAY['lactolose', 'lactulos']::text[]),
('Macrogol', 'medication', 'MAK-ro-gol', ARRAY['macragol', 'movicol']::text[]),
('Docusate sodium', 'medication', 'DOK-yoo-sate', ARRAY['docusate', 'docusate sodum']::text[]),
('Ferrous fumarate', 'medication', 'FER-us FYOO-ma-rate', ARRAY['ferous fumarate', 'ferrous fumerate']::text[]),
('Ferrous sulfate', 'medication', 'FER-us SUL-fate', ARRAY['ferous sulphate', 'ferrous sulphate']::text[]),
('Cyanocobalamin', 'medication', 'sy-an-o-co-BAL-a-min', ARRAY['cyanocobalamine', 'b12 injection']::text[]),
('Cholecalciferol', 'medication', 'ko-le-kal-SIF-er-ol', ARRAY['colecalciferol', 'cholecalciferal', 'vitamin d3']::text[]),
('Alfacalcidol', 'medication', 'al-fa-KAL-si-dol', ARRAY['alphacalcidol', 'alfacalcidal']::text[]),
('Hydroxyzine', 'medication', 'hy-DROX-i-zeen', ARRAY['hydroxazine', 'hidroxyzine']::text[]),
('Propofol', 'medication', 'PRO-po-fol', ARRAY['propafol', 'propafol']::text[]),
('Midazolam', 'medication', 'mi-DAZ-o-lam', ARRAY['midazolan', 'midazalam']::text[]),
('Dihydrocodeine', 'medication', 'dy-hy-dro-CO-deen', ARRAY['dihydracodeine', 'dihydrocodine']::text[]),
('Meloxicam', 'medication', 'me-LOX-i-kam', ARRAY['meloxecam', 'meloxycam']::text[]),
('Etoricoxib', 'medication', 'e-tor-i-COX-ib', ARRAY['etoricoxeb', 'etoricoxib tablets']::text[]),
('Celecoxib', 'medication', 'se-le-COX-ib', ARRAY['celecoxeb', 'celecoxib capsule']::text[]),
('Oesophagus', 'anatomy', 'ee-SOF-a-gus', ARRAY['esophagus', 'oesophogus', 'esophaghus']::text[]),
('Duodenum', 'anatomy', 'dew-o-DEE-num', ARRAY['duedenum', 'dudenum', 'duodenem']::text[]),
('Jejunum', 'anatomy', 'je-JOO-num', ARRAY['jejenum', 'jejunem']::text[]),
('Ileum', 'anatomy', 'IL-ee-um', ARRAY['illeum', 'ilium (small bowel)', 'ileum bowel']::text[]),
('Ilium', 'anatomy', 'IL-ee-um', ARRAY['ileum (hip bone)', 'illium']::text[]),
('Pancreas', 'anatomy', 'PAN-kree-as', ARRAY['pancreass', 'pancrease', 'pancrous']::text[]),
('Gallbladder', 'anatomy', 'GAWL-blad-er', ARRAY['gall bladder', 'gaulbladder']::text[]),
('Diaphragm', 'anatomy', 'DY-a-fram', ARRAY['diaphram', 'diaphragmn']::text[]),
('Peritoneum', 'anatomy', 'pe-ri-to-NEE-um', ARRAY['peritonium', 'peritoneam']::text[]),
('Mesentery', 'anatomy', 'MES-en-ter-ee', ARRAY['mesentary', 'mesentry']::text[]),
('Appendix', 'anatomy', 'a-PEN-dix', ARRAY['apendix', 'appendex']::text[]),
('Caecum', 'anatomy', 'SEE-kum', ARRAY['cecum', 'ceacum']::text[]),
('Sigmoid colon', 'anatomy', 'SIG-moyd', ARRAY['sigmiod colon', 'sigmoyd colon']::text[]),
('Sternum', 'anatomy', 'STER-num', ARRAY['sternem', 'sturnum']::text[]),
('Clavicle', 'anatomy', 'KLAV-i-kul', ARRAY['clavical', 'clavicel']::text[]),
('Scapula', 'anatomy', 'SKAP-yoo-la', ARRAY['scapular', 'scapla']::text[]),
('Humerus', 'anatomy', 'HYOO-mer-us', ARRAY['humorous', 'humerous']::text[]),
('Ulna', 'anatomy', 'UL-na', ARRAY['ullna', 'ulnar bone']::text[]),
('Carpals', 'anatomy', 'KAR-pulz', ARRAY['carpels', 'carples']::text[]),
('Metacarpals', 'anatomy', 'met-a-KAR-pulz', ARRAY['metacarpels', 'metacarples']::text[]),
('Phalanges', 'anatomy', 'fa-LAN-jeez', ARRAY['phalanges (fingers)', 'phalangies', 'phalanx (singular)']::text[]),
('Patella', 'anatomy', 'pa-TEL-a', ARRAY['patela', 'patellar bone']::text[]),
('Fibula', 'anatomy', 'FIB-yoo-la', ARRAY['fibulla', 'fibia']::text[]),
('Calcaneus', 'anatomy', 'kal-KAY-nee-us', ARRAY['calcaneous', 'calcanius']::text[]),
('Vertebrae', 'anatomy', 'VER-te-bray', ARRAY['vertebre', 'vertabrae', 'verterbrae']::text[]),
('Coccyx', 'anatomy', 'KOK-siks', ARRAY['coxxyx', 'coccix', 'coccyx bone']::text[]),
('Sacrum', 'anatomy', 'SAY-krum', ARRAY['sacreum', 'saccrum']::text[]),
('Larynx', 'anatomy', 'LA-rinks', ARRAY['larnyx', 'larinx']::text[]),
('Pharynx', 'anatomy', 'FA-rinks', ARRAY['pharnyx', 'farinx']::text[]),
('Trachea', 'anatomy', 'TRAY-kee-a', ARRAY['trachia', 'trakea']::text[]),
('Bronchus', 'anatomy', 'BRONG-kus', ARRAY['bronchi (plural)', 'bronchous', 'bronkus']::text[]),
('Alveoli', 'anatomy', 'al-VEE-o-ly', ARRAY['alveolli', 'alveoly']::text[]),
('Pleura', 'anatomy', 'PLOOR-a', ARRAY['plura', 'pleurra']::text[]),
('Mediastinum', 'anatomy', 'mee-dee-a-STY-num', ARRAY['medastinum', 'mediastenum']::text[]),
('Myocardium', 'anatomy', 'my-o-KAR-dee-um', ARRAY['myocardum', 'myocardeum']::text[]),
('Pericardium', 'anatomy', 'pe-ri-KAR-dee-um', ARRAY['pericardum', 'pericardeum']::text[]),
('Aorta', 'anatomy', 'ay-OR-ta', ARRAY['aortia', 'aorta artery']::text[]),
('Ureter', 'anatomy', 'yoo-REE-ter', ARRAY['uretor', 'ureater']::text[]),
('Urethra', 'anatomy', 'yoo-REE-thra', ARRAY['urethera', 'urethra tube']::text[]),
('Prostate', 'anatomy', 'PROS-tate', ARRAY['prostrate', 'prostate gland']::text[]),
('Epididymis', 'anatomy', 'ep-i-DID-i-mis', ARRAY['epidydimis', 'epididimis']::text[]),
('Vas deferens', 'anatomy', 'vas DEF-er-enz', ARRAY['vas deferens tube', 'vaz deferens']::text[]),
('Fallopian tubes', 'anatomy', 'fa-LOH-pee-an', ARRAY['falopian tubes', 'fallopion tubes']::text[]),
('Cervix', 'anatomy', 'SER-viks', ARRAY['cervics', 'servix']::text[]),
('Perineum', 'anatomy', 'pe-ri-NEE-um', ARRAY['perinium', 'perineam']::text[]),
('Hypothalamus', 'anatomy', 'hy-po-THAL-a-mus', ARRAY['hypothalmus', 'hypothalamis']::text[]),
('Pituitary gland', 'anatomy', 'pi-TYOO-i-ta-ree', ARRAY['pitutary gland', 'pituatary gland']::text[]),
('Cerebellum', 'anatomy', 'se-re-BEL-um', ARRAY['cerebelum', 'cerebellem']::text[]),
('Medulla oblongata', 'anatomy', 'me-DUL-a ob-long-GAH-ta', ARRAY['medula oblongata', 'medulla oblongota']::text[]),
('Meninges', 'anatomy', 'me-NIN-jeez', ARRAY['meningies', 'meninges membrane']::text[]),
('Hippocampus', 'anatomy', 'hip-o-KAM-pus', ARRAY['hippocampas', 'hipocampus']::text[]),
('Sclera', 'anatomy', 'SKLEE-ra', ARRAY['sclerra', 'sclira']::text[]),
('Choroid', 'anatomy', 'KOR-oyd', ARRAY['choriod', 'choroyd']::text[]),
('Conjunctiva', 'anatomy', 'kon-junk-TY-va', ARRAY['conjuctiva', 'conjunctivia']::text[]),
('Lacrimal gland', 'anatomy', 'LAK-ri-mal', ARRAY['lachrymal gland', 'lacrymal gland']::text[]),
('Tympanic membrane', 'anatomy', 'tim-PAN-ik', ARRAY['timpanic membrane', 'tympanic membrain']::text[]),
('Cochlea', 'anatomy', 'KOK-lee-a', ARRAY['cochlear', 'cocklea']::text[]),
('Vestibule', 'anatomy', 'VES-ti-byool', ARRAY['vestibul', 'vestable']::text[]),
('Mandible', 'anatomy', 'MAN-di-bul', ARRAY['mandable', 'mandiple']::text[]),
('Maxilla', 'anatomy', 'mak-SIL-a', ARRAY['maxila', 'maxillar']::text[]),
('Zygomatic bone', 'anatomy', 'zy-go-MAT-ik', ARRAY['zigomatic bone', 'zygomattic bone']::text[]),
('Sphenoid bone', 'anatomy', 'SFEE-noyd', ARRAY['spheniod bone', 'sfenoid bone']::text[]),
('Ethmoid bone', 'anatomy', 'ETH-moyd', ARRAY['ethmiod bone', 'ethmoyd bone']::text[]),
('Scrotum', 'anatomy', 'SKRO-tum', ARRAY['scrotem', 'scrotom']::text[]),
('Spleen', 'anatomy', 'spleen', ARRAY['splean', 'spleene']::text[]),
('Achilles tendon', 'anatomy', 'a-KIL-eez', ARRAY['achillies tendon', 'achiles tendon']::text[]),
('Meniscus', 'anatomy', 'me-NIS-kus', ARRAY['meniscis', 'menisci (plural)', 'menicus']::text[]),
('Acromioclavicular joint', 'anatomy', 'a-kro-mee-o-kla-VIK-yoo-lar', ARRAY['ac joint', 'acromioclavicula joint']::text[]),
('Gluteus maximus', 'anatomy', 'GLOO-tee-us MAX-i-mus', ARRAY['gluteous maximus', 'glutius maximus']::text[]),
('Trapezius', 'anatomy', 'tra-PEE-zee-us', ARRAY['trapezuis', 'trapezious']::text[]),
('Latissimus dorsi', 'anatomy', 'la-TIS-i-mus DOR-sy', ARRAY['latismus dorsi', 'latissimus dorsai']::text[]),
('Sternocleidomastoid', 'anatomy', 'ster-no-kly-do-MAS-toyd', ARRAY['sternocleidomastoid muscle', 'sterno-cleido-mastoid']::text[]),
('Quadriceps', 'anatomy', 'KWOD-ri-seps', ARRAY['quadracepts', 'quadricepts']::text[]),
('Mastoid process', 'anatomy', 'MAS-toyd', ARRAY['mastiod process', 'mastoyd process']::text[]),
('Eustachian tube', 'anatomy', 'yoo-STAY-shun', ARRAY['eustacian tube', 'eustachian toob']::text[]),
('Turbinates', 'anatomy', 'TER-bi-nates', ARRAY['turbinates (nose)', 'turbinites']::text[]),
('Nasal septum', 'anatomy', 'NAY-zal SEP-tum', ARRAY['nasel septum', 'nasal septem']::text[]),
('Tonsils', 'anatomy', 'TON-silz', ARRAY['tonsills', 'tonsals']::text[]),
('Adenoids', 'anatomy', 'AD-e-noydz', ARRAY['adnoids', 'adenoyds']::text[]),
('Maxillary sinus', 'anatomy', 'MAX-i-lar-ee', ARRAY['maxilary sinus', 'maxillery sinus']::text[]),
('Ethmoidal sinus', 'anatomy', 'eth-MOY-dal', ARRAY['ethmoydal sinus', 'ethmoidal sinuses']::text[]),
('Sphenoidal sinus', 'anatomy', 'sfe-NOY-dal', ARRAY['sphenoydal sinus', 'sfenoidal sinus']::text[]),
('Macula', 'anatomy', 'MAK-yoo-la', ARRAY['macular', 'makula']::text[]),
('Fovea', 'anatomy', 'FOH-vee-a', ARRAY['fovia', 'foveah']::text[]),
('Vitreous humour', 'anatomy', 'VIT-ree-us', ARRAY['vitrious humour', 'vitreous humor']::text[]),
('Aqueous humour', 'anatomy', 'AY-kwee-us', ARRAY['aquious humour', 'aqueous humor']::text[]),
('Ciliary body', 'anatomy', 'SIL-ee-a-ree', ARRAY['cilary body', 'cillary body']::text[]),
('Optic nerve', 'anatomy', 'OP-tik', ARRAY['optick nerve', 'optic nerv']::text[]),
('Acetabulum', 'anatomy', 'as-e-TAB-yoo-lum', ARRAY['acetabalum', 'acetabullum']::text[]),
('Glenoid cavity', 'anatomy', 'GLEE-noyd', ARRAY['glenoyd cavity', 'glenoid fossa']::text[]),
('Olecranon', 'anatomy', 'oh-LEK-ra-non', ARRAY['olecranon process', 'olecranan']::text[]),
('Malleolus', 'anatomy', 'ma-LEE-o-lus', ARRAY['maleolus', 'malleolous']::text[]),
('Subscapularis', 'anatomy', 'sub-skap-yoo-LAIR-is', ARRAY['sub scapularis', 'subscapularus']::text[]),
('Supraspinatus', 'anatomy', 'soo-pra-spy-NAY-tus', ARRAY['supra spinatus', 'supraspinatis']::text[]),
('Infraspinatus', 'anatomy', 'in-fra-spy-NAY-tus', ARRAY['infra spinatus', 'infraspinatis']::text[]),
('Iliotibial band', 'anatomy', 'il-ee-o-TIB-ee-al', ARRAY['ilio-tibial band', 'itb']::text[]),
('Plantar fascia', 'anatomy', 'PLAN-tar FASH-ee-a', ARRAY['plantar fascha', 'planter fascia']::text[]),
('Endometrium', 'anatomy', 'en-do-MEE-tree-um', ARRAY['endometreum', 'endomitrium']::text[]),
('Myometrium', 'anatomy', 'my-o-MEE-tree-um', ARRAY['myometreum', 'myomitrium']::text[]),
('Labia majora', 'anatomy', 'LAY-bee-a ma-JOR-a', ARRAY['labia major', 'labia majorah']::text[]),
('Labia minora', 'anatomy', 'LAY-bee-a mi-NOR-a', ARRAY['labia minor', 'labia minorah']::text[]),
('Bartholin''s glands', 'anatomy', 'BAR-toh-linz', ARRAY['bartholins glands', 'bartholin glands']::text[]),
('Dermis', 'anatomy', 'DER-mis', ARRAY['dermiss', 'dermus']::text[]),
('Epidermis', 'anatomy', 'ep-i-DER-mis', ARRAY['epidermiss', 'epidurmis']::text[]),
('Subcutis', 'anatomy', 'sub-KYOO-tis', ARRAY['subcutus', 'hypodermis']::text[]),
('Sebaceous glands', 'anatomy', 'se-BAY-shus', ARRAY['sebacious glands', 'sebaceos glands']::text[]),
('Corpus callosum', 'anatomy', 'KOR-pus ka-LOH-sum', ARRAY['corpus colosum', 'corpus callosem']::text[]),
('Thalamus', 'anatomy', 'THAL-a-mus', ARRAY['thalimus', 'thalmus']::text[]),
('Basal ganglia', 'anatomy', 'BAY-sal GANG-lee-a', ARRAY['basel ganglia', 'basal ganglea']::text[]),
('Brainstem', 'anatomy', 'BRAYN-stem', ARRAY['brain stem', 'brainsteam']::text[]),
('Occipital lobe', 'anatomy', 'ok-SIP-i-tal', ARRAY['occipitol lobe', 'occiptal lobe']::text[]),
('Temporal lobe', 'anatomy', 'TEM-po-ral', ARRAY['tempral lobe', 'temperal lobe']::text[]),
('Parietal lobe', 'anatomy', 'pa-RY-e-tal', ARRAY['parietel lobe', 'pariatal lobe']::text[]),
('Frontal lobe', 'anatomy', 'FRUN-tal', ARRAY['frontel lobe', 'fronal lobe']::text[]),
('Tricuspid valve', 'anatomy', 'try-KUS-pid', ARRAY['tricuspid vale', 'tricuspit valve']::text[]),
('Mitral valve', 'anatomy', 'MY-tral', ARRAY['mytral valve', 'mitrel valve']::text[]),
('Pulmonary valve', 'anatomy', 'PUL-mo-na-ree', ARRAY['pulminary valve', 'pulmonery valve']::text[]),
('Aortic valve', 'anatomy', 'ay-OR-tik', ARRAY['aortik valve', 'aortic vale']::text[]),
('Atrioventricular node', 'anatomy', 'ay-tree-o-ven-TRIK-yoo-lar', ARRAY['av node', 'atrio ventricular node']::text[]),
('Sinoatrial node', 'anatomy', 'sy-no-AY-tree-al', ARRAY['sa node', 'sino atrial node']::text[]),
('Ventricular septum', 'anatomy', 'ven-TRIK-yoo-lar SEP-tum', ARRAY['ventricula septum', 'ventricular septem']::text[]),
('Carotid artery', 'anatomy', 'ka-ROT-id', ARRAY['carotad artery', 'caratid artery']::text[]),
('Jugular vein', 'anatomy', 'JUG-yoo-lar', ARRAY['jugula vein', 'juggular vein']::text[]),
('Femoral artery', 'anatomy', 'FEM-or-al', ARRAY['femoril artery', 'femorel artery']::text[]),
('Popliteal artery', 'anatomy', 'pop-LIT-ee-al', ARRAY['poplitial artery', 'popletial artery']::text[]),
('Saphenous vein', 'anatomy', 'sa-FEE-nus', ARRAY['saphenus vein', 'safenous vein']::text[]);
